### ISSUE TITLE
「他自治体の対策サイト」がリンク切れ

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#104]
## 起こっている問題 / The Problem
- https://github.com/tokyo-metropolitan-gov/covid19/blob/development/forkedSites.md#readme

が移動した模様でリンク切れになっています。

移動先は、

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md

**Comment by amay077** [comment]
間違えて close してしまったので reopen

**Comment by maketomo** [comment]
初参加です。
やります。
