### ISSUE TITLE
３月１５日から３月１８日までのデータ更新

### ISSUE THREAD

**Issue by billhung** [code4nagoya/covid19#106]
## 起こっている問題 / The Problem
- １２１人から１３０人に、しかし感染者の詳細は愛知県サイトに見えない（人数だけ）。NHKの報道記事には書いてあるけど。

## スクリーンショット / Screenshot
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
![image](https://user-images.githubusercontent.com/2110915/77056924-82880b00-6a16-11ea-81df-5a3c54c5af8f.png)

## 起こっている問題の再現手段 / Steps to Reproduce
input
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
output
https://dev-covid19-aichi.netlify.com/?fbclid=IwAR2AAdR6BojfOMFFOH1ZRcyce14DNnOsADo8pSISYFZweDpkpb90o896Zjc

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by billhung** [comment]
あった、半分の情報...
３月１８日の5人の中の３人
https://www.pref.aichi.jp/site/covid19-aichi/pressrelease-ncov200318.html
３月１７日の２人の中の１人
https://www.pref.aichi.jp/site/covid19-aichi/pressrelease-ncov200317.html
３月１６日の２人の情報がない...？

**Comment by billhung** [comment]
あ、3月１６日の資料

**Comment by billhung** [comment]
とりあえず、今、分かった情報を入れました。
https://docs.google.com/spreadsheets/d/12qStuXjsI8GE8qI1mLPLV--6TQcxAMPDu3-k9RCHN1k/edit#gid=0
情報内の５人どうするか。
リリースまでの手順がわからないです。

**Comment by fussy113** [comment]
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html

![スクリーンショット 2020-03-20 11 11 56](https://user-images.githubusercontent.com/15154105/77130534-accfdc00-6a9b-11ea-8a49-6fb42585fc2e.png)

こちらにリストでまとまってるので、こちら見て更新する方が良さそうです。
(シートの権限ないので更新お願いしたいです。)

**Comment by billhung** [comment]
シートの権限を公開にしました、忘れてすみません。
PDFのところありがとう。
データを入力した
https://docs.google.com/spreadsheets/d/12qStuXjsI8GE8qI1mLPLV--6TQcxAMPDu3-k9RCHN1k/edit?userstoinvite=ozaki360%40gmail.com&ts=5e744bc1&actionButton=1#gid=0
出力したJSONも添付しております。
[20200320.json.txt](https://github.com/code4nagoya/covid19/files/4358805/20200320.json.txt)

**Comment by amay077** [comment]
2020/03/25 00:14 更新となっているようですのでこちらは close します。
