### ISSUE TITLE
サイドバーの「県内の最新感染動向」の下の罫線が消えてる

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#108]
## 起こっている問題 / The Problem
- 「県内の最新感染動向」の下の罫線が消えてしまっている。
- 本番環境には罫線があるので、どこかのタイミングで消してしまった可能性が高い。

## スクリーンショット / Screenshot
本番環境(罫線ある。正しい)
![スクリーンショット 2020-03-19 20 46 44](https://user-images.githubusercontent.com/749758/77065138-157b7200-6a24-11ea-9db8-2cfd36e888c7.png)
開発環境(罫線がなくなってる。)
![スクリーンショット 2020-03-19 20 46 51](https://user-images.githubusercontent.com/749758/77065140-16ac9f00-6a24-11ea-8fa9-b180f9016d04.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「県内の最新感染動向」の下の罫線を復活。

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takaHAL** [comment]
初参加です
やります！
