### ISSUE TITLE
東京のcopyrightを削除する

### ISSUE THREAD

**Issue by 1coin178** [code4nagoya/covid19#11]
## 起こっている問題 / The Problem
-東京メトロのcopyrightを非表示にする

## スクリーンショット / Screenshot

こちらを消す
![貼り付けた画像_2020_03_10_20_24](https://user-images.githubusercontent.com/9292002/76307960-271a9680-630d-11ea-8a8d-e1b121b10b48.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yukou-isshiki** [comment]
こちらですが、開発用サイトは既に暫定的に愛知県に変えてあります。

https://dev-covid19-aichi.netlify.com/
