### ISSUE TITLE
data.json の仕様変更。patients(県内発生事例) の削除と年代など集計項目の追加

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#1103]
## 改善詳細 / Details of Improvement
1. data.json の patients 項目（県内発生事例全件）を削除する
2. data.json の patients_summary（日ごとの感染者数） に、以下の日ごとの集計項目を追加する
  - 住居地
  - 年代
  - 性別

## 目的

- #1099 の実施のために、日付-年代別の感染者数データが必要
- patients をフロントエンドで集計することもできるが、件数が増えてきたため、 data.json の容量が増えデータ転送と計算コストが増大
- そのため集計済みのデータを転送し、フロントエンドではそれを利用するだけとしたい
- 現状 patients は住居地ごとの集計に使用されているのみであり、住居地ごとの集計済みのデータがあれば patients は不要になる
- 性別ごとの集計は現在は使用しないが、今後のために追加しておく
- data.json のファイルサイズは、現行は **7MBytes** 超であるが、この提案を適用すると **630KBytes** 程度に削減される。
- patients.csv はそのまま公開し続けるので 新規感染者数グラフの注記で案内しているリンクは維持される

## データ定義

**現行仕様**

```json
{
  "lastUpdate": "2021/01/03 18:01",

  "patients": {
    "date": "2021/01/03 18:16",
    "data": [
      {
        "No": "1",
        "発表日": "2020/01/26 00:00",
        "年代・性別": "40代男性",
        …
      }
    ],

  "patients_summary": {
    "date": "2021/01/03 18:01",
    "data": [
      {
        "日付": "2020-01-26",
        "小計": 1,
      },  
// 以下略
```

**提案仕様**

```json
{
  "lastUpdate": "2021/01/03 18:01",
  "patients_summary": {
    "date": "2021/01/03 18:01",
    "data": [
      {
        "日付": "2020-01-26",
        "小計": 1,
        "住居地": {
          "名古屋市": 6,
          "犬山市": 5,
          "豊橋市": 4,
          …
        },
        "年代": {
          "10代未満": 2,
          "10代": 1,
          …
        },
        "性別": {
          "女性": 1,
          "男性": 1,
          …
        }
      },  
// 以下略
```

## 実装手順

 1. https://github.com/code4nagoya/covid19-aichi-tools にて、patients_summary へ 住居地、年代、性別 の集計データを追加（patients の削除はまだ）
 2. フロントエンド側（本repo）で、patients 使用箇所（市町村別感染状況）を 1 で追加した集計データの使用に切り替え
 3. https://github.com/code4nagoya/covid19-aichi-tools にて、patients を削除

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
あ、性別は年代の中に移動させようかなあと考え中です。
これだと、男女年齢別感染状況グラフ も実現できます。

```json
{
  "lastUpdate": "2021/01/03 18:01",
  "patients_summary": {
    "date": "2021/01/03 18:01",
    "data": [
      {
        "日付": "2020-01-26",
        "小計": 1,
        "住居地": {
          "名古屋市": 6,
          "犬山市": 5,
          "豊橋市": 4,
          …
        },
        "年代": {
          "10代未満":
            {
              "女性": 1,
              "男性": 5,
              …
            },
          "10代":
            {
              "女性": 3,
              "男性": 2,
              …
            },
          …
        }
      },  
// 以下略
```

**Comment by imabari** [comment]
兵庫県のようにdata.jsonを分割したほうが簡単そう
https://github.com/stop-covid19-hyogo/covid19-scraping/tree/gh-pages

jsonの構造が複雑なのでpandasから直接to_dictでの変換は難しい

pandas.DataFrame, Seriesを辞書に変換（to_dict）
https://note.nkmk.me/python-pandas-to-dict/

**Comment by imabari** [comment]
個別の集計はできますが結合するのが難しい
とりあえず無理やり結合して作成
https://github.com/imabari/covid19-data/blob/master/aichi/data.json

**Comment by amay077** [comment]
ゴリゴリですけど、
https://github.com/code4nagoya/covid19-aichi-tools/pull/84/files
の実装で目的のデータにはなってるようです。

**Comment by imabari** [comment]
結合方法リストで日付ソートで結合したのですが
たしかに日付をキーにループいいですね
また明日作り直してみます

作成時に気になったのが住所地がCJK部首になっていたのと年代に一代とか高齢者になっているところがありましたこれは変換したほうがいいのでしょうか？

**Comment by amay077** [comment]
data.json は可能な限り正規化したいところではありますね。
現行はフロントエンド側で行っていて負荷になっているところもあります。

### 住所地がCJK部首

これは正規化して排除したいです。現行では https://github.com/code4nagoya/covid19/blob/ce61180da24f7638e374556c8d5d4f2bcdcf60d9/data/city_data.json のようなマスタをフロントエンド側で持っていて突き合わせています。
data.json 生成時に、下のようにできるとフロントエンドでの負荷を減らすことができますね。

```json
        "住居地": {
          "23100": 6,  ←名古屋市
          "23215": 5,  ←犬山市
          "23201": 4,  ←豊橋市
          …
        },
```

### 年代に一代とか高齢者

これらは「その他」としてまとめるのがよいでしょうか。
「年代」は、以下のいずれかに該当する形がよさそうです。
半角数値の表記揺れ（全角）には対応しておいた方が良さそうですが。

- "10代未満"
- "10代"
- "20代"
- "30代"
- "40代"
- "50代"
- "60代"
- "70代"
- "80代"
- "90代"
- "100代"
- "110代"
- "その他"

### 性別

性別についても

- "男性"
- "女性"
- "その他"

のいずれかに該当させるのがよいと思います。
現状、元PDF には 男性、女性 のどちらかのみでした。

**Comment by imabari** [comment]
年代はいまのところ半角のみでしたので半角は処理していません
"110代"と"その他"はないので特に修正していません

https://imabari.hateblo.jp/entry/2021/01/04/115005

**Comment by imabari** [comment]
住居地の愛知県の市町村以外を抽出、現在は全部県外で処理しています

|住居地|カウント|
|:----|:----|
|岐阜県|23|
|東京都|18|
|尾張地方|11|
|三重県|11|
|三河地方|5|
|神奈川県|3|
|静岡県|3|
|兵庫県|2|
|千葉県|2|
|中国武漢市|2|
|福岡県|2|
|京都府|2|
|大阪府|2|
|福井県|1|
|滋賀県|1|
|土岐市|1|
|可児市|1|
|一宮保健所管内|1|
|不定|1|
|愛媛県|1|
|茨城県|1|
|石川県|1|
|沖縄県|1|
|岐阜市|1|

**Comment by amay077** [comment]
@imabari さん、ありがとうございます。
部分的に利用させていただきました。→ https://github.com/code4nagoya/covid19-aichi-tools/pull/84/commits

結果、以下のような仕様にします。

- 住居地は、市町村名 →「市町村コード」に
  - 愛知県市町村群以外はコードを ``NOT_FOUND`` に
- 年代は、``[10代未満, 10代, … 110代]`` とし、これに該当しないデータは ``その他`` に集約する
- 性別は、``[男性, 女性]`` とし、これに該当しないデータは  ``その他`` に集約する

```json
{
  "lastUpdate": "2021/01/03 18:01",
  "patients_summary": {
    "date": "2021/01/03 18:01",
    "data": [
      {
        "日付": "2020-01-26",
        "小計": 1,
        "住居地": {
          "23100": 6,
          "23215": 5,
          "23201": 4,
          …
          "NOT_FOUND": 3
        },
        "年代": {
          "10代未満":
            {
              "女性": 1,
              "男性": 5,
              "その他": 1,
            },
          "10代":
            {
              "女性": 3,
              "男性": 2
            },
          …
          "その他":
            {
              "女性": 1,
              "男性": 0
            }
        }
      },  
// 以下略
```

**Comment by takainou** [comment]
対応ありがとうございます。1点確認させて下さい。「10**代**未満」は「10**歳**未満」ではないでしょうか？
> 年代は、[10代未満, 10代, … 110代] とし、これに該当しないデータは その他 に集約する

**Comment by imabari** [comment]
8749の人は60代 女性でスペースが入っている
10歳未満でカウントされてないようです

**Comment by amay077** [comment]
> 「10代未満」は「10歳未満」ではないでしょうか？

おっとそうですね、修正します。

> 8749の人は60代 女性でスペースが入っている

なるほど、トリミングが必要でしたね、対応します。

**Comment by imabari** [comment]
年代はいまのところ半角数字ですが
年代・性別の時点で先に文字コード正規化して半角数字に変換を追加

トリミングは.str.strip()でできます

# 文字コード正規化
df["年代・性別"] = df["年代・性別"].str.normalize("NFKC")

# トリミング
df["年代"] = df["年代"].str.strip()

**Comment by takainou** [comment]
年代の表記揺れが起きているのは、「10歳未満**代**男性」「10歳未満**代**女性」でしょうか。
所管保健所毎のデータでは年代(10/20/30...)と性別(男/女)を別カラムで保持されており、それを1カラムに結合する際、"代"と"性"を入れているようで、「10歳未満**代**男性」「10歳未満**代**女性」と10歳未満にも代が付いている事があります。
![image](https://user-images.githubusercontent.com/63571899/103595840-d8935400-4f3f-11eb-9408-4e0acd928606.png)
![image](https://user-images.githubusercontent.com/63571899/103595859-e2b55280-4f3f-11eb-9261-04234dcaefa3.png)

既出の年代不明の2人「高齢者女性」「ー代女性」は、死亡された方から新型コロナウイルスが検出された症例で、その場合、ご遺族の意向により非公表となっているようです。愛知県公表の陽性者で年代不明はこの2人だけの認識です。
![image](https://user-images.githubusercontent.com/63571899/103596870-3a54bd80-4f42-11eb-904d-eca3d6e81499.png)
![image](https://user-images.githubusercontent.com/63571899/103596893-4b9dca00-4f42-11eb-84c1-9d0be2135adf.png)
![image](https://user-images.githubusercontent.com/63571899/103596749-f9f53f80-4f41-11eb-9b6c-8fab695c19d7.png)
![image](https://user-images.githubusercontent.com/63571899/103596945-6ec87980-4f42-11eb-9bdd-3a7e1df940ae.png)

**Comment by imabari** [comment]
|            |   年代 |
|:-----------|-------:|
| 20代       |   4231 |
| 30代       |   2564 |
| 40代       |   2454 |
| 50代       |   2242 |
| 60代       |   1456 |
| 70代       |   1429 |
| 10代       |   1147 |
| 80代       |    937 |
| 10歳未満   |    517 |
| 90代       |    274 |
| 100代      |      8 |
| 10歳未満代 |      2 |
| 60代       |      1 |
| ー代       |      1 |
| 高齢者     |      1 |

置換方法が違うのでpandasでしたら

```python
df["年代"] = df["年代"].replace("10歳未満代", "10歳未満")

ages_list = [
    "10歳未満",
    "10代",
    "20代",
    "30代",
    "40代",
    "50代",
    "60代",
    "70代",
    "80代",
    "90代",
    "100代",
]
# リスト以外はその他
df["年代"] = df["年代"].where(df["年代"].isin(ages_list), "その他")
```

**Comment by takainou** [comment]
1/3時点の「data.jsonのpatients_summary項目」と「当方手元データ」にて、以下の比較を行い、合致しました。
・日毎 年代別
・累計 男女年代別
・累計 居住地別
・累計(12/14以降) 居住地別

差分は「当方手元データ」では除いている22人(中国人渡航者2人、再陽性16人、名古屋市重複分4人)のみでした。

1/3時点には「10歳未満代」は有りません(1/4時点に発生)。

**Comment by imabari** [comment]
チェック用に「Open in Colab」のアイコンをクリックすると「google colaboratory」で実行できます
https://github.com/imabari/covid19-data/blob/master/aichi/aichi_patients_check.ipynb

**Comment by amay077** [comment]
現状こんな感じです。

1. :heavy_exclamation_mark: ［済 → 要修正 https://github.com/code4nagoya/covid19/issues/1103#issuecomment-754330987  https://github.com/code4nagoya/covid19/issues/1103#issuecomment-754493940 ］ covid19-aichi-tools にて、patients_summary へ 住居地、年代、性別 の集計データを追加
2. :ballot_box_with_check: [済] フロントエンド側（本repo）で、patients 使用箇所（市町村別感染状況）を 1 で追加した集計データの使用に切り替え
3. [未着手] https://github.com/code4nagoya/covid19-aichi-tools にて、patients を削除

**Comment by amay077** [comment]
@imabari さんご提供のソース https://github.com/code4nagoya/covid19/issues/1103#issuecomment-754493940 を、概ね組み込みました。

全て完了のつもりです。

1. :ballot_box_with_check: ［済 https://github.com/code4nagoya/covid19/issues/1103#issuecomment-754330987  https://github.com/code4nagoya/covid19/issues/1103#issuecomment-754493940 ］ covid19-aichi-tools にて、patients_summary へ 住居地、年代、性別 の集計データを追加
2. :ballot_box_with_check: [済] フロントエンド側（本repo）で、patients 使用箇所（市町村別感染状況）を 1 で追加した集計データの使用に切り替え
3. :ballot_box_with_check: [済] https://github.com/code4nagoya/covid19-aichi-tools にて、patients を削除

**Comment by imabari** [comment]
PDFファイルのスクレイピング部分

PDFの右側が2020年、左側が2021年という前提なら

https://qiita.com/barobaro/items/e24c4842013b3bdec263
```python
for i, tag in enumerate(
    soup.find("span", text="▶ 愛知県内の発生事例").parent.find_all(
        "a", href=re.compile(".pdf$")
    )[::-1]
):
```

**Comment by amay077** [comment]
今後の愛知県の対応次第なんですけど、現状のままだとすると来月には、右側のPDFだけで2020年と2021年が混在する可能性が高いです。。

|No|発表日|年代・性別…|
|:-----------|-------|-------|
|1|1月26日|40代男性,中国,中国武漢市…|
|2|1月28日|40代男性,中国,中国武漢市...|
|3|2月14日|60代男性,日本,名古屋市…|
|…|||
|16576|12月31日|,60代男性,,名古屋市…|
|16577|1月1日|40代女性,,稲沢市…|

なので、2019 を初期値として、発表月 が 「1月に変わる」 度にインクリメントする（No:1 で 2020、No:16577 で 2021）のがよいかなあと考えてます。

愛知県HP で年ごとに PDF を分けてくれるか、発表日に年まで記載してくれるのが一番ありがたいですね。

**Comment by imabari** [comment]
混在するようになるとさすがに年が追加されるとは思いますが

12から1に変わるとカウント

```python
df_date = df["発表日"].str.extract("(\d{1,2})月(\d{1,2})日").rename(columns={0: "month", 1: "day"}).astype(int)
ser = df_date["month"] - df_date["month"].shift(1, fill_value=0)

# 12から1に変わるとカウント
df_date["year"] = 2020 + (ser == -11).cumsum()

df["発表日"] = pd.to_datetime(df_date)
```

**Comment by takainou** [comment]
リリースありがとうございました。

「市町村別感染状況」と「当方手元データ」にて、以下の比較を行い、合致しました。
・1/4時点(累計、12/21-1/4)
・1/5時点(累計、12/21-1/5)

同一PDFファイルで「年が未記載かつ2020年と2021年混在」対応は厄介ですね。どこか以降で年を切り替える事になるかと思いますが、名古屋市が事後修正で追加したような事例(No.6882-6939)が再発、例えば「3月になってから12,1月の陽性者を追加」されたりすると、手に負えないですね。[厚労省HPの空港検疫(1/5)](https://www.mhlw.go.jp/stf/newpage_15861.html)では過去到着分(11/12)を「年未記載かつ年混在」で公表されてましたので官公庁では普通なのかもしれません。

**Comment by amay077** [comment]
同一PDFファイルで「年が未記載かつ2020年と2021年混在」対応については、その状況になったら別途 issue で検討することとして、本issue は対応完了したので close しますね。

**Comment by takainou** [comment]
愛知県が県管轄で「3名の公表漏れ及び1名の重複」を[公表](https://www.pref.aichi.jp/site/covid19-aichi/pressrelease-ncov2102254.html)し、事後追加(No.25753-25755)となりました。発生事例一覧「2月」のPDFファイルで「年が未記載かつ2020年と2021年混在」しています。
![image](https://user-images.githubusercontent.com/63571899/109240658-372bce80-781b-11eb-9efa-d1a2e884dd51.png)
なお、重複で削除(No.6950)は特に対応されず(名古屋市重複分と同様)、「1月まで」のPDFファイルは更新されずそのまま残ってます。

> 同一PDFファイルで「年が未記載かつ2020年と2021年混在」対応は厄介ですね。どこか以降で年を切り替える事になるかと思いますが、名古屋市が事後修正で追加したような事例(No.6882-6939)が再発、例えば「3月になってから12,1月の陽性者を追加」されたりすると、手に負えないですね。

想定していましたが、やはり対応は厄介ですよね…。


また、先日発生した患者発生届取り下げによる欠番の2人目(No.25653)も[公表](https://www.pref.aichi.jp/site/covid19-aichi/pressrelease-ncov2102253.html)されています。
![image](https://user-images.githubusercontent.com/63571899/109241213-5840ef00-781c-11eb-90b2-060ee306b185.png)

**Comment by amay077** [comment]
欠番によってNo. が再採番されるのが懸念でしたが大丈夫そうなので、現状の「No. により年を判別する」でよさそうかな、と思います。

**Comment by takainou** [comment]
> 現状の「No. により年を判別する」

欠番側はうまく処理されているようですが、事後追加3人は2020年を2021年で処理されているようです。
patients.csv
![image](https://user-images.githubusercontent.com/63571899/109307145-89083f00-7883-11eb-86d2-cda9fc5b6b61.png)

data.jsonのpatients_summaryには、未来日付が反映されないようになっているのか、3人分のレコード(2021-11-30と2021-12-11)は無く、3人分不足しています(2020/11/30:109人→108人、2020/12/11:198人→196人)。
![image](https://user-images.githubusercontent.com/63571899/109308578-8d355c00-7885-11eb-839c-14eaa7dc0dae.png)
![image](https://user-images.githubusercontent.com/63571899/109308623-9d4d3b80-7885-11eb-91c7-c30504fc12ea.png)

「検査陽性者の状況」の陽性者数(累積)と「累計感染者数」の数値ズレは、34人(中国人渡航者2人、再陽性27人、重複分5人)となる所、事後追加3人分が不足し、31人差(25,737人と25,768人)となっております。

全体の挙動としては問題なく、過去日付の3人ズレですので、その他のズレも考えれば影響は軽微と考えております。

**Comment by imabari** [comment]
@amay077 さん
25753-25755は別途リストで対応でしょうか？

```
y = 2021 if s.name > 16576 else 2020

if s.name in [2753, 25754, 25755]:
    y = 2020
```

**Comment by amay077** [comment]
そうですね、別途リストで対応します。
issue 立てました → https://github.com/code4nagoya/covid19-aichi-tools/issues/93
