### ISSUE TITLE
「最新のお知らせ」を愛知県のコロナに関するお知らせページへのリンクに変更

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#111]
## 起こっている問題 / The Problem
- 現状「最新のお知らせ」を更新しているリソースが不足しており更新できていない。
- グラフについては随時更新されているのに、「最新のお知らせ」の日付が3/11になっているので、サイト全体が更新されていないように見えてしまう。

## スクリーンショット / Screenshot
<img width="706" alt="スクリーンショット 2020-03-20 14 38 57" src="https://user-images.githubusercontent.com/749758/77139303-cd5a5f00-6ab8-11ea-980e-d44df4da1a11.png">

## 期待する見せ方・挙動 / Expected Behavior
- 北海道のサイトみたいに、愛知県の「[感染症対策ページ](https://www.pref.aichi.jp/site/covid19-aichi/)」へのリンクを貼るのが良さそう。

<img width="598" alt="スクリーンショット 2020-03-20 14 38 51" src="https://user-images.githubusercontent.com/749758/77139310-d814f400-6ab8-11ea-9afb-3d967b2b7a43.png">

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takaHAL** [comment]
こちらやります
