### ISSUE TITLE
情報が古い（トップからリンクされてない）ページを削除する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#1113]
## 改善詳細 / Details of Improvement
- アクセス解析結果によると、トップページからリンクされてない、現在は更新されていないページ へのアクセスが確認される
- これらが閲覧されることは望ましくないので、ページを削除する
- 削除対象は以下のページ群
  - /flow
  - /worker
  - /parent

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/103637214-7a419200-4f8e-11eb-8786-2ecca2e067c9.png)

## 期待する見せ方・挙動 / Expected behavior
- 削除対象ページが閲覧できなくなる
- その URL にアクセスしたときに top へ転送されると尚良いが、404 エラーでも構わない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yoshitaka7** [comment]
やります！

**Comment by amay077** [comment]
マージしました、ありがとうございました！
