### ISSUE TITLE
各データソースの参照先が変更されています

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#112]
各データソースとして示している「愛知県内の発生状況について」（ https://www.pref.aichi.jp/soshiki/kenkotaisaku/novel-coronavirus.html ）のリンク先が
現在は「愛知県新型コロナウイルス感染症対策サイト」への誘導ページになってしまっています。

データソースのリンク先を
愛知県新型コロナウイルス感染症対策サイト内「愛知県内の感染者・遺伝子検査件数」
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
に変更する必要があるように感じます。

**Comment by takaHAL** [comment]
追加で
お子様をお持ちの皆さまへのページにある「新型コロナウイルス感染症にかかる相談窓口について」のリンク先についてhttps://www.pref.aichi.jp/soshiki/kenkotaisaku/novel-coronavirus.html#soudan

上記のリンクからhttps://www.pref.aichi.jp/site/covid19-aichi/soudan.html
こちらに変更する必要もある気がします

**Comment by takaHAL** [comment]
こちらやります
