### ISSUE TITLE
/flow ページをサイドバーに掲載する

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#116]
## 起こっている問題 / The Problem
- 現在 /flow ページは直リンクでしか開けないようになっている
- 3/19に愛知県保健医療局健康医務部健康対策課及び名古屋市健康福祉局健康部感染症対策室感染症係に新たに公開予定である旨を案内済。

## スクリーンショット / Screenshot
このページ。

<img width="1156" alt="スクリーンショット 2020-03-21 14 33 13" src="https://user-images.githubusercontent.com/749758/77220182-f514fa00-6b80-11ea-948b-d2150a931403.png">

## 期待する見せ方・挙動 / Expected Behavior
東京都だとこんな感じ。「新型コロナウイルス感染症が心配なときに」のリンク。

<img width="238" alt="スクリーンショット 2020-03-21 14 33 20" src="https://user-images.githubusercontent.com/749758/77220267-c2b7cc80-6b81-11ea-8f23-ced074372ae1.png">

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
確かコメントアウトしただけなので、やります。
