### ISSUE TITLE
HackMDの情報をGitHub Wikiに移管

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#117]
## 改善詳細 / Details of Improvement
- HackMDにまとめていた情報をGitHubに移管したい。
- https://hackmd.io/@pFiNTh1LSJaklz5Kl13-6Q/r1D-4OLH8

## スクリーンショット / Screenshot
<img width="839" alt="スクリーンショット 2020-03-21 17 41 14" src="https://user-images.githubusercontent.com/749758/77222922-2e5a6380-6b9b-11ea-9ca1-7543a1154a4f.png">

## 期待する見せ方・挙動 / Expected behavior
- https://github.com/code4nagoya/covid19/wiki に移管したい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takayashibagaki** [comment]
やります！

**Comment by takayashibagaki** [comment]
とりあえずHackMDの内容をそっくりそのまま移しました。

**Comment by ozo360** [comment]
takayashibagakiさんと競合してしまっていますが
3ページくらいに分けたいという意向を反映して以下を更新しました。
https://github.com/code4nagoya/covid19/wiki
https://github.com/code4nagoya/covid19/wiki/ABOUT_DEVELOPMENT
https://github.com/code4nagoya/covid19/wiki/HOW_TO_DEPLOY
https://github.com/code4nagoya/covid19/wiki/UPDATE_DATA.JSON

**Comment by takayashibagaki** [comment]
すみません、ありがとうございます！！！

**Comment by ozo360** [comment]
こちらこそなんかすみません

**Comment by hajime-miyauchi** [comment]
こちら完了してるのでCloseしますねー。
