### ISSUE TITLE
「貢献の仕方」をアップデート

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#118]
## 起こっている問題 / The Problem
- 「開発責任者をしています、関です。」の記載が残っている。
- CONTRIBUTORS.mdのリンク先が東京のCONTRIBUTORSになっている。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/749758/77228569-a771af00-6bcb-11ea-996e-26471d91e491.png)

![image](https://user-images.githubusercontent.com/749758/77228562-9aed5680-6bcb-11ea-848f-f4117d7f4893.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「開発責任者をしています、関です。」の記載を削除
- CONTRIBUTORS.mdへのリンクを[Wiki]( https://github.com/code4nagoya/covid19/wiki/Contributors )に変更。

**Comment by hajime-miyauchi** [comment]
https://github.com/code4nagoya/covid19/blob/development/.github/CONTRIBUTING.md

**Comment by amay077** [comment]
対応済と思われるのでクローズします。
