### ISSUE TITLE
本番公開されたらOGPのURL, Linkを差し替える

### ISSUE THREAD

**Issue by ctyo** [code4nagoya/covid19#12]
## 起こっている問題 / The Problem
OGP情報が東京のままなので修正する
- https://stopcovid19.metro.tokyo.lg.jp/ogp.png

ついでにReadmeの画像も直しましょう

ここを直せば良さそう
 - https://github.com/code4nagoya/covid19/blob/development/nuxt.config.ts

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ctyo** [comment]
ドメインが決まったのでOGPもなおしますー
https://stopcovid19.code4.nagoya/

**Comment by fussy113** [comment]
- OGPの修正
- README画像

完了しているのでissueクローズします。

@ctyo 素早い対応ありがとうございますー！
