### ISSUE TITLE
グラフのインジケーターが短い期間だと重なってしまって見づらい

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#1243]
## 改善詳細 / Details of Improvement
- グラフのインジケーターが短い期間を指定すると重なってしまって「いつから」の日付が判別しづらい。
- 付随して細かい期間調節がしづらくなってきた。棒グラフの場合はそれでも良いが、市町村別感染状況のようなグラフは細かい期間調節をしたいシーンもありそう(直近一週間など)。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/749758/114146821-0202b800-9953-11eb-8701-e82346f7061e.png)

## 期待する見せ方・挙動 / Expected behavior
- 「日付が判別しづらい」についてはどこかに指定期間をテキストで「〇月〇日～〇月〇日」と表示することで解決できそう。(実装コストも高くなさそう)
- 「細かい期間調整がしづらい」については良い方法が思いつかず。ここで議論して別Issueとしても良い気がしてます。

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by yoshitaka7** [comment]
やります！

**Comment by hajime-miyauchi** [comment]
ありがとうございます！

**Comment by amay077** [comment]
@yoshitaka7 
遅くなりましたがマージしました、ありがとうございました！
