### ISSUE TITLE
より非公式感があるページデザインに変更する

### ISSUE THREAD

**Issue by mikkame** [code4nagoya/covid19#138]
## 改善詳細 / Details of Improvement
- 現在だとオフィシャル感が強い

## 期待する見せ方・挙動 / Expected behavior
- より非公式感を醸し出す。
- 愛知県さんに迷惑がかからないように非公式、有志が作成したと言うことを明確にする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hajime-miyauchi** [comment]
Issue立てありがとうございます。
目的はあくまで「**愛知県への問い合わせがいかないように配慮したほうが良い**」という趣旨で、そのための手段としてデザインの変更なのか、文言の変更なのかを検討するということで皆様ご意見ください。

例えば私が思いつくのは下記です。

- 北海道みたいにページのタイトルに「まとめサイト」を入れる。
- 「このページは非公式の有志がたちあげたものなので、県に問い合わせないでください」という趣旨の文言をいれる。

**Comment by mikkame** [comment]
とりあえず明日日中に仮で実装してPRを出す予定です。
まーじしてもいいし捨ててもいいです。代案があればそれを入れてRevertする感じで

**Comment by amay077** [comment]
トップページに「非公式」である旨を載せる。

![image](https://user-images.githubusercontent.com/401369/77597792-450a0d00-6f43-11ea-9c4c-1c05f9609bd3.png)

画像にも「非公式」を載せる。

https://github.com/code4nagoya/covid19/blob/development/static/ogp.png
https://github.com/code4nagoya/covid19/blob/development/static/logo.svg
https://github.com/code4nagoya/covid19/blob/development/static/icon.png

…くらいですかねえ。
