### ISSUE TITLE
手動によるデータ更新用のissueが必要

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#142]
## 起こっている問題 / The Problem
- data.json更新のプルリクエストを投げる際に使えるissueが必要

## スクリーンショット / Screenshot
プルリクエストのテンプレートに「Issue 番号がない PR は受け付けません。」とある
![image](https://user-images.githubusercontent.com/36749946/77622826-51618a80-6f82-11ea-8333-62ad70c3bd3b.png)

## 期待する見せ方・挙動 / Expected Behavior
- データ更新時に使いまわせるissueを立てて欲しい

**Comment by amay077** [comment]
作りました → #146
