### ISSUE TITLE
data.json の手動更新を行う

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#146]
**``data.json`` の更新は GitHub Actions により半自動で行われるようになったため、通常手動更新の必要はなくなりました**

こちらはデータ更新時の使いまわし用 issue です。

``data.json`` などのデータを手動で更新する際、Pull request に本 issue の番号 #146 を指定してください。

こちらは close はしないでください。
Pull request  には ``- close #146`` ではなく ``- #146`` と記述してください。

**Comment by amay077** [comment]
「検査実施数」のチャートデータの手動更新方法については以下のとおりです。
※検査実施数 も自動更新できるようになったら、この方法は不要になります。

■修正するファイル

``/data/data_inspections.json``

■修正箇所

1. 3行目あたりの `` "date": "2020/03/25 00:01",`` の日付を修正
2. ``data: [`` の末端に 日付 と 小計 の組を追加

■ 修正前 → 修正後の例

**修正前**

```
      },
      {
          "日付": "2020-03-25",
          "小計": 164
      }
    ]
  }
}
```

**修正後**

```
      },
      {
          "日付": "2020-03-25",
          "小計": 164
      },
      {
          "日付": "2020-03-27",
          "小計": 99
      }
    ]
  }
}
```

実際の修正内容は https://github.com/code4nagoya/covid19/commit/1bcba98b8a771ed1d16adea83e0217025a348eb0#diff-cfd57d81b096b06aacbf92e5b6d4efe1 を参照。

**Comment by ozo360** [comment]
このissueはもうcloseしちゃっていいのではないでしょうか

**Comment by amay077** [comment]
閉じましょう！
