### ISSUE TITLE
「新型コロナウイルス感染症が心配なとき」のフローが愛知県公式と少し違うので同じにする

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#148]
## 起こっている問題 / The Problem

新型コロナウイルス感染症が心配なとき のフローについて、
[愛知県公式](https://www.pref.aichi.jp/site/covid19-aichi/) (A とする) と [https://stopcovid19.code4.nagoya/](https://stopcovid19.code4.nagoya/) (S とする) に
以下の違いがある。

- 症状が4日以上続いているに「あてはまる」場合の連絡先が、A では「帰国者・接触者相談センター」だが、S では「新型コロナ 受診相談窓口」である

## スクリーンショット / Screenshot

**A : 愛知県公式**

![image](https://user-images.githubusercontent.com/401369/77744189-9bb73a00-705c-11ea-9361-ad90160c03a5.png)

**S : stopcovid19.code4.nagoya**

![image](https://user-images.githubusercontent.com/401369/77744278-bdb0bc80-705c-11ea-8906-fb532286eba8.png)

## 期待する見せ方・挙動 / Expected Behavior

症状が4日以上続いているに「あてはまる」場合の連絡先は、S も A と同じく、「帰国者・接触者相談センター」にする

**Comment by penpen4690** [comment]
対応いたします
