### ISSUE TITLE
「新型コロナウイルス感染症が心配なとき」のモバイル向けページの色をPC向けと同じにする

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#149]
## 起こっている問題 / The Problem
- PC向けは全体テーマと同じく赤系の色だが、モバイル向けは tokyo 版の名残で緑系のままになっている

## スクリーンショット / Screenshot

**PC向け**

![image](https://user-images.githubusercontent.com/401369/77745350-6f042200-705e-11ea-95fa-a717c2ae7cb3.png)

**モバイル向け**

![image](https://user-images.githubusercontent.com/401369/77745398-87743c80-705e-11ea-9e05-e8a29573e3bc.png)

## 期待する見せ方・挙動 / Expected Behavior
- モバイル向けもPC向けと同じく赤系にする
- 公開当時、モバイル向けの図は画像であり、画像の色を変更するのが面倒だったので後回しにした経緯がある
- [現在の tokyo 版](https://stopcovid19.metro.tokyo.lg.jp/flow) では、画像は使われておらず HTML/CSS で実現されているため、改めてこのページのみ tokyo 版を取り込み直した方がよいかも知れない

**Comment by ctyo** [comment]
こちらやってみますー
