### ISSUE TITLE
陽性患者の属性に適切ではない備考が表示されている

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#151]
## 起こっている問題 / The Problem
- 陽性患者の属性の備考として「※退院には、死亡退院を含む」が表示されている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/77748000-fb184880-7062-11ea-9c43-5abc5eda7ab5.png)

## 期待する見せ方・挙動 / Expected Behavior
- 陽性患者の属性の備考から削除する
- 検査陽性者の状況に付け加える（要検討）

**Comment by hajime-miyauchi** [comment]
取り急ぎ、「陽性患者の属性の備考から削除する」のところ対応しましたー。
