### ISSUE TITLE
Netlify の Deploy Previews の代替手法を検討する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#152]
## 課題

- Pull request 毎に検証用デプロイをしてくれる Netlify の Deploy Previews は便利だったが、無料使用枠のビルド時間制限を超えてしまい現在は未使用
- そのため現状は Pull request を自PCに手動で取り込んで確認する必要があり不便
- なので Netlify の Deploy Previews に代わる仕組みを検討する

## 改善詳細 / Details of Improvement

- GitHub Actions で PR 送信毎に Firebase Hosting にデプロイすることは技術的には可能と思われます -> [github Actionsで pushされたらfirebase hostingにdeployする - Qiita](https://qiita.com/reika_i/items/db38f955af950eed010e)
- [Firebase Hosting の制限](https://firebase.google.com/pricing) は問題なさそう
- Pull request 毎にデプロイ先を変える（サブディレクトリ？）ことができるかは要検証
- Netlify の 無料使用枠 を増やして？もらうという道もあるかもしれません（これが一番楽）

**Comment by hajime-miyauchi** [comment]
Netlify社にスポンサード頂いたことにより、無料使用枠が実質無制限となったため本Issueの課題が解決しました！
