### ISSUE TITLE
それぞれの出典元表記を修正

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#158]
## 起こっている問題 / The Problem
- 「陽性患者数」「陽性患者の属性」「検査実施数」グラフのデータ出典元の表記が「愛知県内の発生状況について」になっている。また、リンク先が [愛知県内の感染者・遺伝子検査件数
 ](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html)になっているが、実際は[愛知県新型コロナウイルス感染症トップページ](https://www.pref.aichi.jp/site/covid19-aichi/)からの出典もある。
- 「検査陽性者の状況」グラフは出典元の表記が無い。

## スクリーンショット / Screenshot
![県内の最新感染動向 | 愛知県 新型コロナウイルス感染症対策サイト 2020-03-28 19-27-58](https://user-images.githubusercontent.com/749758/77821117-08990580-712b-11ea-8c31-25f5925b0547.png)

## 期待する見せ方・挙動 / Expected Behavior
- 一旦、すべての表記を「出典:  愛知県新型コロナウイルス感染症対策サイト」とするのが良さそう。
- リンク先は[愛知県新型コロナウイルス感染症トップページ](https://www.pref.aichi.jp/site/covid19-aichi/)にするのが良さそう。

参考: 北海道 コロナウイルスまとめサイト
![image](https://user-images.githubusercontent.com/749758/77821134-26ff0100-712b-11ea-83eb-bec2a3eb3f6b.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mira-tech** [comment]
僕やりたいのですが...もう取り組んでますかね?

**Comment by hajime-miyauchi** [comment]
あー、ごめんなさい...もうやっちゃいました...

**Comment by hajime-miyauchi** [comment]
@mira-tech さん、ごめんなさい、これまだ手つかずでした！お願いできますか？

@mira-tech さんが直前に立ててくれた https://github.com/code4nagoya/covid19/issues/159 と勘違いしてました。すみません。

**Comment by mira-tech** [comment]
了解です！僕がやります！

**Comment by mira-tech** [comment]
質問なのですが、このIssueは```検査陽性者の状況 ```にも出典の文言を追加する、という認識で正しいでしょうか?

**Comment by hajime-miyauchi** [comment]
その認識で正しいです！

**Comment by hajime-miyauchi** [comment]
https://github.com/code4nagoya/covid19/pull/168

こちら上記PRで完了しているのでCloseします！
