### ISSUE TITLE
非公式であることへのトップページのお知らせの文言がタイポしてる

### ISSUE THREAD

**Issue by mira-tech** [code4nagoya/covid19#159]
## 起こっている問題 / The Problem
- #155 から追加された```当サイトは有志が作成したものです。お問い合わせは愛知県ではなく、当サイトまで運営まで。```の文言がタイポしている(#155 に書いてある変更内容と実装が合っていない)

## スクリーンショット / Screenshot
<img width="690" alt="スクリーンショット 2020-03-28 19 26 50" src="https://user-images.githubusercontent.com/30523995/77821039-3cbff680-712a-11ea-9dbc-232bd964c91b.png">

## 期待する見せ方・挙動 / Expected Behavior
<img width="656" alt="スクリーンショット 2020-03-28 19 41 54" src="https://user-images.githubusercontent.com/30523995/77821281-43e80400-712c-11ea-9292-d704a6746290.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hajime-miyauchi** [comment]
本当ですね！ありがとうございます。修正しますー。
