### ISSUE TITLE
各データソースの時点情報を明示できるようにしたい

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#162]
## 改善詳細 / Details of Improvement
- 公開情報の時点情報を表示したい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/77826741-93dac100-7154-11ea-9151-42b2b62bd3e5.png)
更新日時は27日18:52になっているがデータは26日20時現在として公開されたデータ

## 期待する見せ方・挙動 / Expected behavior
- 現在は更新時間（data.jsonの生成時間）は表示されているが1次情報に明記された時点情報と乖離してしまっている。
- 更新時間とは別にデータソースに記載された時点日時を表示したい

**Comment by amay077** [comment]
同じ issue があったのでリンクしときます。
https://github.com/tokyo-metropolitan-gov/covid19/issues/2652

**Comment by ari3der** [comment]
こちら未着手でしたらぜひ対応したいと思います。
リンクされている東京都のサイトと同様の表示で問題ないでしょうか？
