### ISSUE TITLE
検査実施数グラフが何の検査実施数なのか説明を入れる

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#165]
## 改善詳細 / Details of Improvement
- 検査実施数グラフが何の検査実施数なのか東京都を参考に説明を入れる

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/77836969-a0840700-719e-11ea-8207-c37bac42284a.png)
![image](https://user-images.githubusercontent.com/36749946/77836979-b1347d00-719e-11ea-89d0-edf267089bb8.png)
![image](https://user-images.githubusercontent.com/36749946/77836990-cad5c480-719e-11ea-8a56-3a3a7505be70.png)

## 期待する見せ方・挙動 / Expected behavior
- 「愛知県衛生研究所、名古屋市衛生研究所、厚生労働省機関で実施した県内の新型コロナウイルスの遺伝子検査件数」であることを明示
- 「同一の対象者について複数の検体を検査する場合あり」であることを明示（要確認）

**Comment by yuuton414** [comment]
着手します

**Comment by mira-tech** [comment]
取り組みます！

**Comment by mira-tech** [comment]
この`「同一の対象者について複数の検体を検査する場合あり」であることを明示`についての確認なのですが、[国(厚生厚労省)発表の愛知県の検査数](https://www.mhlw.go.jp/content/10906000/000619392.pdf)(**重複は除外の明記**)と[愛知県が出している検査数](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html)(**重複などに関しては明記なし**)がそれぞれ2,917、5,386と2000件ほど愛知県発表の方が多くなっております。(厚生厚労省の方が15日ほどカウントし始めるのが早いので正確な比較ではない)

なので愛知県が発表している検査数は同一の対象者に複数の検体を検査した物もカウントしてるのではないのでしょうか...?
