### ISSUE TITLE
検査実施数のデータ更新を自動化する&ファイルの統合

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#167]
## 改善詳細 / Details of Improvement

検査実施数 のチャートのデータは、``/data/data_inspections.json`` ですが、
他のチャートデータは、``/data/data.json`` です。

``/data/data_inspections.json`` を ``/data/data.json`` に統合し、
また、データの更新を自動化したいです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/77840592-29616980-71c4-11ea-86a5-938cb63109a7.png)

#### 現行

**data.json**

```
{
    "patients": {
        "date": "2020/03/29 00:51",
        "data": […]
    },
    "patients_summary": {
        "date": "2020/03/29 00:51",
        "data": […]
    },
    "lastUpdate": "2020/03/29 00:51",
    "main_summary": {
        "attr": "検査実施人数",
        "value": 2661,
        "children": […]
    }
}
```

**data_inspections.json**

```
{
  "inspections_summary": {
    "date": "2020/03/25 00:01",
    "data": […]
  }
}
```

#### 統合後

``inspections_summary: { }`` を ``data.json``  に含めます。

```
{
    "patients": {
        "date": "2020/03/29 00:51",
        "data": […]
    },
    "patients_summary": {
        "date": "2020/03/29 00:51",
        "data": […]
    },
    "lastUpdate": "2020/03/29 00:51",
    "main_summary": {
        "attr": "検査実施人数",
        "value": 2661,
        "children": […]
    },
    "inspections_summary": {
      "date": "2020/03/25 00:01",
      "data": […]
    }
}
```

### 自動更新

自動更新の方法は、 #73 に含めてもらうのを希望します（すみませんが内容をあまり追えてないです）。

データの1次ソースは、 https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html  の 「3．愛知県内の検査件数」の表です。

**Comment by hajime-miyauchi** [comment]
データ更新は現状はまだ下記covid19-aichi-toolsで行われているので、一旦下記ツールでも対応しておきますね。

https://github.com/code4nagoya/covid19-aichi-tools

対応するIssue。

https://github.com/code4nagoya/covid19-aichi-tools/issues/1

**Comment by hajime-miyauchi** [comment]
とりあえず、現時点(2020/03/30 23:44)の愛知県の発表情報をGoogleスプレッドシートに転記しました。

以下すべてMacで作業。

1. 愛知県のサイトをコピー
2. Excelで「形式を選択してペースト」で「テキスト」を選択してペースト
3. ExcelからコピーしてGoogleスプレッドシートにペースト
4. 「◯月◯日（◯曜日）〜◯月◯日（◯曜日）」が2行に渡ってしまっているので修正。（終了日を残す)
5. 検査日の「（◯曜日）」を手作業で削除して有効な日付データに変更
6. 検査日の表示形式を「◯月◯日」から「YYYY/MM/DD」の形式に変更

https://docs.google.com/spreadsheets/d/1ivROd_s3AmvY480XKEZR_COAlx08gOGxZYRYubxghP0/edit#gid=0

![image](https://user-images.githubusercontent.com/749758/77925159-7dad3c00-72df-11ea-86d3-e6c8e5aff443.png)

![image](https://user-images.githubusercontent.com/749758/77925791-455a2d80-72e0-11ea-908b-f0660be6cd5d.png)

**Comment by hajime-miyauchi** [comment]
@amay077 

data/data.jsonについてはこんな感じでどうですー？

https://github.com/code4nagoya/covid19/pull/173

変換ツールをアップデートしてdata.jsonを生成するようにしてみました。

https://github.com/code4nagoya/covid19-aichi-tools

現状は、他のデータと同様に愛知県のサイトからGoogleスプレッドシートに転記して、それをCSV出力してdata.jsonを生成してます。

**Comment by amay077** [comment]
> data/data.jsonについてはこんな感じでどうですー？

OK ですー #173 をマージしました。

**Comment by imabari** [comment]
data_inspections.jsonスクレイピング作成しました
https://github.com/imabari/aichi/blob/master/aichi_inspections_summary.py
