### ISSUE TITLE
サイドメニューの整理

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#176]
## 改善詳細 / Details of Improvement
- 愛知県公式LINE、Twitterアカウントをテキストリンクで追加
- 他自治体の対策サイトのリンク先を先頃立ち上がったばかりの https://stopcovid19.code4japan.org/ に変更。(スマホ対応等はまだだけどそこはおいおい整備されると思われる)

## スクリーンショット / Screenshot

![県内の最新感染動向 | 愛知県 新型コロナウイルス感染症対策サイト 2020-03-31 23-16-31](https://user-images.githubusercontent.com/749758/78037184-2920c400-73a6-11ea-99fb-ca0cbb0bb15a.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by scrpgil** [comment]
こちらやってみます!
LINE：https://liny.link/r/1653954481-KA3xJl9g?lp=8Zhyvz
Twitter：https://twitter.com/pref_aichi
でよかったですよね！

**Comment by scrpgil** [comment]
こちらマージされたのでクローズですかね？

**Comment by amay077** [comment]
クローズします！
