### ISSUE TITLE
「新型コロナウイルス感染症が心配なとき」の 「経済産業省 遠隔健康相談事業」を削除する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#184]
## 改善詳細 / Details of Improvement
- 「経済産業省 遠隔健康相談事業」は 3/31 で期限が切れたので削除する
-  [LINEヘルスケア はひきつづき無償利用が可能な模様](https://linecorp.com/ja/pr/news/ja/2020/3163) が可能な模様だが、「愛知県公式 LINE チャンネル」からもアクセス可能なので削除して問題ないと考える
- [first call の方は 3/31 までの申し込み分をもって無償提供は終了する模様](https://medpeer.co.jp/press/7616.html)

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/401369/78225082-8cc10380-7504-11ea-9526-42930b549f9d.png)

## 期待する見せ方・挙動 / Expected behavior
* 赤枠内を削除する
* モバイル用ページも

**Comment by penpen4690** [comment]
対応いたします
