### ISSUE TITLE
検査実施件数の合算値表記対応

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#194]
## 課題
- 愛知県の検査実施数の表（ https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html ）の過去日付の値が（県のお気持ちで）合算値になる
- https://stopcovid19.code4.nagoya/  の検査実施件数チャートには、合算値である旨を「※」で注記している
- が、この注記はソースコードにベタ書きで合算値が増える度に書き換えが必要なので面倒。
- data.json に備考を設けて、それを vue 側で表示するようにしたい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/401369/78535100-8b564a80-7826-11ea-9894-9ea6845d17b0.png)

![image](https://user-images.githubusercontent.com/401369/78535121-97daa300-7826-11ea-8252-3019b0f23fcc.png)

## 期待する見せ方・挙動 / Expected behavior
- Google Spreadsheet の検査実施数の表に  「合算」 列を追加して合算値である日付に「○」を手入力する
- データ生成ツールで、``data.json`` の  ``inspections_summary`` に ``{ "日付": "2020-03-01", "小計": "639", "合算": "○" },`` のように Spreadsheet の項目値を転記する
- vue 側で 「合算」に「○」が付いている日付を注記として表示する

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19-aichi-tools/issues/3

でツール側が対応されたら close します。

**Comment by ozo360** [comment]
https://github.com/code4nagoya/covid19/pull/197
とこちらの期待する見せ方・挙動では「合算」の位置が異なります。
2列目、3列目どちらが正しいでしょうか。
それともどちらでも問題ないでしょうか？

**Comment by amay077** [comment]
どちらでも問題ないです。（以下どちらも OK）

``{ "日付": "2020-03-01", "小計": 639, "合算": "○" }``
``{ "日付": "2020-03-01", "合算": "○", "小計": 639 }``

**Comment by amay077** [comment]
code4nagoya/covid19-aichi-tools#3 が対応されたのでこちらも Close します。
