### ISSUE TITLE
検査実施件数のグラフの累計表示がおかしい

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#202]
## 起こっている問題 / The Problem
- 検査実施件数のグラフの累計表示がおかしくなってます。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/749758/78671400-35fb6580-791a-11ea-8519-3611ba2d673d.png)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. 本番環境のサイトを開く
2. 検査実施件数のグラフの「累計」を押す。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hajime-miyauchi** [comment]
最近の修正だとこれが関係してる？？

https://github.com/code4nagoya/covid19/pull/193

**Comment by amay077** [comment]
ちょっと調べてみますー

**Comment by hajime-miyauchi** [comment]
@amay077 
ありがとうございます！助かります！

**Comment by ctyo** [comment]
一つ一つ振り返ってましたが、こちらのコミットのタイミングで表示が崩れていましたー
お助けになればmm
https://github.com/code4nagoya/covid19/pull/193/commits/62f6d4044f0d376b582d13bef35a46e98313306f

**Comment by hajime-miyauchi** [comment]
そのタイミングということはdata.json側が壊れてる可能性も微レ存ですね。ちょっとdata.jsonも見てみます。

**Comment by amay077** [comment]
そうですね data.json で 数値に ``””`` が付いてるのが直接の原因ぽいですね。

![image](https://user-images.githubusercontent.com/401369/78674123-18c89600-791e-11ea-881a-0666796952d2.png)

**Comment by ctyo** [comment]
ロジックの側で雑データでも食えるように対応入れてみました
https://github.com/code4nagoya/covid19/pull/203

**Comment by amay077** [comment]
↑早速マージしました！

**Comment by ctyo** [comment]
devで様子をみて、よければmasterマージPRつくりますね

**Comment by hajime-miyauchi** [comment]
早い。お二人ともさすがです。
masterへの反映もお願いしますー。
Admin権限あるはずなので一人でマージも可能なはずですがダメそうだったら言ってくださいー。

**Comment by amay077** [comment]
こちら https://github.com/code4nagoya/covid19/pull/197 もマージしちゃいます。

**Comment by ctyo** [comment]
お得!

**Comment by ctyo** [comment]
よさげな動作に見えますね 🎉 
22:40に本番反映しますー(ビール開ける準備)

https://dev-covid19-aichi.netlify.com/

**Comment by amay077** [comment]
:beer: :clap:

**Comment by ctyo** [comment]
修正されましたね
対応ありがとうございましたーおつかれさまでしたー

クローズしますmm

**Comment by hajime-miyauchi** [comment]
data.jsonの生成もちゃんと数値型になるように修正のIssue立てておきますー

**Comment by ozo360** [comment]
紛らわしくてごめんなさい、こちらツール側は現在未対応です
（githubの使い方がよくわからないのでプルリクを取り下げました）

**Comment by amay077** [comment]
はい、 https://github.com/code4nagoya/covid19-aichi-tools/issues/10 で別 issue 化されてるので close で大丈夫です（ツール未対応でも表示側での対処はできたので）。
