### ISSUE TITLE
トップページの最終更新日時が正しくない

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#204]
## 起こっている問題 / The Problem
- トップページの最終更新に各グラフの更新日時よりも古い値が表示されている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/78734085-421b0d80-7982-11ea-999e-781f6d49ca85.png)

## 期待する見せ方・挙動 / Expected Behavior
- 文字通り「最終更新」に最終更新日時を表示する

## 起こっている問題の再現手段 / Steps to Reproduce
- 最終更新に表示している日時の取得方法にバグがあるのではないか
- 全てのデータの更新日時（lastUpdate）をチェックして最も新しい値を表示すべき
- 現在は検査陽性者の状況の更新日時（lastUpdate）だけを取得しているのではないか？

**Comment by amay077** [comment]
こちら https://github.com/code4nagoya/covid19/pull/211/files#diff-868ae2d65fb52e0bf680b28558a92a88R3534 の修正で気づかれたかも知れませんが、
最終更新日時は ``data.json`` の ``lastUpdate`` の値を表示しています。

ので、``data.json`` を手作業で修正された場合、あるいはツールで生成した場合は、``lastUpdate`` も更新をお願いしたいです。

> 現在は検査陽性者の状況の更新日時（lastUpdate）だけを取得しているのではないか

``lastUpdate``  は 検査陽性者の ではなく ``data.json`` の という位置付けになりますので、これでよいかな、と思います。

![image](https://user-images.githubusercontent.com/401369/78907171-5282d380-7abb-11ea-8c81-3b01a3d671da.png)

**Comment by ozo360** [comment]
なるほど！理解しました。
データの位置がmain_summaryの前だったので勘違いしましたが
確かにデータ構造的にご指摘の通りになっていますね。
ということはツール側で対処しなくてはいけないところということですね。
ツール側にissueを上げておきます。

**Comment by ozo360** [comment]
なるほど！理解しました。
データの位置がmain_summaryの前だったので勘違いしましたが
確かにデータ構造的にご指摘の通りになっていますね。
手動で編集した私のミスでした。
closeします。
