### ISSUE TITLE
検査実施数グラフで集計単位の異なるデータを視覚的に区別したい

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#209]
## 改善詳細 / Details of Improvement
- 集計単位の異なるデータを１つのグラフで表示しているため視覚的に区別できるよう改善したい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/78856004-6fd68400-7a60-11ea-811e-8abe53e16c6d.png)

## 期待する見せ方・挙動 / Expected behavior
- data.jsonの合算に「〇」の入ったデータは棒グラフの色を変えて欲しい

**Comment by amay077** [comment]
こんな感じでどうでしょう？

![image](https://user-images.githubusercontent.com/401369/78891130-e051c500-7aa1-11ea-9ff4-0141415a014d.png)

**Comment by ozo360** [comment]
素晴らしいと思います
