### ISSUE TITLE
愛知県の感染症発生状況に「施設入所」という項目が新たに増えている

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#216]
## 起こっている問題 / The Problem
- 「施設入所」の項目をグラフに追加する必要がある
- Google Spreadシートおよびcovid19-aichi-toolsにも変更が必要

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/749758/78959280-70851e00-7b25-11ea-8222-4612b6eca95b.png)
![image](https://user-images.githubusercontent.com/749758/78959318-8a266580-7b25-11ea-8d0a-5532720809c0.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「施設入所」の項目を追加

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
Google スプレッドシート main_summary の履歴シートには、項目を追記しておきました。
シート1 の方は追加するとツールへの影響が分からなかったので行っていません。

![](https://user-images.githubusercontent.com/401369/78988891-15771980-7b6d-11ea-95cf-2222be249e83.png)

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19/issues/220 の対応により、上の SpreadSheet が data.json に在る前提となりました。

data.json に下記データが作られています。
https://github.com/code4nagoya/covid19-aichi-tools/issues/21
https://github.com/code4nagoya/covid19/blob/development/data/data.json#L4465-L4728

本件は、こちらの最新日付(末端)のデータを参照する形にしたいと思います。
