### ISSUE TITLE
「検査陽性者の状況」グラフ出典リンク先相違

### ISSUE THREAD

**Issue by hmatsu47** [code4nagoya/covid19#224]
## 起こっている問題 / The Problem
- 「検査陽性者の状況」グラフの出典は「愛知県新型コロナウイルス感染症トップページ」のはずだが、他の3つのグラフと同じ「愛知県内の感染者・遺伝子検査件数」になってしまっている。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35142774/79062794-27c19680-7cd8-11ea-94bf-f88100460db1.png)
ここをクリックすると https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html へ飛ぶが、飛んだ先のページにはソースの情報は存在しない。

## 期待する見せ方・挙動 / Expected Behavior
- https://www.pref.aichi.jp/site/covid19-aichi/ へのリンクに変更する。
- 細かいことを言えば「出典: 愛知県新型コロナウイルス感染症対策サイト」という表記もリンク先ごとに変えるべきなのかもしれませんが、個人的にはそこは変えなくても良いと思います。

（以降省略）

**Comment by hmatsu47** [comment]
ここですかね？
https://github.com/code4nagoya/covid19/blob/development/pages/index.vue#L39

**Comment by mira-tech** [comment]
#158 で一旦全てのリンクを https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html にする内容の修正したんですよね... ループになりそう

**Comment by hajime-miyauchi** [comment]
@hmatsu47 さん
ありがとうございます！本件私もIssue立てなきゃなと思ってました。

@mira-tech さん
そのIssueではリンク先は @hmatsu47 さんのこのIssueの通り、 https://www.pref.aichi.jp/site/covid19-aichi/ に合わせる想定だったんですが、実際は https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html に合わせていました。

ので、ここで改めて https://www.pref.aichi.jp/site/covid19-aichi/ に合わせるで統一が良いと思います。

**Comment by hmatsu47** [comment]
@hajime-miyauchi さん
あ、ほかの 3 つのグラフ・表（陽性患者数・陽性患者の属性・検査実施件数）もトップページへのリンクで統一、のほうが良いですか？
愛知県のサイトが重くなることがあるので、ほかの 3 つは https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html のままでもいいかな？と思ったのですが（ソースの情報に到達するまで2回クリックしなくてもいいので）。

※正式にはトップページにリンクするのが筋かもしれませんが、↑に書いた事情で2クリック必要になると愛知県のサイトに余計な負荷を掛けることになりかねないな、と思いました。

**Comment by hajime-miyauchi** [comment]
@hmatsu47 さん
あ、たしかに統一する必要は無いですね。
仰る通り「検査陽性者の状況」のグラフの出典元のみトップページに変更(本Issueの提案通り)がベストだと思います！

**Comment by hmatsu47** [comment]
こちら、開発環境ができたので私自身で対応します。
