### ISSUE TITLE
グラフの表示期間を指定できるスライダーがあると良さそう

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#227]
## 改善詳細 / Details of Improvement
- https://stopcovid19.hokkaido.dev/ 参照
- 今後、期間が長くなっていくことが想定されるので、北海道版のようなグラフの開始・終了日をしていできるスライダーがあると便利だと思います
- 東京 https://stopcovid19.metro.tokyo.lg.jp/ では横スクロール可能になっていますが、ちょっと不便な感じがします

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/401369/79072043-dafeaf80-7d19-11ea-96e2-e905d64d07c1.png)

**Comment by daikiyamamuro** [comment]
### 北海道の場合
- デフォルト表示期間が全期間
- 最小表示期間は14日間

となっているが、デフォルトの表示期間を14日間にしたほうが良いかも。
さらに #243 で週次グラフへの切り替えが実現されれば、デフォルトは週次グラフが良さそう。
