### ISSUE TITLE
「入院中数」「重症者数」推移グラフの追加

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#234]
## 改善詳細 / Details of Improvement
- 「死亡者数を抑える」事が県全体の最大目標であり、陽性者数を減らし検査実施件数を増やすだけでは達成出来ません。医療関係者の努力が反映され、感染拡大が収束し0人になるまで管理する数値「入院中数」「重症者数」を指標とするのが良いと考えます。
- 北海道サイトでは「現在患者数」を先頭に表示しており同じ考え方です。愛知県サイトだと「検査陽性者の状況」の次に「入院中数」「重症者数」を表示するのが良いと考えます。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/79118221-3b4c2a80-7dc8-11ea-8628-00d1583d442c.png)

## 期待する見せ方・挙動 / Expected behavior
- 「入院中」「重症」の日次データを、北海道サイトの「現在患者数」と同じ見せ方・挙動の棒グラフ２つを表示する。
- 「日別」では増減を棒グラフに表示し、右上には最新の増減数を表示する。
→北海道サイトを参考にしたので「日別」を記載したが、必須ではなく、無くて良い。
- 「累計」はその日の値を棒グラフで表示し、右上には最新の値を表示する。
- 「累計」を初期表示する。

**Comment by hmatsu47** [comment]
ちょっと時間が掛かるかもしれませんが取り組んでみます。
