### ISSUE TITLE
GitHub ActionsのPatientsデータ取得先を変更

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#235]
## 改善詳細 / Details of Improvement
- GitHub ActionsのPatientsデータ取得先をGoogleDriveのpatients.csvに変更して欲しい。

何故なら、
Patientsスプレッドシートは更新量が大量で手動での更新が現実的ではないので
スクレイピングツール（scrape_patiant.py）の利用が必須になっている。
スクレイピングツールを使って生成されたpatients.csvをそのまま利用して欲しい。

GitHub Actionsにスクレイピングツールを含めることは
既知の[不具合](https://github.com/code4nagoya/covid19-aichi-tools/issues/2)が修正されてからがよい。

## 期待する見せ方・挙動 / Expected behavior
- データの取得先をpatients.csvから取得するように変更
wget "https://drive.google.com/uc?export=download&id=1BVwkwONO8hXlHJMa0u0f4K69W1eB7WUn" -O patients.csv

**Comment by amay077** [comment]
既に愛知県発表のPDFからスクレイピングにて CSV生成 → data.json まで動いているようなので、こちらは close させていただきます。

https://github.com/code4nagoya/covid19-aichi-tools/issues/2

は、そちらの issue にコメントしたとおり、次回再現したら追跡可能になりますので、しばらく様子を見ましょう。

P.S. つまり、Google Spreadseet の patients は、未使用となり更新不要になったと認識しています。
