### ISSUE TITLE
「陽性患者数」の(週次)推移グラフの追加

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#243]
## 改善詳細 / Details of Improvement

- 現在「陽性患者数」には、(日次)と(累積)が有ります。(日次)には曜日変動があり、増えるだけの(累積)では、推移が分かりにくいので(週次)を追加するのが良いと考えます。
- 長い戦いとなりつつあり、日々の変動で一喜一憂するのではなく、今週の値を前週と比較する事で管理されると考えます。他の感染症は週次で前年と比較して管理されています。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/79204521-a4d74200-7e77-11ea-88ec-d1c95bb94d31.png)

## 期待する見せ方・挙動 / Expected behavior

- 「陽性患者数」(日次)の構成数値を、週(月〜日)で集計して、推移棒グラフを表示する。
- 週の半ばでも日次で更新する。つまり今週の数値は月～土曜まで7日分に満たないが表示する。
- 「陽性患者数」に(週次)を追加し、切り替えられるようにする。
- 右上には今週の値、前週比を表示する。
- カーソルをおいた際、「その週の月曜日付＆”週”」「その週の陽性患者数」を表示する。
- 初期表示は(日次)のままとする。今後、様子を見て(週次)への切り替えを検討する。

**Comment by amay077** [comment]
週次のデータ集計は、まずはフロントエンド側でやってしまって良いと思います（現状それほど負荷はかからないですし、長期化によるデータ増大の問題は別 issue で検討し、その際にフロントエンドで行っている集計化をバッチ可＜定期処理＞で行うようにしたいと考えています。）。

週次化されたデータは現状の ``data.json`` にはないですね（強いて言えば inspection_summary の過去データが愛知県の発表により週次化されている程度です）。
