### ISSUE TITLE
faviconを愛知県章からオリジナルアイコンに変更する

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#25]
## 起こっている問題 / The Problem
- faviconが愛知県章のままになってる？オリジナルアイコンに変更する

**Comment by ctyo** [comment]
ドメイン変えたら治ったみたいです
<img width="267" alt="スクリーンショット 2020-03-10 23 42 05" src="https://user-images.githubusercontent.com/1971086/76323994-c600bc00-6328-11ea-889a-659b3f44bc50.png">

**Comment by ctyo** [comment]
忘れてたので更新までしておきました　
https://github.com/code4nagoya/covid19/pull/28/files

**Comment by fussy113** [comment]
@ctyo ありがとうございます！closeします
