### ISSUE TITLE
「検査陽性者の状況」に注記と時点情報を記載する

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#254]
## 起こっている問題 / The Problem
4/12から、愛知県の検査陽性者の報告対象が2点変更されました。
1. 中国人渡航者を除く
2. 再感染は、含めない

これまでの報告対象から3人外れています。

愛知県公式の「検査陽性者の状況」の最下部には添付画像の記載が追記されています。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/79344306-9ddd2c00-7f6a-11ea-9e1b-e1a52edd2f5d.png)

## 期待する見せ方・挙動 / Expected Behavior
こちらも「検査陽性者の状況」の下部に、同様の注記を入れるのが良いと考えます。

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19/issues/216 で、データの参照先を ``data.json`` の ``main_summary_history`` の最新に変更して頂きました。

そこには、上記内容を備考として入れてあります（元は愛知県画像の ※ を Google Spreadseet に転記しています）。

https://github.com/code4nagoya/covid19/blob/807fd6b059541846d231e0ec42ad64d1fef487db/data/data.json#L4744

なので、「検査陽性者の状況」に、``data.json`` - ``main_summary_history`` の最新 - 備考 を表示するのがよいと考えます。

もう一つ「ついで」ですが、データの時点情報が https://github.com/code4nagoya/covid19/blob/807fd6b059541846d231e0ec42ad64d1fef487db/data/data.json#L4734 に「更新日時」として在りますので、これも表示させたいです。

![image](https://user-images.githubusercontent.com/401369/79355485-ae949e80-7f78-11ea-9333-2da7495e37c1.png)

**Comment by hmatsu47** [comment]
手を付けてみました。
