### ISSUE TITLE
「愛知県新型コロナウイルス感染症対策本部会議報」がリンク切れ

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#261]
## 起こっている問題 / The Problem
- 「愛知県新型コロナウイルス感染症対策本部会議報」がリンク切れ

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/401369/79410577-ccdfb600-7fdb-11ea-98a7-ea58f5373823.png)

## 期待する見せ方・挙動 / Expected Behavior
- 移動後のリンク先が見つかればそちらに修正、見つからなければこの項目を削除しちゃって良いと思います。

**Comment by hmatsu47** [comment]
元がどんなページだったのか見ていないのですが、こちらですかね？
https://www.pref.aichi.jp/site/covid19-aichi/novel-coronavirus-taisakuhonbu.html

リンク切れのURLとは途中のパスが違うみたいですね。

**Comment by hmatsu47** [comment]
合っていればさっさと対応してしまいますが、ご存知の方教えてください！

**Comment by amay077** [comment]
たぶん合ってるので、お願いします！

**Comment by hmatsu47** [comment]
では対応します！
