### ISSUE TITLE
全国に緊急事態宣言が発出されたのでトップの文言を何か変える

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#267]
## 改善詳細 / Details of Improvement
- [全国に緊急事態宣言が発出された](https://www3.nhk.or.jp/news/html/20200416/k10012391681000.html) のでトップページの文言を何か変える

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/79451601-c116e280-8021-11ea-8645-339aba6ae4d2.png)

## 期待する見せ方・挙動 / Expected behavior
- 愛知県緊急事態宣言の上行に「全国に緊急事態宣言が発出されました」的な文言でよいかと。
- リンク先は 政府 かどこかの1次ソースへ

**Comment by amay077** [comment]
愛知県は [「特定警戒都道府県」](https://news.livedoor.com/article/detail/18131268/) にも指定されてようなので、それも文言に含められれば。

**Comment by hmatsu47** [comment]
「一次ソース探し」が結構大変なのですが、こちらで良いですかね？
https://corona.go.jp/

（このサイトでは「特定警戒都道府県」が目立たないのがネック…一応そんな趣旨のことが「基本的対処方針」の中で触れられていますが。）

表現は
「緊急事態宣言の対象区域が全国に拡大されました。愛知県は「特定警戒都道府県」 に指定されました」
あたり？
（あまり長くなりすぎないように、「国の」「政府の」「…特別措置法の」などの文言は省略。）

**Comment by amay077** [comment]
よいと思います。
そのサイト知りませんでした、ありがとうございます。

**Comment by hmatsu47** [comment]
明日、じゃなくて今日はもう遅いのと午前中微妙に「不要不急」外の用事があるので（こんなタイミングで歯の詰め物が取れた…）、午後まで残ってたら対応します。

**Comment by amay077** [comment]
はいー、お手すきの時間でお願いしますー。
