### ISSUE TITLE
「当サイトについて」から「データについて」を非表示に

### ISSUE THREAD

**Issue by 1coin178** [code4nagoya/covid19#27]
## 起こっている問題 / The Problem
- 今東京のリンクになっているので、愛知版がオープンデータと公開されるまで非表示にする
   -  https://stopcovid19.hokkaido.dev/about も表示していない

## スクリーンショット / Screenshot

<img width="1515" alt="貼り付けた画像_2020_03_10_23_35" src="https://user-images.githubusercontent.com/9292002/76323248-cf3d5900-6327-11ea-9fb1-6ad99e7eeba2.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mziyut** [comment]
こちら やりますね

**Comment by hajime-miyauchi** [comment]
助かります！
