### ISSUE TITLE
「市町村別感染状況」のカラム地図の追加

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#287]
## 改善詳細 / Details of Improvement

- 県全体ではなく、自分や親族、友人の住む市町村の状況を把握する為に、市町村別の情報掲載が必要と考えます。
- ダッシュボード向けの「カラム地図」での掲載が適当と考えます。#270
- 塗り分けは、感染者数で行うと人口が多い名古屋市が目立つだけなので、感染率(10万人あたりの感染者数)で塗り分ける必要があると考えます。感染率の意味を理解していただく必要はあるが、感染拡大してくると感染者数だけでは状況判断がしにくくなります。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/79681603-83e76600-8256-11ea-8aa8-869e4444eb51.png)

## 期待する見せ方・挙動 / Expected behavior
- 市町村マスタを設け、54市町村のみの、[市町村名]、[市町村名短] (うしろの1文字を削除)、[人口]を保持する。[市町村コード]を保持してキーにしても良い。
- 人口は、推計人口(2020年3月1日時点)を利用する。
　( https://www.pref.aichi.jp/soshiki/toukei/jinko1new.html )
- 「陽性患者の属性」で掲載しているデータが更新される毎に、"居住地"毎にカウントし感染者数を算出する。0件の場合でも算出結果データにレコード生成しても良い。
- "居住地"が、54市町村以外の場合(尾張地方、三河地方、一宮保健所管内など)や、県外は対象外とする。つまり、市町村マスタに無い"居住地"は算出対象外とする。
- "居住地"毎に、以下の通り、感染率を算出する。
　感染率 ＝ （ 感染者数 ÷ 人口 ) × 100,000
- 「カラム地図」の市町村の配置は、スクリーンショットの通りとする。
- カラム内の表示は上から、以下の通りである。[市町村名短]を用いるので、前述の算出結果データにも[市町村名短]を保持しても良い。
　[市町村名短]
　[感染者数]
　[感染率]
- 感染率により、カラム全体の背景色・文字色を塗り分ける。[塗り分け種類]を算出し、前述の算出結果データに保持しても良い。
　感染率：背景色：文字色
　0人：#FFFFFF：黒
　128人以上：#04209D：白
　32人以上：#47710B2：白
　8人以上：#73A20C6：白
　2人以上：#8ABC0CF：黒
　2人未満：#C5ED0DF：黒

**Comment by amay077** [comment]
FYI: 大阪府版で挙がっている類似の issue
https://github.com/codeforosaka/covid19/issues/281

**Comment by amay077** [comment]
こちら着手してます。
今はこんな感じで、カラム地図と情報は表示されるようになりました。

![image](https://user-images.githubusercontent.com/401369/80285375-70109800-875f-11ea-9472-3521e80a9e5c.png)

塗り分け色は、このサイトのテーマカラーの赤系のグラデーションにしようと思います。
また、

>　感染率：背景色：文字色
>　128人以上：#04209D：白
>　32人以上：#47710B2：白
>　8人以上：#73A20C6：白
>　2人以上：#8ABC0CF：黒
>　2人未満：#C5ED0DF：黒

は、塗り分け数のみを指定して、データから自動算出させたいので、
塗り分け数が 5 ならば、

1. 10万人あたり感染者数を算出
2. 感染者数0人の市町村を除く
3. 2 を、10万人あたり感染者数の降順で並び替え
4. 3 のリストを 5等分して、それぞれに塗り分け色を適用

としたいと思います。

**Comment by takainou** [comment]
ありがとうございます。良い感じです。

色は、以下の記事などを読んだ結果、意識的に青系にしてます。他のグラフ部分との配色バランスもありますので、指定色以外でも構いませんが、赤系はやはり避けた方が良いと考えます。

『階級区分図で使用する色を赤系から青系に変えた理由について、「人々は赤い地図が好きです。そして、赤色は人の目を引きます。しかし、データセットを考慮してください。我々は今後さらに悪化する可能性のある悲劇そのものをマッピングしています。真っ赤なマップを見て悲鳴を上げたいですか？依然として統計的に見れば新型コロナウイルスによる『死』は極めてまれなものですが、赤色はそれを暗示してしまいます」として、扱う題材によって配色にも気を配るべきと主張しています。』

https://gigazine.net/news/20200228-mapping-coronavirus/

あと、自動配色算出ですが、例えば、自分の市町村の感染率が変化していないが、他の市町村が悪化した事で相対的に良くなり、色が変わりませんか。その結果、前見た時から、自分の市町村の色が変わっており、自分の市町村に変化があったと勘違いしませんか。感染率が変わっていないのであれば、色は変わらない方が良いと考えます。

**Comment by amay077** [comment]
### 色について

赤系を避けた方がよいとの主張、理解しました。
「ならばサイト自体のテーマカラーも再考したほうが？」につながるかも知れませんが、
ひとまずこのカラム地図では、冒頭で提示いただいている配色を使います。
公開してみて不自然であるという意見が出れば、再検討しましょう。

### 塗り分け条件値について

> 例えば、自分の市町村の感染率が変化していないが、他の市町村が悪化した事で相対的に良くなり、色が変わりませんか。その結果、前見た時から、自分の市町村の色が変わっており、自分の市町村に変化があったと勘違いしませんか

勘違いが発生するかはわかりませんが、自分の市町村の感染率の絶対値による色付けではなくなる（他市町村との相対的な順位で色が変化する）のは確かです。

絶対値での塗り分けを大事にされたい意見は理解しましたので、そのようにします。
懸念もおっしゃる通りで、色塗り条件をたびたび見直す必要が生じます。

その際、色塗り条件（次の段階）が増えることは、画面のレイアウトなども考慮しなければならないため面倒が生じます。
塗り分け項目数６(感染者０も含む)を維持して、境界値を変える方が簡単ですが、それは前述と同じく「自分の市町村の色が意図されず変わる」ことになるので、どちらか（項目数を増やすか境界値を変えるか）を選択する必要があります。

**Comment by amay077** [comment]
ということで、ほぼ完成 版のスクリーンショットです。コード調整後 PR 投げます。
（データが少々古いので最新の状況とは異なります）

### PC版

![image](https://user-images.githubusercontent.com/401369/80367745-956be600-88c6-11ea-8b36-423b8b6edec0.png)

### モバイル版

モバイル版の方は、横幅が狭く文字サイズを小さくし過ぎるわけにもいかないので、４文字の「北名古屋」は見切れてしまいますが、識別はできるので折返して縦に長くなるよりはよいかなと思っています。

![image](https://user-images.githubusercontent.com/401369/80367864-c2b89400-88c6-11ea-8299-f58bc98236e2.png)

**Comment by takainou** [comment]
ありがとうございます。素晴らしいです！！！！

色と塗り分け条件は検討いただきありがとうございます。
テーマカラーは感染拡大して赤が濃くなっていく訳ではないので、良いかなと思ってます。
塗り分け条件は、それ以上感染拡大して行かない事を祈願しましょう。

データは4/17時点ですかね。手元にあるものと突き合わせてみました。
感染者数はピタリ合致、感染率は小数点以下で0.1ずれている箇所がありました。
例えば、「刈谷：153,252 | 1 | 0.653」小数点以下第二位を四捨五入すると感染率は「0.7」になりませんか？細かい点ですが、確認頂ければと思います。

![image](https://user-images.githubusercontent.com/63571899/80369341-15934b00-88c9-11ea-9a1f-8055d1daabb4.png)
