### ISSUE TITLE
知事からのメッセージを差し替えもしくは削除

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#29]
## 起こっている問題 / The Problem
- 「知事からのメッセージ」のリンク先がコロナと関係ないので削除もしくは、コロナに関係するページを探して差し替え
![スクリーンショット 2020-03-10 23 56 10](https://user-images.githubusercontent.com/749758/76325583-d6b23180-632a-11ea-85ae-3b458d52f20e.png)
![スクリーンショット 2020-03-10 23 56 18](https://user-images.githubusercontent.com/749758/76325585-d7e35e80-632a-11ea-9adc-adb343996f4c.png)

**Comment by fussy113** [comment]
### 提案

変更するとしたらこのページになりそうです

https://www.pref.aichi.jp/chiji/message/index00.html
