### ISSUE TITLE
「最新のお知らせ」を愛知県のお知らせに変更

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#31]
## 起こっている問題 / The Problem
- 「最新のお知らせ」が東京都のままなので愛知県の最新情報に差し替えもしくは一旦削除
- できればここ自動更新できると良いが、それはまた別のIssue登録したほうがよさそう

**Comment by isy** [comment]
こちらやります！

愛知県の最新情報として以下のものからコロナ関連のものを抜粋する形で良いでしょうか？
https://www.pref.aichi.jp/soshiki/list1-1.html

**Comment by amay077** [comment]
感染者が判明している市町村からも抽出すると良いと思います（自動化は置いておいて）。

名古屋市
http://www.city.nagoya.jp/kenkofukushi/page/0000124556.html

半田市
https://www.city.handa.lg.jp/kinkyu/index.html

蒲郡市
https://www.city.gamagori.lg.jp/

**Comment by amay077** [comment]
あ、岡崎市もですね。

岡崎市
https://www.city.okazaki.lg.jp/

**Comment by isy** [comment]
本家の方のコミット履歴みたら2件で絞っているようなので一旦愛知県からの情報のみ２件載せますね

[FYI]
お知らせページを作るissueも上がっているようです
https://github.com/tokyo-metropolitan-gov/covid19/issues/1082

**Comment by hajime-miyauchi** [comment]
あ、ごめんなさい、コメント見てなくてとりあえず本サイトオープンしましたっていうのに差し替えてマージしちゃいましたが、愛知県からの情報載せるで進めてください！
