### ISSUE TITLE
各パネルの「出典」の表示位置を下寄せにする

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#315]
## 改善詳細 / Details of Improvement
- 検査陽性者の状況
- 陽性患者数
- 検査陽性者状況の推移

のパネルは、「出典：」の下に余白があるので、これを取りたい。
「入院中数」「重症者数」などは OK。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/80107851-9515d700-85b6-11ea-9f4a-14af27f9d11f.png)

## 期待する見せ方・挙動 / Expected behavior

「入院中数」「重症者数」などのように「出典：」の位置を下寄せにする。

**Comment by hmatsu47** [comment]
対応します。
