### ISSUE TITLE
PCR検査の場所について

### ISSUE THREAD

**Issue by yukou-isshiki** [code4nagoya/covid19#32]
## 起こっている問題 / The Problem
- 東京都の情報のままなので変える必要があるが、愛知県でそこに相当する場所が不明
## スクリーンショット / Screenshot
![スクリーンショット 2020-03-11 0 27 03](https://user-images.githubusercontent.com/22832130/76328899-38749a80-632f-11ea-826f-3b58cfd44680.png)

**Comment by hajime-miyauchi** [comment]
本当ですね。

残念ですが最短公開に向けてはこのページ自体を、一旦削除してしまったほうが良いかもしれませんね。

https://dev-covid19-aichi.netlify.com/flow

そしたら関連するIssueのこちらもCloseできるし
https://github.com/code4nagoya/covid19/issues/34

**Comment by mziyut** [comment]
こちらではないでしょうか?

> 愛知県衛生研究所
https://www.pref.aichi.jp/eiseiken/

**Comment by hajime-miyauchi** [comment]
確かに愛知県衛生研究所で遺伝子検査を実施はしているようですね。

https://www.pref.aichi.jp/soshiki/kenkotaisaku/pressrelease-ncov200310.html

ただ東京都の下記サイトのように明確に記載されているサイトは見つけられませんでした。

https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html

愛知県のサイトで上記のような記載があれば同じ内容を載せるということで一旦削除の方向ですかねぇ。

このフロー自体が東京都のフローであって、愛知県が同様のフローであるかも含め確認したほうが良い気がしますね。

**Comment by hajime-miyauchi** [comment]
北海道でも検討した結果、現時点ではこのコンテンツは落としてますね。

https://github.com/codeforsapporo/covid19/issues/30

**Comment by hajime-miyauchi** [comment]
ページ自体を削除したので一旦Close
