### ISSUE TITLE
「陽性患者数」「検査実施件数」(週別)の集計を月～日とする

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#323]
## 起こっている問題 / The Problem
「陽性患者数」「検査実施件数」の(週別)にて
- 週の集計(サマリ)が 月～日 となっていない。
- 目盛の日付表示が月曜日では無い。

## 期待する見せ方・挙動 / Expected Behavior
愛知県の週のサマり方が 月～日 なので、それに 月～日 とする。
目盛の日付表示も月曜日(3/30,4/6,13,20)とする。

**Comment by amay077** [comment]
![image](https://user-images.githubusercontent.com/401369/80195271-8c74dd80-8656-11ea-8b50-b5fa2d3927d2.png)

X軸の目盛り表示は 東京版 - https://stopcovid19.metro.tokyo.lg.jp/ のように「4/6～4/12」にできると更に良いです。

**Comment by daikiyamamuro** [comment]
週のサマリかたなんですけど、月～日になっていると思います。

![6_12](https://user-images.githubusercontent.com/16362469/80280139-2f078c00-873d-11ea-83ff-176ebdf71f4e.png)
![13_19](https://user-images.githubusercontent.com/16362469/80280143-3169e600-873d-11ea-998f-b8b5f93fa38c.png)
![weekly](https://user-images.githubusercontent.com/16362469/80280145-35960380-873d-11ea-83ee-f869848b97b1.png)

----



また、週サマリの日付は、月～日で週を考えた場合の末日→日曜日の日付にしました。
ちなみにこれは従来からあった『検査実施件数』の表示方法に準じています。

![2020-04-25_21h41_37](https://user-images.githubusercontent.com/16362469/80280266-f3b98d00-873d-11ea-9b6a-85b8a297e0cf.png)

![2020-04-25_21h41_51](https://user-images.githubusercontent.com/16362469/80280272-fe742200-873d-11ea-8f76-d36681325890.png)




----



以上のことから、基本的には従来のサマリかたを踏襲し、値は間違っていないと思います。
実装している最中に違和感があったのは、週の末日（日曜日）を軸の値にするのは見る人の感覚に依存するなとは思っていました。
（自分なら開始日の月曜を軸の値にして4/6週みたいするかもなぁって感覚です。）
（とはいえ、これまでに議論されて決定された事項かもしれないので、現行踏襲で実装しました。）

ですので、問題の本質としては ****軸の値の表示方法がわかりづらい**** ことであり、取り組むべき課題としては ****軸の表示方法を改善する**** ことだと思います。（ @amay077 さんのご提案のイメージのような感じです）

**Comment by takainou** [comment]
大変失礼いたしました。再確認しサマリ方は間違っていませんでした。私の手元とは、中国人渡航者と再感染がズレている(これは別問題)だけで、ピッタリです。大変申し訳ありません。

![image](https://user-images.githubusercontent.com/63571899/80281458-4303bb80-8746-11ea-9699-4fd183f97895.png)

「検査実施件数」が週の末日（日曜日）としている背景を知らないので、確認いただくとして、
＞（自分なら開始日の月曜を軸の値にして4/6週みたいするかもなぁって感覚です。）
に賛同します。

あとは、 #327 で処理されるとして、こちらはCloseで良いのではないでしょうか。

**Comment by amay077** [comment]
確認ありがとうございます。
ではこちらは close しますね。
