### ISSUE TITLE
陽性患者数のデフォルト表示が週別となっているのは現状では勘違いしてしまう

### ISSUE THREAD

**Issue by keita99** [code4nagoya/covid19#327]
## 改善詳細 / Details of Improvement
陽性患者数の初期表示が週別になってるのは、ぱっと見ると人数が多く見えて現状では勘違いしやすい。

## 期待する見せ方・挙動 / Expected behavior
＞＞初期表示は(日次)のままとする。今後、様子を見て(週次)への切り替えを検討する。
このような運用方針が良いかと思います。

## 動作環境・ブラウザ / Environment
-  Windows 
-  Edge

**Comment by amay077** [comment]
> 様子を見て(週次)への切り替えを検討する

それも良いかと思いますが、その時に週別グラフについて、何らかの差別化が図れていないと同じく勘違いされる人は多いかと思います。

そこで週別グラフの差別化を検討したく思います。
例えば、

### 1. X軸のラベルに 「4/5～4/11」のように範囲を示す

東京都のサイトでは一部そのようになっています。

![image](https://user-images.githubusercontent.com/401369/80276844-2d7e9980-8726-11ea-9d1f-4dd48c5b9956.png)

### 2. 週次の棒は色を変える

検査実施件数 のグラフは愛知県発表の過去データが週次で合算されており、週次と日次が交じっていたため色で差別化しました。

![image](https://user-images.githubusercontent.com/401369/80276891-759dbc00-8726-11ea-8d26-12a6a351f38e.png)

### 3. グラフタイトルや最新値の表記で週別であることを強調する

- 陽性患者数 → 陽性患者数(週別)
- 4/23 実績値（前週比：-7 人） →  4/23～4/25 実績値（前週比：-7 人）

などと表記を変えることで差別化が図れるのでは無いかと思います。

![image](https://user-images.githubusercontent.com/401369/80276984-fb216c00-8726-11ea-9c96-f5c62b39cb45.png)


皆さまからのご意見を募集します。

**Comment by hmatsu47** [comment]
わたしの感覚では、サイトのどこかに「なぜこのような見せ方をしているのか」の説明を用意して、リンククリックでポップアップするなり別タブで表示するなりしたほうが良いと思います（グラフ等の並び順の理由とともに）。

おそらく、マスコミの報道を中心に見ている人にとっては「分かりづらい。不便だな」で終わってしまうと思いますので。

**Comment by keita99** [comment]
1. X軸のラベルに 「4/5～4/11」のように範囲を示す
3. グラフタイトルや最新値の表記で週別であることを強調する
       4/23 実績値（前週比：-7 人） → 4/23～4/25 実績値（前週比：-7 人）
この2点の対応は見分けやすくなって良いと思います。

2. 週次の棒は色を変える
こちらは意図がわかりにくいかと。

**Comment by amay077** [comment]
では、さしあたり

> 1. X軸のラベルに 「4/5～4/11」のように範囲を示す
> 
> 2. グラフタイトルや最新値の表記で週別であることを強調する
> 4/23 実績値（前週比：-7 人） → 4/23～4/25 実績値（前週比：-7 人）
> この2点の対応は見分けやすくなって良いと思います。

の対策を行いましょう。
これらは新たに issue 化した後、本 issue は close したいと思います。

https://github.com/code4nagoya/covid19/issues/327#issuecomment-619370426 の内容は、各グラフの配置も含めた、全体的な話になるかと思いますので、別 issue あるいは Slack などで議論しましょう（既に親しい議論もありますね）。

**Comment by amay077** [comment]
#352 に修正用 issue を起票したので、こちらは close しますね。
ありがとうございました。
