### ISSUE TITLE
福祉保健局のリンク先が東京都の福祉保健局になっている

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#34]
## 起こっている問題 / The Problem
-  「新型コロナウイルス感染症が心配なときに」の「福祉保健局HPへ」のリンク先が東京都の福祉保健局になっている。
- 「新型コロナウイルス感染症について」にリンクして「一般相談窓口の電話番号は健康対策課HPへ」とするのが良さそう。
https://www.pref.aichi.jp//soshiki/kenkotaisaku/novel-coronavirus.html
![スクリーンショット 2020-03-11 1 19 33](https://user-images.githubusercontent.com/749758/76334428-64474e80-6336-11ea-9ab6-94771740b790.png)

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19/pull/42 で削除したので一旦 close でよろしいかと思います。
