### ISSUE TITLE
名古屋市のコロナ対策特設サイトへのリンク追加

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#340]
## 改善詳細 / Details of Improvement
- 名古屋市のコロナ対策特設サイトが公開されたのでリンクを貼りたい。
- 愛知県の政令指定都市である名古屋市の特設サイトが公開されたため、リンクは有用と考える。
- リンク先: https://nagoyabousai.maps.arcgis.com/apps/Cascade/index.html?appid=04c0250edfe54ae4af7f1c8755d275b5

## スクリーンショット / Screenshot
![県内の最新感染動向 | 愛知県 新型コロナウイルス感染症対策サイト 2020-04-27 20-36-54](https://user-images.githubusercontent.com/749758/80368018-06130280-88c7-11ea-82e7-e0dc7ccbe396.png)

## 期待する見せ方・挙動 / Expected behavior
- 位置的には愛知県庁公式Twitterの下に新しく罫線を作って、その下くらいが良さそう。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hmatsu47** [comment]
（たまたま開発環境を立ち上げっぱなしにしていたので）対応します。
