### ISSUE TITLE
「陽性患者数の属性」は必要？

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#344]
## 改善詳細 / Details of Improvement
- すべての感染者の情報を、この小さなパネルで見たいだろうか？
- このパネルは(感染者数が増えるほど)処理コストが高く、低スペックな端末（特にモバイル）では処理が非常に重くなる
    - 他所(東京)の事例1: https://github.com/tokyo-metropolitan-gov/covid19/issues/3267
    - 他所(北海道)の事例2: https://github.com/codeforsapporo/covid19/issues/403

ちなみに東京版がモバイルで重いことを調査した際、その原因は、「3000件超の感染者一覧を表にレンダリングすること」でした。「data.json に 3000件超 のデータがあること」は原因ではありませんでした。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/401369/80380700-e2f24e00-88da-11ea-9b47-567f947e1b1a.png)

## 期待する見せ方・挙動 / Expected behavior

以下、思いつくままにアイデアを書きます

- モバイルでのユーザービリティを下げてまで、このパネルを表示する必要はないのではないか？
  - ユーザービリティが下がらない方法があれば、表示してもよい
    - 全件表示したまま、パフォーマンスを上げる（たぶん難しい）
      - 東京版は遅延ローディングを導入した模様ですが、文字通り読み込みを「遅延」するだけで根本解決にはなっていません
      - 使用している ``v-data-table`` がよろしくないのでは？
    - 一部のみ表示にすることで、パフォーマンスを上げる
      - 直近ｎ件のみ
      - ページング導入
      - 無限スクロール（最下部までスクロールすると追加読み込みするやつ）
    - パネルには「直近ｎ件」を表示し、以降は「別の一覧画面」に遷移する
  - ユーザービリティはどうしても下がるので、表示しない
    - 長期戦になりデータはどうしても増えるので、パフォーマンスの担保は難しい
    - ``data\patients.csv`` のダウンロードリンクをグラフ（陽性患者数）のパネルにつければよいのではないか

**Comment by takainou** [comment]
data\patients.csv のダウンロードリンクをグラフ（陽性患者数）のパネルにつければよいのではないか

で、充分と考えます。カラム地図も出来ますし。

**Comment by hmatsu47** [comment]
たぶんプロジェクトに関わっている人の中ではわたしが一番よく見ているほうだと思うのですが（笑）。

東京を見ていてすごく遅くなったと感じていましたし、カラム地図と、CSVダウンロードまたは愛知県のサイトへの誘導で事足りるので無くてもいいのではないかと思います。

**Comment by amay077** [comment]
> data\patients.csv のダウンロードリンク

ですが、GitHub のファイル(↓)に飛ばしちゃってもよいかもですね。

https://github.com/code4nagoya/covid19/blob/development/data/patients.csv

GitHub では CSV を表で表示してくれるし、「Raw」ボタンで CSV ファイル自体にもアクセスできます。

**Comment by amay077** [comment]
北海道版では、

> * 一部のみ表示にすることで、パフォーマンスを上げる
>   * 直近ｎ件のみ
>     * ページング導入

により [解決した](https://github.com/codeforsapporo/covid19/pull/426) ようです。現在、北海道版のサイトでパフォーマンスの不満はありません。ページングを [東京版に適用する PR](https://github.com/tokyo-metropolitan-gov/covid19/pull/3868) も送られており、これはこれで素晴らしいことだと思います。

愛知県版にもページングを導入する手段もあるのですが、私としては冒頭の

* すべての感染者の情報を、この小さなパネルで見たいだろうか？

に疑問を感じており、他の方も概ね同じ意見であるようですので、前述の、
「GitHub の CSV ページにリンクを貼る」
でよいかなと考えています。

**Comment by takainou** [comment]
賛同します。そこまでしても見たい人はcsvで見ますよね。

**Comment by amay077** [comment]
概ね合意が取れたものとして、実装用 issue として #405 を立てました。
こちらは close します。
