### ISSUE TITLE
神奈川県ページリンク差し替え

### ISSUE THREAD

**Issue by yukou-isshiki** [code4nagoya/covid19#36]
## 起こっている問題 / The Problem
- 神奈川県は同じソースで公式ページを立ち上げたので、リンク差し替えの必要あり
https://www.pref.kanagawa.jp/osirase/1369/

## スクリーンショット / Screenshot
<img width="1179" alt="スクリーンショット 2020-03-11 9 40 26" src="https://user-images.githubusercontent.com/22832130/76371105-9085be00-637c-11ea-9474-7c9bc7164b8c.png">

**Comment by hajime-miyauchi** [comment]
現状、並行運用になる可能性もあるので、差し替えではなくて追加のほうが良いかもしれませんね。

- 現状の「神奈川県」の表記を「神奈川県(Open Kawasaki/Code for Kawasaki版)」に変更
- 「神奈川県(神奈川県公式)」を追加

表記については「野良版」と自称されているので野良版でもよいかもしれません。

https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view

**Comment by yukou-isshiki** [comment]
とりあえず、併記という方向で進めます。状況が変化した場合にはその時に対応します。

**Comment by yukou-isshiki** [comment]
閉鎖されたようなので、やはり差し替える形にします
