### ISSUE TITLE
「検査実施件数」(日別)から週合算値の表示削除と(累計)廃止

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#360]
## 改善詳細 / Details of Improvement
- 愛知県提供データの形式に従い、「検査実施件数」(日別)では、直近分は日別、過去分は週合算値を掲載している
- 同じグラフ内に、日と週のデータが混在し、棒グラフの色を変えるなど工夫をして来た
- (累計)も、日と週のデータが混在し、推移が正しく読みとれないグラフとなっていた
- (週別)追加に伴い、(日別)に週合算値を掲載する理由は無くなったと考え、(日別)から週合算値の表示を削除するのが良いと考える
- (累計)は、日と週混在は推移が正しく読みとれず、直近の日だけの累計では価値が無く、推移は(週別)で確認できるので、廃止して良いと考える
- ただし、全累計が表示される場所が無くなるので、注記部分に掲載する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/80607466-7d37ca80-8a70-11ea-84ef-5de73bdf5cd3.png)

## 期待する見せ方・挙動 / Expected behavior
- (日別)直近の日別データのみ掲載する、週合算値は掲載しない
　日別データが公表されている期間しか表示されていない旨、注記を記載する
- (週別)今まで通り、直近の日別データを週サマリし、過去分の週合算値と一緒に掲載する
　棒グラフの色(日：赤、週：青)は、１色(全部：赤)で問題ないと考える
　(週別)をデフォルト表示とし、デフォルト表示期間は60週とする
- (累計)廃止する
　週別に掲載するデータを合算し、「検査件数 累計：xx,xxx件」と注記に掲載する

なお、 #352 にて、X軸ラベルに日付の範囲を表示する予定だが、「検査実施件数」(日別)の週合算部分への改修は削除予定につき、対応不要である

**Comment by amay077** [comment]
> (日別)直近の日別データのみ掲載する、週合算値は掲載しない

同意します。

> (週別)今まで通り、直近の日別データを週サマリし、過去分の週合算値と一緒に掲載する

同意します。

> (累計)廃止する
>　週別に掲載するデータを合算し、「検査件数 累計：xx,xxx件」と注記に掲載する

これは、累計は維持した方が良いと思います。
理由は、「累計表示の統一性」です。
他のグラフでも、「[日別|累計]で累計が選択された時、その右端に累計値が表示される」で共通な UX になっているので、それを維持した方が良いかと思います。

**Comment by takainou** [comment]
まず、最初に、誤っていた個所から修正します。
現在、「～3/1」で表示している検査件数は、週ではなく、「1/30～3/1」の合算した検査件数でした。
よって、この部分は(週次)にも掲載しないのが良いと考えます。

(累計)は廃止せず、以下の改修案どちらかではどうでしょうか？
2.だと厳密には共通なUXでは無くなってしまいますが。
1. 直近の日別データの部分のみ、累計表示する
　「1/30～3/1」「週別データ」の全合算値を直前に表示し累計開始する
2. 週別累計で表示する
　「1/30～3/1」から累計開始する 

![image](https://user-images.githubusercontent.com/63571899/81079702-d600da80-8f2a-11ea-81b0-3d6753ec6572.png)

**Comment by amay077** [comment]
> 現在、「～3/1」で表示している検査件数は、週ではなく、「1/30～3/1」の合算した検査件数でした。
> よって、この部分は(週次)にも掲載しないのが良いと考えます。

同意です。


>1. 直近の日別データの部分のみ、累計表示する
> 　「1/30～3/1」「週別データ」の全合算値を直前に表示し累計開始する

が、自然なように感じますね。累計は現在のところ日別のみですから、日別グラフとの期間とも合致しますし。「累計x週別」のニーズが全体的に発生した場合には、それを追加すれば自然です。


先日のオンラインミーティングでも話題になったとおり、日にちの経過と共に「県の発表データが月次に合算される」可能性も高いと思いますので、柔軟に対応できるようにしておきたいですね（ [日別｜週別｜累計] それぞれのグラフの表示限界日付を設定ファイルに持っておく、など）。

**Comment by amay077** [comment]
ここまでの内容をまとめると、修正内容は以下の通りです。

* (日別)直近の日別データのみ掲載する、週合算値は掲載しない
    * 日別データが公表されている期間しか表示されていない旨、注記を記載する
* (週別)今まで通り、直近の日別データを週サマリし、過去分の週合算値と一緒に掲載する
    * 棒グラフの色(日：赤、週：青)は、１色(全部：赤) のみとする
    * (週別)をデフォルト表示とし、デフォルト表示期間は60週とする
    * 1月30日～3月1日の合算データは、表示しない
* (累計)廃止しない
　* 週別に掲載するデータを合算し、「検査件数 累計：xx,xxx件」と注記に掲載する
    * 日別と同じく、直近の日別データのみ掲載する、週合算値は掲載しない
