### ISSUE TITLE
「検査陽性者の状況」フォーマットを縦型に変更

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#368]
## 改善詳細 / Details of Improvement

- 「検査陽性者の状況」は、厚生労働省への報告形式を元にしたと思われる、東京都サイトを元にした横に項目を並べたフォーマットを採用している。
- 東京都(6項目)と比べ項目数が9項目と増えており、先頭に表示している重要なサマリ情報なのに、スマホではかなり文字が小さくなっている。
- さらに今後"自宅療養"などが増える可能性はあり、横幅はますますひっ迫するが、拡張性は無くなっている。
- サマリ情報のフォーマットを、大阪府サイトを参考に、スマホでも文字が大きく表示出来て、拡張性がある「縦型」に変更するのが良いと考える。
- 先頭に重要なサマリ情報が掲載されるよう、注記も下に移すのが良いと考える。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/80718103-ac177480-8b34-11ea-8e4e-f341bcbbec70.png)

## 期待する見せ方・挙動 / Expected behavior
- 「検査陽性者の状況」のフォーマットを、大阪サイトを参考に、縦型に変更する
- 「検査陽性者の状況」は、スマホでもなるべく文字を大きく表示する
- 注記を下に移す
- 注記を最新の愛知県HPの文言に修正する

**Comment by amay077** [comment]
こちら、大阪府版のように「インデント付きテキストブロックを縦に並べる」であれば [good first issue] かなと思いますが、「L字型の枠の表現」が必要であれば SVG でゴリゴリ書くのでちょっと難易度上がりますね。

大阪府版のコピーでもよいですかね？

**Comment by takainou** [comment]
良いです。

明日になりますが、大阪版コピーで、愛知版作り直して載せます。

**Comment by takainou** [comment]
## スクリーンショット / Screenshot


![image](https://user-images.githubusercontent.com/63571899/81129858-b399ac00-8f80-11ea-93ca-a35e2b153f00.png)

## 期待する見せ方・挙動 / Expected behavior
- 「検査陽性者の状況」のフォーマットを、大阪サイトを参考に、縦型に変更する
-  インデント付きテキストブロックを縦に並べる
- 「検査陽性者の状況」は、スマホでもなるべく文字を大きく表示する
- 上部の注記を削除し、下部の注記のみとする
- 下部の注記は、main_summaryの備考を参照するのみとし、直接記載しない

**Comment by takainou** [comment]
東京サイトも縦型に変更されました。横型では数値の途中で改行してました。

![image](https://user-images.githubusercontent.com/63571899/82668437-b2e96100-9c74-11ea-91af-09399d98a559.png)

**Comment by amay077** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/1520

の実装をみると、「L字型」の実装もそれほど難しくなさそうに見えるので、これはマネしたいですね。

**Comment by takainou** [comment]
東京サイトは、3桁毎のカンマ区切り #524 も対応されていますね。

**Comment by takainou** [comment]
> ・上部の注記を削除し、下部の注記のみとする
> ・下部の注記は、main_summaryの備考を参照するのみとし、直接記載しない

この2点は https://github.com/code4nagoya/covid19/pull/619 で対応頂きました。ありがとうございました。

大阪サイトも「L字型」となりました。3桁毎のカンマ区切りは未対応ですね。
https://github.com/codeforosaka/covid19/pull/485

![image](https://user-images.githubusercontent.com/63571899/84497991-b8255300-acea-11ea-904d-039e58ec28e1.png)

**Comment by amay077** [comment]
千葉県も、続々ですねー。

https://github.com/civictechzenchiba/covid19-chiba/pull/396

**Comment by hmatsu47** [comment]
なるほど箇条書きを上手く使っているんですね。
東京のを持ってきてうまく当てはまるかわかりませんが、数日掛かっても大丈夫なら対応します。

**Comment by amay077** [comment]
おねがいします！
