### ISSUE TITLE
県民の皆さまへの情報提供ページの見直し

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#372]
## 改善詳細 / Details of Improvement
「県内の最新感染動向」の下から、「知事からのメッセージ」の上までの間の情報が、愛知県HPと比べて、以下の状況である。
1. 掲載情報が古くて正しくない
2. 誤った箇所にリンクがされている
3. 情報量が少ない、絞り込んだ基準が不明である

まず、当サイトへの掲載基準を定めて、絞り込む必要があると考えます
また、当サイトで表現を改めて掲載する場合、愛知県HPの更新に追随させる仕組みを構築する必要があると考えます

過去の掲載経緯が分かりませんが、古くて正しくないのは問題なので、対応案を検討しましょう。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/80810758-73909d00-8bff-11ea-8d98-92e1da77c2ae.png)

## 期待する見せ方・挙動 / Expected behavior
「愛知県新型コロナウイルス感染症対策サイト」にある「県民の皆さまへ」「県の情報」の情報について、

案１．"全て"を分かりやすく表現を改めて、当サイトに掲載し、更新に追随する仕組みを構築する

案２．"全て"当サイトからリンクを貼る。リンク変動(追加削除)に追随する仕組みを構築する

案３．掲載基準を設けて一部に絞り込み、分かりやすく表現を改めて、当サイトに掲載し、更新に追随する仕組みを構築する
　　残り"全て"当サイトからリンクを貼る。リンク変動(追加削除)に追随する仕組みを構築する

案４．掲載基準を設けて一部に絞り込み、分かりやすく表現を改めて、当サイトに掲載し、更新に追随する仕組みを構築する

案５．リンク掲載基準を設けて一部に絞り込み、当サイトからリンクを貼る

案６．掲載基準を設けて一部に絞り込み、分かりやすく表現を改めて、当サイトに掲載し、更新に追随する仕組みを構築する
　　別途リンク掲載基準を設けて一部に絞り込み、当サイトからリンクを貼る

案７．当サイトには掲載しない
　「愛知県新型コロナウイルス感染症対策サイト」へのリンクを貼るのみとする

案No　絞込　掲載情報
－－－－－－－－－－
案１　全て　改情報　
案２　全て　リンク
案３　全て　一部改情報、残リンク
－－－－－－－－－－
案４　一部　改情報
案５　一部　リンク
案６　一部　一部改情報、一部リンク
－－－－－－－－－－
案７　無し　無し

**Comment by amay077** [comment]
私は

> 案７　無し　無し

に賛成です。
現状、左側のリンクは数は多いが「愛知県HPのどこかへ飛ぶ」のでまとめて一つあればよいと考えます。トップページで愛知県HPへのリンクがあるのでそれで十分かと。

**Comment by hajime-miyauchi** [comment]
私も

> 案７　無し　無し

に賛成です。(今見ると重複してたりしますね)

一点、「新型コロナウイルス感染症が心配なときに」は非常に見やすく惜しいコンテンツなので、一旦リンクを外すとしても、情報ソースがあるのであれば最新の情報に更新していずれまた公開できたらいいなと思います。

**Comment by hmatsu47** [comment]
わたしも現段階では案７で。

おそらく、いまは県のサイトにたどり着ける状態になっていれば、こちらのサイトの掲載情報はそれほど閲覧されないのではないかと思います。

（サイト開設時の状況は違っていたと思いますし、また将来は状況が変わる可能性がありますが…たとえば県のサイト掲載の情報が（ルール・フロー変更等により）複雑化するとか、頻繁にアクセス過多でページが開かなくなるとか。）

**Comment by amay077** [comment]
> 「新型コロナウイルス感染症が心配なときに」は非常に見やすく惜しいコンテンツ

は、修正を行っていた私自身が感じている事として、
「修正コストがとても高く、変化にすぐに追従できない」
があります。
Web デザイナーさんが居たら、状況は違うのかも知れませんが。

コロナ禍が継続するにつれて、さまざまな要因で対処は変わってゆくと思いますので、
愛知県HPを参照していただくのがよいと考えます。
当初は存在しなかった PDF が用意された今では、最大の役割は終わったかなと。

**Comment by amay077** [comment]
案７で概ね合意できたとし、
#407 に、実施の issue を作ったので、こちらは目的を達したと判断して close します（なにかあったら re-open してください）。
