### ISSUE TITLE
「医療機関（病院）の状況」について

### ISSUE THREAD

**Issue by yukou-isshiki** [code4nagoya/covid19#38]
## 改善詳細 / Details of Improvement
- 神奈川県版の独自コンテンツとして存在しているので書いておきます。ただ、どこまで実現できるかは不明です。

https://www.pref.kanagawa.jp/osirase/1369/medical

**Comment by scrpgil** [comment]
神奈川県は、厚生労働省主体による全国一斉調査へ移行するようですね...！
厚生労働省から調査結果が公開されるまで、一時更新停止のようです...！

以下、転機

```
神奈川県で実施してまいりました日次での医療機関の状況調査は、3月30日（月）より厚生労働省主体による全国一斉調査へ移行いたしました。 本ページで公開中の神奈川県内の医療機関の状況については、厚生労働省の調査結果公開まで更新を停止いたしますので、 何卒ご理解のほどよろしくお願いいたします。
```

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19/issues/38#issuecomment-607294949 の通り、現時点では実現見込薄として close します。
