### ISSUE TITLE
グラフの並び順を検討する

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#384]
## 改善詳細 / Details of Improvement
5月2日の第5回ミーティングにて「グラフの並び順」について議論したが
結論には至らなかったため引き続きこちらで意見や感想を求める。

ミーティングで「グラフの並び順」について合意した内容
- 「検査陽性者の状況」は先頭
- 結論が出るまでは現状維持とする

「グラフの並び順」について出た意見
- 入院中数、重症者数、陽性患者数の順に表示を行う
- 陽性患者数、入院中数、重症者数の順に表示を行う
- 「検査陽性者状況の推移」で陽性患者数、入院中数、重症者数は表示できるので個別のグラフは冗長でないか

## 期待する見せ方・挙動 / Expected behavior
5/11（月）を期限として広く意見をいただきたい

- どのような並び順が良いと考えるか
- その理由など

**Comment by daikiyamamuro** [comment]
めちゃくちゃ本音でいうと

- 市町村別感染状況
- 陽性患者数
- 検査実施件数

以外は見てないです😂

**なので、この３つを上の方にほしいです。**
（あとは別ページでもいいくらいです。）

プラスで気になるのは
- 回復者（退院者）数

です。


----
### 以下、個人的な意見
理由としては
私や私の周囲（家族、同僚）は

**「わが町は大丈夫か？」**
**「陽性の人は増えた？減った？」**
**「検査はされてんの？」**
**「感染しても治るの？」**

を気にしているからです。


あと、本音ついでに言うとデータ元などの注釈も **あの場所には** 不要だと思います。
（ないのはあれなんで、別ページに記載するとか？）

この理由は
- 日々の推移と傾向が見れればそれで良い（つまりデータ元がどうとか気にならない）
- 他県の注釈スッキリ版を見るとめちゃ見やすい


よりシンプルで、多くの人が毎日見てくれるような役に立つサイトになってほしいと願っています。そしてそれが習慣となり、意識付けになれば、情報を提供するだけではなく、感染予防に少しでも貢献できるかもしれません。そういったサイトになっていってほしいです。

ちなみに、オープンソースなので方向性に違和感があると開発者は離れちゃうと思います😅
（先日のミーティングの議事録に **開発者のやる気** に触れられていた部分がありましたので..）

**Comment by amay077** [comment]
議論が発散してしまいますが（汗）、

愛知県版の制限解除の条件が発表されました。 https://www.chunichi.co.jp/article/front/list/CK2020051102000071.html
https://youtu.be/9gj2zhgPy-g?t=739

![image](https://user-images.githubusercontent.com/401369/81549740-2e682a00-93ba-11ea-97c4-735309044c8d.png)

当面は、それに関わるパネルを上の方に表示した方がよいのかなと考えます。

■現在

|                      |              |
|----------------------|--------------|
| 検査陽性者の状況     | 入院中数     |
| 重症者数             | 陽性患者数   |
| 検査陽性者状況の推移 | 検査実施件数 |
| 市町村別感染状況     |              |

■amay077案

|                      |              |
|----------------------|--------------|
| 判断指標と達成状況 ※1  | 陽性患者数 ※2     |
| 検査実施件数 ※2     | 入院中数 ※2     |
| 検査陽性者の状況             | 検査陽性者状況の推移 |
| 市町村別感染状況 | 重症者数  |

- ※1: 新設。上画像のような指標の表示とその時点の状況（注意に達したら黄色、危険なら赤で塗る）
- ※2: それぞれ「7日移動平均線」の折れ線グラフを棒グラフと共に表示。既定は「日別」。

３つの指標（新規感染者数、陽性率、入院患者数）に係るグラフを先に並べています。
その次には、現在の状況である「検査陽性者の状況」とその推移を並べ、
市町村別感染状況 の位置は変わりません。
重症者数 は、数がそれほど多くない愛知県においては、現在は「無し」でもいいかなと思います。

愛知県HP で、この指標と状況がわかりやすく掲示されるなら、同じことをする必要はないとも思います。

**Comment by ozo360** [comment]
第4回のミーティングから少しづつ状況が変化しているので
現時点ではamay077案が私もしっくりくる気がします。
意見が異なる点としては、
- 検査実施件数はそのまま陽性率での方がよいのではないでしょうか
- 入院中数は入院患者数に置き換えても大丈夫とお墨付きをもらったと捉えて変更

くらいです。

**Comment by takainou** [comment]
私も基本方針は amay077 さん意見に賛同します。5/11の知事会見で状況が変わってしまった認識です。

幾つかコメントがあります。

**「検査実施件数」「陽性率・検査人数」**
「検査実施件数」には陰性確認を含んでおり、推移を見て状況判断するには"正しくない"為、別途「陽性率・検査人数」グラフを開発する必要があります。なお「検査実施件数」は、最後尾で良いと考えます。

**「検査陽性者の状況」と「検査陽性者状況の推移」の順序**
「検査陽性者状況の推移」は「退院」を主に見せるグラフとしています。「入院中」を増やす「陽性患者数」、「入院中」を減らす「退院」と考えると、「増加分/入院中/減少分」の並びが座りが良いと考えます。会社の「売上/利益/経費」と考えると分かり良いですね。利益は増やしたい、入院中は減らしたいので、例としてはいまいちですけど。また「検査陽性者状況の推移」は見映えが良く初心者受けすると考えます。つまり「検査陽性者状況の推移」が先で、その後に「検査陽性者の状況」が良いと考えます。

**「重症者数」**
「無し」としても復活させる事が容易でしたら「重症者0人が1週間程度継続した時点」で「無し」としても良いと考えます。それまで、最後尾１つ前で良いと考えます。もちろん復活して欲しくないです。

**「判断指標と達成状況」**
「検査陽性者の状況」が縦型 #368 なら、同居できるかもしれませんね。

**「陽性患者数」**
デフォルトを(日別)とするまでに、#429 が解決している事が前提ですね。

**「市町村別感染者数」**
初心者の掴みには良いので、前の方にするのも良いと考えていたのですが、現状だと日々ほぼ変化しないので、amay077さん案で良いと考えます。

以上をまとめると以下順序となります。

1. 判断指標と達成状況…開発未
2. 陽性患者数(日別)
3. 陽性率・検査人数…開発未
4. 入院中数
5. 検査陽性者状況の推移[退院]
6. 検査陽性者の状況
7. 市町村別感染状況
8. 重症者数
9. 検査実施件数

**Comment by amay077** [comment]
ここまでの意見をまとめますと、

|                      |              |
|----------------------|--------------|
| 1. 判断指標と達成状況...開発未  | 2. 新規感染者数     |
| 3. 陽性率...開発未     | 4. 入院患者数     |
| 5. 検査陽性者状況の推移  | 6. 検査陽性者の状況 |
| 7. 市町村別感染状況 | 8. 重症者数  |
| 9. 検査実施件数 |   |

で確定ということでよさそうですね。

こうなってくると、週別 or 日別 の既定値は、当面はすべて「日別」で統一してよさそうです。

2～4 のタイトルは、@ozo360 の意見で、 指標と合わせた方が良いと思いますので、 https://github.com/code4nagoya/covid19/issues/384#issuecomment-626614431 の画像に合わせてみました（最終的には、愛知県HP に掲載されるであろう表記に合わせる）。

> 「判断指標と達成状況」
> 「検査陽性者の状況」が縦型 #368 なら、同居できるかもしれませんね。

当面では指標を目立たせたいので、同居せずスペースに余裕があるなら文字を大きくするなどしたいと思います。

**「重傷者数」**
消すことも復活することも容易なので、表現しなくてもよくなったら消しましょうか。

**「検査実施件数」**
「2. 陽性率」のためのデータが入手でき、そちらに 陽性者数の積上棒グラフと移動平均線が表現されるであろうので、こちらには不要で現状ママでよいと考えます（こちらで表現しても正しくない）。

直近では、上表レイアウトを実現することをゴールに進めましょうか。
必要なタスクを次の通り issue 化します。あ、 Project を使えばいいのか。

1. #429
2. 「1. 判断指標と達成状況」のパネルを作る
3. 「3. 陽性率」のパネルを作る
4. 「2. 新規感染者数（旧:陽性患者数）」に７日移動平均の折れ線グラフを追加する
5. 「4. 入院患者数（旧:入院中数）」に７日移動平均の折れ線グラフを追加する

セオリーだと大きめな機能追加は git のブランチを別に用意して開発し、全て揃ったところで development にマージするのですが、一つ一つは独立した機能追加で個別にリリースしても問題ないので、development のまま進めましょう。

**Comment by takainou** [comment]
取り纏めありがとうございます。合意します。

タスク4.5.はIssue #453 起票しました。

1点だけ。「新規感染者数（旧:陽性患者数）」の名称変更について、(日別)(週別)は新規が付いた方が良いですが、(累計)は違和感ありませんか？(累計)だけ「累計感染者数」とした方が良いと考えます。

**Comment by amay077** [comment]
どうでしょう？
私は「新規感染者数の累計」という語句に特に違和感を感じないのですが。。

日別 | 週別 | 累計 で 累計 を選択したときだけ、タイトルを「累計感染者数」とすることは可能だし、その方が親切ではありますね。

**Comment by takainou** [comment]
その辺りは人それぞれかもしれませんね。私は、(日別)(週別)における「新規」はあくまで当日や当週のみを指すイメージなので、指標名は良くても、過去を表示しているグラフ名では違和感を感じますが、そこは皆さんに合わせます。

**Comment by amay077** [comment]
> その辺りは人それぞれかもしれませんね。私は、(日別)(週別)における「新規」はあくまで当日や当週のみを指すイメージなので、指標名は良くても、過去を表示しているグラフ名では違和感を感じますが、そこは皆さんに合わせます。

こちらは別途 issue 化していただければ、どなたか実装していただければ（私かもｗ）改善になりますので。


本件は議論の役割は終え
https://github.com/code4nagoya/covid19/projects/4
に引き継ぎましたので、close しますね。
