### ISSUE TITLE
「 当サイトは有志～運営まで。」の文章がmdi-open-in-newアイコンがないのに新規タブで開く

### ISSUE THREAD

**Issue by Nekoya3** [code4nagoya/covid19#387]
## 起こっている問題 / The Problem
-「当サイトは有志が作成したものです。お問い合わせは愛知県ではなく、当サイト運営まで。」の文章がmdi-open-in-newアイコンがないのに新規タブで開く。
- 同一サイト内の移動なのにもかかわらず再読み込みが発生している

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/17000370/80898824-24538500-8d43-11ea-9a54-fd717f6bcc0d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 新規タブで開くのであればmdi-open-in-newアイコンを付ける
- 同一タブの場合はnuxt-linkで遷移するようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.code4.nagoya にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hajime-miyauchi** [comment]
あ、ほんとだ。たしかに！ありがとうございます。

**Comment by hmatsu47** [comment]
同一タブの中で遷移する形で対応します。
