### ISSUE TITLE
「検査陽性者の状況」を出典とするグラフの注記の整理

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#389]
## 改善詳細 / Details of Improvement
- グラフ数が増えてきて出典元が「出典: 愛知県新型コロナウイルス感染症対策サイト（一部、県知事のTwitter）」だけでは、そのサイトのどのデータを元に可視化したのか？がわかりづらくなってきた。
- 一旦本Issueでは **「検査陽性者の状況」を出典とするグラフ** を対象とします。
- 具体的には **「「入院中数」「重症者数」「検査陽性者状況の推移」** の3つのグラフが対象です。
- 関連するIssue https://github.com/code4nagoya/covid19/issues/385

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/749758/80914274-7c12e000-8d85-11ea-8c31-aeaf357ebcba.png)
![image](https://user-images.githubusercontent.com/749758/80914290-a6649d80-8d85-11ea-8eef-3e37219c6be6.png)
![image](https://user-images.githubusercontent.com/749758/80914310-c5632f80-8d85-11ea-9b78-d776027ff902.png)

## 期待する見せ方・挙動 / Expected behavior
1. 「_愛知県が発表した【感染症発生状況】を_」という表記を「_愛知県が発表した「検査陽性者の状況」を_」という表記に変更。(3グラフ共が対象)※
2. 「入院中数」のグラフは「_※「入院中数」とは、愛知県が発表した「検査陽性者の状況」のうち、「入院中」の人数です。_」の注記を先頭に追加する。
3. 同じく「重症者数」のグラフは「_※「重症者数」とは、愛知県が発表した「検査陽性者の状況」のうち、「重症」の人数です。_」の注記を先頭に追加する。

※「【感染者発生状況】」という表記だと「検査陽性者の状況」「日別感染者数」「累計人数」の3つの画像を総称しており範囲が広いため。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HasegawaTadamitsu** [comment]
初めてですが、やってみます！

**Comment by hajime-miyauchi** [comment]
お願いします！

**Comment by HasegawaTadamitsu** [comment]
pull-requestを出してみましたが、これでいいのか。。よくわかりません！
ご指摘お願いします！
