### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」を削除

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#40]
## 起こっている問題 / The Problem
- 東京都の内容が多いので一旦削除して、情報が集まったら復活させる

**Comment by yukou-isshiki** [comment]
リンクを外す形で良いですか？

**Comment by amay077** [comment]
あ、PR 出しちゃいました。
https://github.com/code4nagoya/covid19/pull/42

**Comment by yukou-isshiki** [comment]
特に何もしていないので大丈夫です。
