### ISSUE TITLE
「陽性患者の属性」パネルを削除し、「陽性患者数」パネルに一次ソース及びCSVへのリンクを付ける

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#405]
## 改善詳細 / Details of Improvement
- #344 より
- 「陽性患者の属性」パネルはパフォーマンス、ユースケース不明の理由で削除とする
- 代わりに、GitHub の data/patients.csv へのリンクを「陽性患者数」グラフに貼ることとする

## スクリーンショット / Screenshot

![図1](https://user-images.githubusercontent.com/401369/81064185-32a4cb00-8f14-11ea-8569-1bdf581be87e.png)

![図2](https://user-images.githubusercontent.com/401369/81064435-a9da5f00-8f14-11ea-9046-de1ab79fd35e.png)

## 期待する見せ方・挙動 / Expected behavior
- 図1: 陽性患者の属性パネルを削除し、市町村別感染状況パネルを左に詰める
- 図2: 陽性患者数パネルの下部に、グラフデータの説明兼、陽性患者の属性一覧へのリンクを追加（文言は以下）

※「陽性患者数」とは、愛知県が発表する「 **愛知県内発生事例** 」を日別または週別に集計した人数です。(参考: **当サイトでCSV形式に加工したデータ** )
↑太字部にリンクを貼る。リンク先は 

- 愛知県内発生事例 → https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
- 当サイトでCSV形式に加工したデータ → https://github.com/code4nagoya/covid19/blob/development/data/patients.csv

### 開発時の注意

現在、グラフ下部の注記領域には、単純なテキストしか配置できないので、リンク付きテキスト を配置できるようにする実装が必要になります。

**Comment by hajime-miyauchi** [comment]
注記について一次情報の記載と、当サイトの加工データ(CSV)を明確にするのどうでしょう？

※「陽性患者数」とは、愛知県が発表する「 [愛知県内発生事例](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html) 」を日別または週別に集計した人数です。(参考: [当サイトでCSV形式に加工したデータ](https://github.com/code4nagoya/covid19/blob/development/data/patients.csv))

余談ですが、GitHubのページ、PCだとフィルタもかけられるようになってましたが、モバイルだと生データになるんですね。CSV使うシーンはPCだと思うので問題ないと思いますがー。

![IMG_7045](https://user-images.githubusercontent.com/749758/81066163-a8f6fc80-8f17-11ea-8046-508be3b3ea78.PNG)

**Comment by amay077** [comment]
> 注記について一次情報の記載と、当サイトの加工データ(CSV)を明確にするのどうでしょう？

良いと思います。そうしましょう。

> モバイルだと生データに

あれ、私はスマホでも表形式になりますね。Android10 の Chrome ですが。
![image](https://user-images.githubusercontent.com/401369/81078890-c339d600-8f29-11ea-8428-64d5b3a93925.png)

**Comment by hajime-miyauchi** [comment]
あ、ごめんなさい。iOSのSafariでも表敬式になりました。
さきほどはGitHub for mobile内で開いたために生データ表示になってしまったようです。

![IMG_7048](https://user-images.githubusercontent.com/749758/81079412-7dc9d880-8f2a-11ea-889b-fb294900c35e.PNG)
