### ISSUE TITLE
左メニュー内リンクの不要なものを削除する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#407]
## 改善詳細 / Details of Improvement
- #372 より
- 案7 を採用し、「掲載内容が古い」「リンク切れ」「用途が不明」などのリンクはすべて削除する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/81081100-74417000-8f2c-11ea-9bb9-96014c86e514.png)

## 期待する見せ方・挙動 / Expected behavior
- 「新型コロナウイルス感染症が心配なときに」から「愛知労働局主催等 中止又は延期するイベント等」までの項目を削除する
- 「知事からのメッセージ」以降の項目を上へ詰める（トルツメ）

**Comment by HasegawaTadamitsu** [comment]
着手します
