### ISSUE TITLE
SNS/HPリンクを見直す

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#411]
## 改善詳細 / Details of Improvement
- #366 #367 より
- Step2 別ページ「各市町村自治体の対策サイト」の設置は止める
- Step1 のみとし、「コロナに負けるなナゴヤTwitter」を追加する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/81132386-37579680-8f89-11ea-8127-9b6151841a49.png)

## 期待する見せ方・挙動 / Expected behavior
「知事からのメッセージ」以下に貼られているSNS/HPリンク７個について、以下の通り更新する。

- 以下３リンクを削除
　・知事からのメッセージ
　・愛知県公式ホームページ
　・愛知県公式Twitter
- 以下２リンクを追加
　・愛知県 新型コロナウイルス感染症対策サイト
　　https://www.pref.aichi.jp/site/covid19-aichi/
　・コロナに負けるなナゴヤ(Twitter)
　　http://twitter.com/corona_nagoya
- 「他自治体の対策サイト」から「他地域の対策サイト」に名称変更
　自治体公式サイトで無いケースもあるため

更新後のSNS/HPリンクは以下の通り６個となる
　・当サイトについて
　・愛知県 新型コロナウイルス感染症対策サイト
　・愛知県-新型コロナ対策パーソナルサポート(LINE)
　・名古屋市 新型コロナ特設サイト
　・コロナに負けるなナゴヤ(Twitter)
　・他地域の対策サイト

**Comment by HasegawaTadamitsu** [comment]
着手します！
