### ISSUE TITLE
注記や補足をデフォルト非表示とし、必要な時に開いて読む形はどうか？

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#415]
## 改善詳細 / Details of Improvement
 #384 の @daikiyamamuro  さんコメントと、 #389 の @hajime-miyauchi さんの求める必要性も分かるので、どうにか二つを満たせないかと考えてみました。

東洋経済オンラインの新型コロナウイルス 国内の感染状況のサイトでは、注記や補足を1行目途中までのみデフォルト表示し、必要な時に「もっと読む」を開いて読む形式となっています。
https://toyokeizai.net/sp/visual/tko/covid19/

これを採用し、当サイトの対応案として、以下が良いと考えますが、いかがでしょうか？
- グラフ上部に注記や補足は記載しない
- グラフ下部の注記などは、1行目途中まで記載し、残りを「もっと読む」としておく
- デフォルトは「もっと読む」を表示して閉じた状態とする
- 対象はグラフ下部に記載する情報全て
　・注記
　・※による補足説明
　・出典: 愛知県新型コロナウイルス感染症対策サイト
　・右下の当サイトでの更新時刻

こうすると、デフォルトではシンプルでスッキリしスマホでも縦に短くなり、必要な情報は掲載可能となると考えます。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/81142379-85c95d00-8faa-11ea-8a29-46bfe5defcdd.png)
![image](https://user-images.githubusercontent.com/63571899/81142382-87932080-8faa-11ea-88a6-03f7ad1e6b1a.png)

**Comment by amay077** [comment]
これは同意です。
特にスマホでは、注記のためにコンテンツが縦に長くなってしまい、スクロール操作量が増えてしまいますね。

東京版の「テーブルを表示」のように単純な Expand/Collapse でもよいかと思います。

![image](https://user-images.githubusercontent.com/401369/81464847-2e242f00-9200-11ea-82cb-daf342a12fd3.png)

**Comment by takainou** [comment]
ありがとうございます。

東洋経済と東京サイト、形式はどちらでも良いと考えます。

東京サイトを参考にした場合、留意したいのは、「テーブルを表示」下の以下も、愛知サイトではデフォルト非表示としたい点です。
> オープンデータを入手
> 2020/05/08 20:00 更新

少し別件ですが、東京サイトで上部に注記が有ったからか、愛知サイトでもグラフ上部に少し隙間を空けていると思います。グラフ上部に注記しないのであれば、この上部の隙間は減らす事が出来るものなのでしょうか？

**Comment by ozo360** [comment]
出典情報（データソース元）はグラフなどと一緒に表示されるべき情報で
開けば見える、辿れば見れるという見せ方は反対です。

**Comment by amay077** [comment]
@takainou さん、

> グラフ上部に注記しないのであれば、この上部の隙間は減らす事が出来るものなのでしょうか？

![image](https://user-images.githubusercontent.com/401369/81826760-1091f500-9573-11ea-9c35-4bcaf275fdf7.png)

![image](https://user-images.githubusercontent.com/401369/81827378-aaf23880-9573-11ea-961d-bec79f471fd7.png)


この薄橙色の領域のことであれば、狭めても問題ないと思いますね。
特にモバイルだとより大きな領域が空くのが気になってはいました。
これはこれで別 issue 化お願いします。

@ozo360 さんの言われる

> 出典情報（データソース元）はグラフなどと一緒に表示されるべき情報で
>開けば見える、辿れば見れるという見せ方は反対です。

のように、グラフ上下の領域を十分に狭めることができれば、出典と更新日時 は表示されていて問題ないかと思います。

**Comment by takainou** [comment]
> この薄橙色の領域のことであれば、狭めても問題ないと思いますね。
> 特にモバイルだとより大きな領域が空くのが気になってはいました。
> これはこれで別 issue 化お願いします。

Issue #473 起票しました。確認をお願いします。

グラフ下部も薄橙色の領域にて、出典と更新日時の上部に隙間が有ります。
黄緑色の領域で隙間は確保できているので、この隙間も狭めても良いのではないでしょうか？
![image](https://user-images.githubusercontent.com/63571899/82001442-3106a000-9696-11ea-9b3a-f7bf121aaa3b.png)
![image](https://user-images.githubusercontent.com/63571899/82001466-3663ea80-9696-11ea-9e56-9016761f832f.png)

**Comment by amay077** [comment]
> 黄緑色の領域で隙間は確保できているので、この隙間も狭めても良いのではないでしょうか？

私もそう思います。
グラフのパディング（黄緑色の領域）で十分かなと感じますね。
