### ISSUE TITLE
「市町村別感染状況」右上の更新日時を「陽性患者数」右上日付と同じにする

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#419]
## 起こっている問題 / The Problem
- 「市町村別感染状況」カラム地図の右上の更新日時が、右下の更新日時と等しくなっている。
- 「市町村別感染状況」の元データは「陽性患者数」と同じであり、それと同じ日付を右上に表示するのが良いと考える。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/81168894-d3f25680-8fd2-11ea-8913-6645a513045b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「市町村別感染状況」右上の更新日時を「陽性患者数」右上日付と同じにする

**Comment by hmatsu47** [comment]
対応します（「新規感染者数」の「M/D 時点」に合わせる）。

**Comment by hmatsu47** [comment]
あー、Issuesをリロードして確認するタイミングをミスったみたいで直前に対応済みのものにプルリクを出しちゃいました…。
