### ISSUE TITLE
日本語以外のreadme等参照されていないだろうファイルの削除

### ISSUE THREAD

**Issue by HasegawaTadamitsu** [code4nagoya/covid19#439]
## 改善詳細 / Details of Improvement
- 日本語以外のreadme等参照されていないだろうファイルの削除
翻訳へのリンクを削除/ステージング環境の記載の削除 #51
で、README.mdから他言語へのリンクが削除されたかと思います。
そのため、下ファイルには参照元がなくなったかと思います。
また、日本語以外のREADME.mdには、東京の情報が残っており誤解を生む原因になっているかと思います。
本当に必要とされていないかはgrepで確認した程度です。もし、その前提が違っていたらご指摘ください。

これら理由より、下のファイルを削除したほうが望ましいかと思うのですが、
どうでしょうか？

というのは、中国語を知人に確認してもらったあと、どこからも参照されていないことに気が付き、同様なことが起きないようにと思った次第です。

## 期待する見せ方・挙動 / Expected behavior
- 下のファイルの削除

> covid19/
> README_EN.md
> README_ES.md
> README_KO.md
> README_ZH_TW.md
> 
> covid19/.github/
> CODE_OF_CONDUCT_EN.md
> CODE_OF_CONDUCT_ES.md
> CODE_OF_CONDUCT_KO.md
> CODE_OF_CONDUCT_ZH_TW.md
> CONTRIBUTING_EN.md
> CONTRIBUTING_ES.md
> CONTRIBUTING_KO.md
> CONTRIBUTING_ZH_TW.md
> 

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
ありがとうございます。
私も削除したほうが適切と考えます。

Web アプリについては、ビルドできる状態が維持できればよし、
それ以外についてももしあとで必要とわかっても revert すればよいので、
不要と思われるものは削除していきましょう。

**Comment by HasegawaTadamitsu** [comment]
着手します！
