### ISSUE TITLE
「市町村別感染状況」が累計値であることを強調する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#448]
## 改善詳細 / Details of Improvement
- 「市町村別感染状況」は累計であるが、「状況」という名称だと「最新の時点情報（現在感染者数）」と勘違いされそう
- タイトルと凡例の文言を変えて「累計」であることを強調する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/81626387-817fc280-9436-11ea-8621-1c227f6990bd.png)

## 期待する見せ方・挙動 / Expected behavior
- 変更後タイトル： 市町村別感染者数
- 変更後凡例： 累計感染者数

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by maketomo** [comment]
やります！

**Comment by amay077** [comment]
対応ありがとうございました！
リリースできましたので close します。
