### ISSUE TITLE
「陽性患者数」(日別)と「入院患者数」に「移動平均」線を追加する

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#453]
## 改善詳細 / Details of Improvement
- 県の定める3指標のうち「新規感染者数」と「入院患者数」が、後方7日移動平均を用いる事となりました
- 「陽性患者数」(日別)と「入院中数」に「移動平均」の表示を追加するのが良いと考えます

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/81677896-3f816b80-948c-11ea-9a9f-db081d9fbb84.png)
![image](https://user-images.githubusercontent.com/63571899/81677951-46a87980-948c-11ea-9968-deadf6988732.png)

## 期待する見せ方・挙動 / Expected behavior
**「陽性患者数」(日別)**
- N日の移動平均＝[陽性患者数(N-6日)+陽性患者数(N-5日)+陽性患者数(N-4日)+陽性患者数(N-3日)+陽性患者数(N-2日)+陽性患者数(N-1日)+陽性患者数(N日)]÷7
- 陽性患者数0人の日も、同様に算出する
- 7日分のデータが取得出来ない過去日は算出しない(例：最古が1/26の場合、1/31以前は算出しない、2/1以降のみ算出)
- 補足に「※移動平均は後方7日移動平均値です」と追記する
- 折れ線グラフで表示する
- (日別)にのみ追加し、(週別)(累計)には追加しない

**「入院患者数」**
- N日の移動平均＝[入院患者数(N-6日)+入院患者数(N-5日)+入院患者数(N-4日)+入院患者数(N-3日)+入院患者数(N-2日)+入院患者数(N-1日)+入院患者数(N日)]÷7
- 3/25より前は入院患者数が入手出来ていないので、7日分のデータが取得できる3/31以降で算出する
- 「検査陽性者の状況」が取得出来ずデータが無い日が、7日分の中に1日有った際は、無い日を含めず加算結果を6で除算する。7日中6日有った際も当日のみを1で除算する
- 補足に「※移動平均は後方7日移動平均値です」と追記する
- 折れ線グラフで表示する

**Comment by amay077** [comment]
とりあえず、棒と折れ線の複合グラフの基盤を作ります。
