### ISSUE TITLE
「陽性率」のグラフを追加する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#454]
## 改善詳細 / Details of Improvement
- 愛知県の規制解除指標のひとつである「過去７日間の陽性率」を示す折れ線グラフ
- ↑の根拠となる「検査実施人数」と「陽性者数」が分かる積み上げ棒グラフ

を１枚のグラフパネルで表現する。

## スクリーンショット / Screenshot

■東京都版の陽性率グラフ

ref https://github.com/tokyo-metropolitan-gov/covid19/issues/4103#issuecomment-627313385

![image](https://user-images.githubusercontent.com/401369/81695234-52506c00-949d-11ea-98a7-f032e3348c17.png)

■愛知県版の検査実施数グラフ

![image](https://user-images.githubusercontent.com/401369/81695437-97749e00-949d-11ea-9717-9bd98b752143.png)

## 期待する見せ方・挙動 / Expected behavior
- 愛知県版の検査実施数グラフ に、東京都版の陽性率グラフ を実装したものになるだろう
- ただし「愛知県版の検査実施数グラフ」は 「検査実施 **件数**」であり、新規に作るグラフは「検査実施 **人数**」であることに注意。
-  「検査実施 **人数**」データが公開されるか？は不明ですが、「在る前提」で実装してください。
- 積み上げ棒グラフの項目は下段より以下の通りとする
  1. 凡例-陽性者数、色-濃赤
  2. 凡例-陰性者数、色-薄赤
- 折れ線グラフは、東京版に倣うが、色は変えた方が目立つかも知れない。
- [日別]を選択した場合は、折れ線グラフは「過去７日間の陽性率」を表示する。[週別] を選択した場合は、折れ線グラフはなし。
- [累計] は、まずは無しで。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takainou** [comment]
> 「検査実施 件数」データが公開されるか？は不明ですが、「在る前提」で実装してください。

「検査実施 **人数**」ですね。

> ↑の根拠となる「検査実施人数」と「陽性者数」が分かる積み上げ棒グラフ

東京の陽性率の定義は、
> 陽性率＝陽性判明数の移動平均／（陽性判明数＋陰性判明数）の移動平均

なので、積み上げ棒グラフがふさわしいですが、愛知の陽性率の定義は、
> 陽性率＝陽性者数(過去７日間)／検査人数(過去７日間)

なので、陽性者数と検査人数の2つの棒グラフを、系列の重なり100%で表示する(陽性者数が手前)が良いと考えます。以下イメージ添付します。
![image](https://user-images.githubusercontent.com/63571899/81704936-639f7580-94a9-11ea-90eb-8ad12c63a145.png)


> [週別] を選択した場合は、「その週の陽性率」を表示する。

週が月－日なので、その週が終われば、[週別]の陽性率は、[日別]の日曜の陽性率と合致します。

**Comment by amay077** [comment]
> 「検査実施 人数」ですね。

訂正しました、ありがとうございます。

> 系列の重なり100%で表示する(陽性者数が手前)が良いと考えます。「陰性者数」という言葉も愛知県では登場していません

これは使用しているライブラリの chart.js では実現できそうにないですね。
普通の StackedBar にしかならなさそうです。項目名に特にこだわりはないのですが。

> 週が月－日なので、その週が終われば、[週別]の陽性率は、[日別]の日曜の陽性率と合致

はい、そうなります。株価チャートだと週足では「７週移動平均線」とか出すのでしょうが、ここでは不要でしょうね。

**Comment by amay077** [comment]
あ、 https://github.com/code4nagoya/covid19/issues/453 では移動平均線は 日別 のみ案だったのですね、見落としてました。

ではそちらに合わせて こちらも 日別 のみとします。

**Comment by takainou** [comment]
> これは使用しているライブラリの chart.js では実現できそうにないですね。
> 普通の StackedBar にしかならなさそうです。

ライブラリの制約なのですね。では、積み上げ棒グラフで、以下の様に表示するのが良いと考えます。

- 「陰性者数」＝「検査人数」－「陽性者数」を算出する
- 積み上げ棒グラフ(「陽性者数」+「陰性者数」)とする
- 凡例の「陽性者数」をクリックしても「陽性者数」棒グラフを非表示化しないよう設定する
→「陰性者数」のみの表示を避ける
- 「陰性者数」にオンカーソルで表示する数値は「検査人数」とする
→どこにカーソルを置いても、その日の「陽性率」「検査人数」「陽性者数」と全情報を表示しても良い
- 「陰性者数」の凡例名を「検査人数」とする

つまり、データとしては「陰性者数」だが、表示・操作上は「検査人数」として振る舞う事とする



なお、「検査件数」ではなく「検査人数」をこのグラフで確認頂きたいので、
- グラフ名を東京に倣い「検査人数・陽性率」とする
- 「検査人数」の色をテーマカラーの濃赤とする

のも良いと考えます。

**Comment by amay077** [comment]
リリースしたので close します
