### ISSUE TITLE
グラフの並び順を規制判断基準の順にする

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#456]
## 改善詳細 / Details of Improvement
- 目下の関心は愛知県の規制判断基準と達成状況であるので、それに準じたパネルを先に並べる
- via https://github.com/code4nagoya/covid19/issues/384#issuecomment-627284989

## スクリーンショット / Screenshot

|                      |              |
|----------------------|--------------|
| 1. 判断指標と達成状況...開発未  | 2. 新規感染者数     |
| 3. 陽性率...開発未     | 4. 入院患者数     |
| 5. 検査陽性者状況の推移  | 6. 検査陽性者の状況 |
| 7. 市町村別感染状況 | 8. 重症者数  |
| 9. 検査実施件数 |   |

## 期待する見せ方・挙動 / Expected behavior

以下の issue が実装されたあとになります。

- #454 
- #455

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takainou** [comment]
> 以下の issue が実装されたあとになります。

本件ですが、#454 #455 の開発を待たず、対応頂いて良いと考えます。

政府による緊急事態宣言(特定警戒)は解除され、
「感染拡大しないよう、医療崩壊しないよう自粛して、長期的に推移を見守る」
フェーズから、
「日に数人の感染者で感染再拡大せず、入院患者が0人に向かうのを確認する」
フェーズに移行しており、#454 #455 が無い状態でも、新しいグラフの並び順の方が良いと考えます。

グラフの並び順変更の際、可能なら、#429 の応急処置対応が完了しているので、

- 「陽性患者数」のデフォルト表示を(日別)とする

のみ合わせて対応頂くのが良いと考えます。
他の改修(グラフ名含め)は順次適用されれば良いと考えます。

**Comment by amay077** [comment]
私は、レイアウトが短期間に頻繁に替わるのは避けたいと考えています。

#454 #455 を待たずにレイアウトすると、開発未の 1. 3. が詰められて下図のようになると思いま
す。

|                      |              |
|----------------------|--------------|
| 2. 新規感染者数 |  4. 入院患者数    |
| 5. 検査陽性者状況の推移  | 6. 検査陽性者の状況 |
| 7. 市町村別感染状況 | 8. 重症者数  |
| 9. 検査実施件数 |   |

となり、1. 3. が実装された後に、

|                      |              |
|----------------------|--------------|
| 1. 判断指標と達成状況...開発未  | 2. 新規感染者数     |
| 3. 陽性率...開発未     | 4. 入院患者数     |
| 5. 検査陽性者状況の推移  | 6. 検査陽性者の状況 |
| 7. 市町村別感染状況 | 8. 重症者数  |
| 9. 検査実施件数 |   |

になると、特に 2. の移動が顕著なので避けたいです。
（2. 4. がもともと横並びで「行」が上に挿入される程度ならよかったのですが。。）

なのでレイアウト変更を急ぐなら、#454 #455 の進捗が 50％ 程度ですべてを表現できていなくとも、「パネル」がそこに在ってほしいなという意見です。

**Comment by takainou** [comment]
私が把握していないので申し訳なかったのですが、モバイル用の1列表示と、PC用の2列表示の2つを設定していて、PC用の方はレイアウト変更の負荷が高いという事ですね。了解です。

> 50％ 程度ですべてを表現できていなくとも、「パネル」がそこに在ってほしいな

「検査人数」の県からの公表時期が見えておらず、公表前に、#454 を掲載すべきなのか迷う所です。 #455 も「検査人数」が公表されないと陽性率が載せられず進捗は 67%(2/3) です。50%程度のグラフの「パネル」を前の方に配置してしまうのは、グラフの並び順を議論した意図から外れてしまいませんか。それであれば、全部揃うのを待ちましょう。
