### ISSUE TITLE
緊急事態宣言の解除に併せて、トップの文言を変える

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#461]
## 改善詳細 / Details of Improvement
- [宣言 あす解除対象「特定警戒」で愛知や福岡も検討・NHKニュース](https://www3.nhk.or.jp/news/html/20200513/k10012427921000.html) より
- 愛知県も緊急事態宣言の対象地域から外れる可能性があるため、トップの文言をそれに応じて変える。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/81777431-c2a5ce80-952b-11ea-9aec-6cc2192cf3b1.png)

## 期待する見せ方・挙動 / Expected behavior

政府の緊急事態宣言、政府の特系警戒地域、愛知県の緊急事態宣言 の状況により、以下のパターンでメッセージを変える。
（政府の特系警戒地域 はあいまいになりそうなので、その場合は政府の緊急事態宣言と同じとする。）

#|政府の緊急事態宣言|政府の特定警戒地域|愛知県緊急事態宣言|メッセージとリンク先|
--|--|--|--|--|
現在|発出中|対象|発出中|[全国を対象区域とした緊急事態宣言が 5/31 まで延長されました。愛知県は引き続き「特定警戒都道府県」 に指定されています](https://corona.go.jp/) |
1|解除|解除|解除(政府と同日)|政府の緊急事態宣言、愛知県独自の「愛知県緊急事態宣言」は 5/○ に解除されました。引き続き十分な感染予防に努めましょう。 ※リンクなし |
2|解除|解除|解除(後日)|政府の緊急事態宣言は 5/○ に、愛知県独自の「愛知県緊急事態宣言」は 5/○ に解除されました。引き続き十分な感染予防に努めましょう。 ※リンクなし |
3|解除|解除|発出中|[5/○、政府は、愛知県の緊急事態宣言を解除しました。愛知県独自の「愛知県緊急事態宣言」は引き続き発出中です。](https://www.pref.aichi.jp/site/covid19-aichi/covid19-aichi.html) |
4|解除|対象※1|* ※2|[5/○、愛知県は、［特定警戒都道府県 ｜ 感染拡大注意都道府県 ｜ 感染観察都道府県］ に指定されました。※3]() ※1 https://github.com/code4nagoya/covid19/issues/461#issuecomment-628299114 のいずれかに該当する場合。 ※2 愛知県独自の発令があれば、それを足す。 ※3 リンク先は、政府の判断指標を示すサイトがあればそこが望ましい |

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takainou** [comment]
分類が増えるかもです。

> 提言案によると、流行状況に合わせ、〈１〉特定警戒都道府県〈２〉感染拡大注意都道府県〈３〉感染観察都道府県――に分ける。

https://www.yomiuri.co.jp/politics/20200514-OYT1T50018/

**Comment by amay077** [comment]
上表の 4 を変えてみました。
政府の発表が今日で、愛知県の動きは明日以降ですかねたぶん。

**Comment by amay077** [comment]
とりあえず、

- 政府の緊急事態宣言： 解除
- 政府の特定警戒地域： 解除
- 愛知県緊急事態宣言： 継続（月末まで）

ということになるようです（知事の会見動画中継より）。

**Comment by takainou** [comment]
愛知県は「感染観察都道府県」に当たるようですが、これを愛知県は、公式には用いないのかもしれません。解除のリリースを待つのかな。

> 緊急事態宣言が解除された39県については、新規の感染者数が少ない「感染観察都道府県」に当たるという見解を示しました。

https://www3.nhk.or.jp/news/html/20200514/k10012430601000.html
