### ISSUE TITLE
グラフ下部の注記のフォントサイズを統一する

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#477]
## 改善詳細 / Details of Improvement
- グラフ下部に注記していますが、フォントサイズが統一されていません
- 現状、モバイル経由のアクセスが多く、スクロール量を増やすのは好ましくないので、小さい方への統一が良いと考えます

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/82006462-d1fb5800-96a2-11ea-8d16-09354c598bfd.png)
![image](https://user-images.githubusercontent.com/63571899/82006471-d758a280-96a2-11ea-88be-dbd32f7d9982.png)

## 期待する見せ方・挙動 / Expected behavior
- グラフ下部の注記のフォントサイズを「市町村別感染状況」に合わせる形で統一する
- 対象のグラフは以下の通り
　「入院患者数」「検査実施人数・陽性率」「陽性患者数」「検査陽性者状況の推移」「検査実施件数」「重症者数」

**Comment by sinjikoro** [comment]
こちらやらせて頂けないでしょうか？

**Comment by amay077** [comment]
ぜひお願いします！
