### ISSUE TITLE
愛知県独自の緊急事態宣言が解除されたら、Topからその文言を消す

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#529]
## 改善詳細 / Details of Improvement
- 5/31 までとなっているので、基本的には 6/1 から削除
- が [愛知県独自の緊急事態宣言26日にも解除へ　大村知事が示す](https://news.yahoo.co.jp/articles/73308fe237c9c8fd87d260ca06eb74e11cc43b26) という会見が遭った模様なので、5/26 にも解除される可能性があるので、解除されたなら削除

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/82778222-bacf1e00-9e8b-11ea-9f6e-921810e5a3b2.png)

## 期待する見せ方・挙動 / Expected behavior
- 青枠部分をまるっと消す

**Comment by amay077** [comment]
解除されたっぽいです。

[愛知県緊急事態宣言の解除についての知事記者会見動画を配信しました - 愛知県](https://www.pref.aichi.jp/site/covid19-aichi/2020052502.html)

**Comment by hmatsu47** [comment]
対応します。
