### ISSUE TITLE
「男女年齢別感染状況」グラフの作成

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#562]
## 改善詳細 / Details of Improvement
- 男女年齢別に感染傾向を示し、かかりやすい人達(=感染率)を把握する為に、男女年齢別の情報掲載が必要と考えます。
- 感染者数でも傾向はつかめるが、感染率(10万人あたりの感染者数)の方が比率をより正しく把握できると考えます

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/83351308-c20b9580-a37d-11ea-9a21-75afb6436dbc.png)
![image](https://user-images.githubusercontent.com/63571899/83351316-cb94fd80-a37d-11ea-831d-ad4a5f978fe4.png)

## 期待する見せ方・挙動 / Expected behavior
- ボタン切替にて、[感染率]と[感染者数]を掲載する
- 比率をより正しく把握できる[感染率]をデフォルト表示とする
- 「市町村別感染者数」カラム地図の次に掲載する

**[感染者数]**
- 陽性患者の属性データより、年代・性別の欄で集計する
- 0歳と90代は、人口が少ないので、以下の通り合算する
　"0歳男性"/"0歳女性"は、"10歳未満男性"/"10歳未満女性"に合算
　"80代男性"&"90代男性"/"80代女性"&"90代女性"は、"80代以上男性"/"80代以上女性"に合算
- 以下の方は集計対象外とする
　年齢性別が公表されていない方
　居住地が県外(中国武漢市/兵庫県/東京都)の方
　再感染の方
- 人口ピラミッドの様に、左右に男女の棒グラフとする
- 最大人数によりグラフスケールが変わるが、大小を見誤らぬよう常に男女同じスケールとする
- 棒グラフの男女色は、ジェンダーなどに関するステレオタイプを助長するようなデザイン(例.男性：青、女性：赤)を避けてもらえれば、お任せする

**[感染率]**
- [感染者数]で求めた男女年齢別感染者数と、男女年齢別人口より、感染率を算出する
　　感染率 ＝ （ 感染者数 ÷ 人口 ) × 100,000
- 人口は、他グラフでも利用している、推計人口(2020年3月1日時点)を利用する
　( https://www.pref.aichi.jp/soshiki/toukei/jinko1new.html )
- [感染者数]で求めた男女年齢別感染者数を、男女別でも集計し、男女別全世代感染率を算出する
　[感染者数]側に男女別感染者数を掲載すると、男女別は人数が多く年齢別が小さくなるので、[感染率]にのみ掲載する
- グラフ形式、男女同スケール、男女色は[感染者数]と同様とする

**Comment by takainou** [comment]
新規陽性者一覧にて、名古屋市公表分が2022年1月18日より一覧からサマリ形式に変更となり、名古屋市から愛知県に新規陽性者一覧が提出されておらず、県HPの発生事例一覧PDFの名古屋市公表分には「年代・性別」が記載されなくなっています([covid19-aichi-tools Issue 99](https://github.com/code4nagoya/covid19-aichi-tools/issues/99)を参照)。
![image](https://user-images.githubusercontent.com/63571899/174928443-624d972a-123e-4b84-9c16-6f0ed38515cd.png)

これにより、名古屋市公表分(県全体の約3.5割)の2022年1月18日以降の「年代・性別」情報が欠けており、「男女年齢別感染状況」グラフは正しい状況を示す事が出来なくなっておりますので、本IssueはCloseでお願いします。

**Comment by amay077** [comment]
承知しました、close します。
