### ISSUE TITLE
「指標推移」グラフの作成

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#563]
## 改善詳細 / Details of Improvement
- 「判断指標と達成状況」 #455 で幅の都合で最新値の掲載のみとなり、推移が掲載できなかった
- 現在が、好転傾向なのか、悪化傾向なのか、把握する為、指標推移の折れ線グラフを掲載するのが良いと考える
- 名古屋市[「新型コロナウイルス感染症対策特設サイト」](https://nagoya-bousai.maps.arcgis.com/apps/Cascade/index.html?appid=04c0250edfe54ae4af7f1c8755d275b5)の「感染状況(指標ベース)」を参考にする

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/83352735-b2de1500-a388-11ea-829d-1a92941503ee.png)
![image](https://user-images.githubusercontent.com/63571899/83352902-cb026400-a389-11ea-8eef-ed994d102e39.png)

## 期待する見せ方・挙動 / Expected behavior
- 3+1指標(新規感染者数/陽性率/入院患者数+感染率)の注意ライン＝100として、日毎の折れ線グラフを表示する
　 注意ライン：新規感染者数(10人)、陽性率(5%)、入院患者数(150人)、感染率(0.5人)
- 注意ラインと危険ラインを引く
　 危険ライン：新規感染者数(20人=200)、陽性率(10%=200)、入院患者数(250人=167)
- 縦軸の目盛数値は掲載しない
- ツールチップに表示する値は、4指標の実際の値を表示する
　ツールチップは、どの項目を触っても、その日の全項目(4指標)の値を表示する
- 凡例は上部に設置する
- 下部にスライダーを設置、デフォルト期間は60データ(60日)とする
- 3指標の値が全て揃った最新日で判定し、パネル右上に判定(-/注意/危険)と時点情報を記載する
　注意：3指標の1つでも注意ラインを上回った場合
　危険：3指標の全てが危険ラインを上回った場合
- 「判断指標と達成状況」と同パネルとするか、新規パネルとするか、ボタン切替とするか、要検討である

**Comment by amay077** [comment]
>「判断指標と達成状況」と同パネルとするか、新規パネルとするか、ボタン切替とするか、要検討である

私は、大きなパネルを使って「指標推移」グラフを見せる必要は無いのではないか、という意見です。
以下、理由です（物言いが厳し目ですみません）。

1. 過去からの傾向は見たいが、良化・悪化・変化なし程度の大雑把なものを知ることができれば十分と考える（詳細な傾向を見たいなら 3. へ続く）
2. 過去の達成状況のためにパネルを1枚専有するのは望まない(それほど重要な情報ではないし 3. に続く)
3. 既存のチャートと重複する情報ならそちらを見てもらえばよい
4. 危険を示す水平線が２本あるのは、折れ線との関係を閲覧者が理解せねばならず、１枚のグラフに統一するメリットがあまり感じられない

グラフを「判断指標と達成状況」と同パネルに入れることが一番良いのですが、表示領域の狭さとの戦いになるので情報量をシンプルにする必要があり、その点でも2本の危険水平線の表現が厳しいと思われます。

なので、「指標推移」グラフ自体は作成せず、「判断指標と達成状況」パネル内に以下のような機能を追加してはどうかという提案をします。

■案１：前日・翌日に移動できるボタンを用意する

![image](https://user-images.githubusercontent.com/401369/83406757-4c213000-a44a-11ea-9ccc-51112cf5d32b.png)

表の最右列が、移動した日の状況値になります。
推移を俯瞰はできません（個別のチャートで俯瞰可能）が、各日の個別値にアクセスできます。

■案２：過去７日間の状況を簡易表示する

![image](https://user-images.githubusercontent.com/401369/83406814-69ee9500-a44a-11ea-93ce-761f34182104.png)

小さな表で、過去７日分の総合状況を表示します。
１週間分は推移が俯瞰できますが、過去日の値にはアクセスできません（個別のチャートでアクセスが可能）。


尚、実装のし易さでは、案１ が最も簡単であると思います。

**Comment by amay077** [comment]
議論の対象の指標自体の継続可能性が低まってきたので、現状で議論継続の意味も薄いと判断し、こちらの issue は Close します。
