### ISSUE TITLE
READMEにデータ更新方法を記載する

### ISSUE THREAD

**Issue by fussy113** [code4nagoya/covid19#59]
## 改善詳細 / Details of Improvement
- dockerでphpの環境立ち上げ、データ更新を可能にしました。
- ゆくゆくはgithub actionsとかで自動化したいが、一旦は手動更新になるので、方法をREADMEにまとめる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fussy113** [comment]
hackMDに記載
実際に確認してもらって、修正あれば修正してクローズとします。

**Comment by hajime-miyauchi** [comment]
@ctyo さんと昨日確認したんですが、そのままでは動かなくてその場でFIX入れたりしてたので一旦保留で。
元データのEXCELが書き換わっていて動かなかった可能性もあるかもです。

**Comment by fussy113** [comment]
マクロでjsonデータの更新の動きがあるため、一旦pending

**Comment by hajime-miyauchi** [comment]
READMEよりもWikiのほうが良いかなと思いました。
READMEがでかくなりすぎるのと、結構頻繁に変わりそうなので。
別Issue立てました。

https://github.com/code4nagoya/covid19/issues/117
