### ISSUE TITLE
SNS等のリンクを直す

### ISSUE THREAD

**Issue by fussy113** [code4nagoya/covid19#6]
## 起こっている問題 / The Problem
- SNSのリンクなどが東京都のままになっている

## スクリーンショット / Screenshot

![スクリーンショット 2020-03-10 19 51 37](https://user-images.githubusercontent.com/15154105/76305497-96da5280-6308-11ea-86e0-051f36032131.png)

## 期待する見せ方・挙動 / Expected Behavior
- spread sheetに書かれているURLに変更する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fussy113** [comment]
こちら対応しますー！

**Comment by takayashibagaki** [comment]
対応します！！！

**Comment by fussy113** [comment]
どのコンポーネントのどのリンクをどのように直すのかをリスト化します。

**Comment by YoshiokaMitsuyoshi** [comment]
１つだけ修正点っぽいところみつけました。これで合ってそうですか。。
すみません。GitHub初めてのへたれっす。（よしおか）
知事メッセージ
https://github.com/code4nagoya/covid19/blob/development/components/SideNavigation.vue
153行目
修正前：
          link: 'https://www.pref.aichi.jp/chiji/index.html'
修正後：
          link: 'https://www.pref.aichi.jp/chiji/message/index00.html'

**Comment by YoshiokaMitsuyoshi** [comment]
GitHubが良く分からなくて直せません。我ながらへたれです。ご迷惑かけてすみません。
facebookのリンク
https://github.com/code4nagoya/covid19/blob/development/components/SideNavigation.vue
57行目
修正前：
            href="https://www.facebook.com/tochokoho"
修正後：
            href="https://www.facebook.com/aichikoho"

**Comment by YoshiokaMitsuyoshi** [comment]
twitterのリンク
https://github.com/code4nagoya/covid19/blob/development/components/SideNavigation.vue
50行目
修正前：
            href="https://twitter.com/tokyo_bousai"
修正後：
            href="https://twitter.com/pref_aichi"

**Comment by YoshiokaMitsuyoshi** [comment]
LINEのリンク
https://github.com/code4nagoya/covid19/blob/development/components/SideNavigation.vue
43行目
修正前：
            href="https://line.me/R/ti/p/%40822sysfc"
修正後：
            href="http://line.naver.jp/ti/p/%40aichipref"

**Comment by fussy113** [comment]
@YoshiokaMitsuyoshi 
率先して確認いただき最高です！
伝えていただいたものを合わせて対応箇所シートにまとめますね！

**Comment by fussy113** [comment]
## 現時点の残対応

- TOPの「最新のお知らせ」に貼られているリンク
  - 現時点では一旦決して良さそう
- 「お子様をお持ちの皆様へ」に貼られているリンク
  - [【参考】感染症予防のための正しい手洗い方法（動画）](https://tokyodouga.jp/lViN9C_BS-0.html)
    - このままでは良さそうだけどコミュニティとしてどうすべきかは判断必要
- 「当サイトについて」に貼られているリンク
  - [東京都オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/)
    - [ここに変える?](http://linkdata.org/work/rdf1s8257i?fbclid=IwAR1RHz-PzjW9WJWXjBsgGabUa45d5QOO1KYrf3PzzMxjQXXBRgbnlLZiNX4)

**Comment by fussy113** [comment]
> TOPの「最新のお知らせ」に貼られているリンク
#31

> 「当サイトについて」に貼られているリンク
#30 

こちらで対応するのでこのissueはクローズします。
