### ISSUE TITLE
検査陽性者の状況グラフで検査実施人数が枠からはみ出している

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#602]
## 起こっている問題 / The Problem
- 検査陽性者の状況グラフで検査実施人数が枠外にはみ出ている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/36749946/84014838-e850b700-a9b5-11ea-9c63-ba61ce912a5a.png)

## 期待する見せ方・挙動 / Expected Behavior
- フォントサイズを調整するか左側のインデントを減らして枠内に収める
- #368 でもよい

**Comment by amay077** [comment]
これは #368 で対応したいですね。

**Comment by amay077** [comment]
#368 で解決されたので close します。
