### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」を復活

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#67]
## 改善詳細 / Details of Improvement
- #40 で一旦削除しましたが、図が見やすいので復活させたいです

## 期待する見せ方・挙動 / Expected behavior

[東京都のオリジナル版](https://stopcovid19.metro.tokyo.lg.jp/flow) の以下 5箇所 の表記とリンクを修正すれば ok と思います。

![image](https://user-images.githubusercontent.com/401369/76477181-dbb8d300-6447-11ea-996e-e4552cbd4ee2.png)

![image](https://user-images.githubusercontent.com/401369/76477239-0b67db00-6448-11ea-9504-67058c665ede.png)

**Comment by hajime-miyauchi** [comment]
これはぜひ復活したいですね。
@amay077 さんわかりやすく変更点まとめていただきありがとうございます！
ところで、この変更箇所って何のソフト(OR サービス)でつけてるんですか？

**Comment by amay077** [comment]
こちら着手してみてます。

**Comment by amay077** [comment]
この図は skitch https://evernote.com/intl/jp/products/skitch というツールで作成しましたが、これはすでに開発終了になっています。
代替としては MonoSnap https://www.pojihiguma.com/entry/MonoSnap というツールが有名です。

**Comment by hajime-miyauchi** [comment]
あ、これPCでは052-XXX-XXXって表示されるけど、スマホで表示したときには03-XXXX-XXXXが表示されてたので、確認頂くときはPC/スマホで確認頂けると助かります。

**Comment by amay077** [comment]
了解です :+1:

**Comment by amay077** [comment]
![image](https://user-images.githubusercontent.com/401369/76704876-6a1aa680-671f-11ea-8206-2d386e74e86f.png)

現状、こんな感じで進めています。
リンク先は以下の通りです。

1. https://www.pref.aichi.jp/soshiki/kenkotaisaku/novel-coronavirus.html#kikokusha
2. https://www.meti.go.jp/press/2019/03/20200311004/20200311004.html
3. https://medpeer.co.jp/press/7471.html
4. https://linecorp.com/ja/pr/news/ja/2020/3119

**Comment by amay077** [comment]
スマホ用画面修正案です。キャプチャがとても長くなってしまいましたが、切るのが面倒なのでそのまま貼り付けます。
内容は PC 版と同じ、しかしモバイル版は画像ファイルが使われており色の変更が面倒なので、ちょっとカッコ悪いですがとりあえずそのままでいいかなと思っています。

![mobile](https://user-images.githubusercontent.com/401369/76753721-5a08d280-67c4-11ea-8ad2-48ded98dc632.png)
