### ISSUE TITLE
CONTRIBUTING.md　の開発者サイトリンク

### ISSUE THREAD

**Issue by yamuun** [code4nagoya/covid19#68]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)

CONTRIBUTING.mdの
開発サイト https://dev-covid19-tokyo.netlify.com/

が東京都の物になっております

https://github.com/code4nagoya/covid19/blob/development/.github/CONTRIBUTING.md

https://dev-covid19-aichi.netlify.com/ 
が愛知の開発サーバーでしょうか？

**Comment by hajime-miyauchi** [comment]
Issue登録ありがとうございます！

https://dev-covid19-aichi.netlify.com/
が愛知の開発サーバーです！
(これ誰かが直してくれたけど、私が間違えて上書きしちゃった可能性が高い。ごめんなさい。)

**Comment by hajime-miyauchi** [comment]
あと、開発責任者が関さんになってるから、これも変更が必要ですね。

「開発責任者をしています、関です。」を丸ごと削除でよさそう。

**Comment by upura** [comment]
翻訳版（英語・中国語など）も修正した方が良い気はしています。
