### ISSUE TITLE
Code for Aichiのサイトへのリンクの追加

### ISSUE THREAD

**Issue by ctyo** [code4nagoya/covid19#71]
## 改善詳細 / Details of Improvement
 - 自治体サイトではないですが、有用なサイトへのリンクとして以下を追加しませんか？
 - https://code4aichi.github.io/corona/

## 期待する見せ方・挙動 / Expected behavior
- こちらのページに追加
 - https://stopcovid19.code4.nagoya/government

**Comment by HidekazuSuzuki** [comment]
Code for Aichiが公開していた「愛知新型コロナウイルス感染情報」は本サイトの公開により，閉鎖することが決まったようです（既に閉鎖）．

**Comment by amay077** [comment]
おっとそうなのですね。
「愛知新型コロナウイルス感染情報」にあった「感染状況の図」は分かりやすい図だったので、こちらで引き続き公開できればよいかもですが、メンテが大変（ツールが使える人が居ない）ですかね。

https://twitter.com/amay077/status/1236885897112481793

**Comment by hajime-miyauchi** [comment]
@ctyo さん、これ私も昨日布団の中で「そういえば！」と思い出し、起きたらIssue立てようと思ってたとこでした。ありがとうございます。
が、閉鎖されてしまったのですね。公開されている情報も多かったし、こちらはグラフがメインで、あちらはグラフに限らず様々な情報が集約されるという別の方向性だったように思うので残念。一旦このIssueはCloseしますね。

**Comment by hajime-miyauchi** [comment]
@amay077 さん
たしかにその図わかりやすいですね！
ただ、このサイトではなくて別サイトでもいいのかなと思いました。
ちなみにこれ北海道のIssueでもあがっています。
https://github.com/codeforsapporo/covid19/issues/230

私の個人的な意見としてはそのIssueのkoukitaさんやtk-suzukiさんの意見に近いです。
https://github.com/codeforsapporo/covid19/issues/230#issuecomment-598127214
https://github.com/codeforsapporo/covid19/issues/230#issuecomment-598136801
