### ISSUE TITLE
愛知県HPの検査件数表に「抗原検査」が追加されたことによる対応

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#713]
## 改善詳細 / Details of Improvement
[愛知県HP の 3．愛知県内の検査件数](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html) に「抗原検査」の列が追加されました。

それにより以下の事象の影響が発生します。

1. [優先度:高]表形式が発生したことにより(?)、定期自動スクレイピングが失敗している ※1
3. [優先度:低]「検査実施件数」グラフに、抗原検査の検査件数も表現する（「件数」としてなら、PCRと抗原検査の積み上げ防棒グラフでよい？） ※2

元々、検査件数表の情報は「件数」しか使っていませんでした（陽性者数は未使用）。そのため他の影響は無いと思います。

### ※1

https://github.com/code4nagoya/covid19/pull/712

### ※2

> 「抗原検査」ですね。「PCR検査」を代替するもので、短時間で判定出来ますが、感度が劣る(一定のウイルス量が必要)ようです。
> 「抗原検査」で陽性なら感染確定とし、陰性となっても症状から感染を疑う場合「PCR検査」を引き続き行うようです。
> https://news.yahoo.co.jp/byline/kutsunasatoshi/20200517-00178720/
> 「検査件数」は、情報として特に分けて見る必要は無いと考えます。重要なのは「検査人数」です。前述の例のように「抗原検査」→「PCR検査」とした場合、「検査人数」は1人なので、『愛知県は日毎の「検査人数」を公表して下さい』です。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/86869969-7d101700-c112-11ea-890b-808459091f43.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
> 1. [優先度:高]表形式が発生したことにより(?)、定期自動スクレイピングが失敗している

は、検査件数のスクレイピングをコメントアウトしてみた。

https://github.com/code4nagoya/covid19-aichi-tools/commit/3da5bbb9c8f68afed0fb0db3756305f828a15e61

**Comment by takainou** [comment]
> 2. [優先度:低]「検査実施件数」グラフに、抗原検査の検査件数も表現する（「件数」としてなら、PCRと抗原検査の積み上げ棒グラフでよい？） ※2

県民にとっては、PCR検査か抗原検査かは特に関係無く、総検査実施件数と推移が把握出来れば十分なので、積み上げせず、合算値の棒グラフでも良いと考えます。よって、開発が容易な方で対応頂ければ良いと考えます。

なお、東京都の検査実施件数グラフでは、合算になってます(既に他の区分で積み上げているからかもしれませんが)。
![A63A9F08-310C-4115-9A16-BE3F1776BCCC](https://user-images.githubusercontent.com/63571899/87050693-92339580-c239-11ea-921b-c2073eb8e6de.jpeg)

ちなみに、東京都はモニタリング新項目対応されました(7/9)。その際「モニタリング項目(4)検査の陽性率・検査人数」グラフでは、PCR検査と抗原検査を分けてます。こちらこそ合算が相応しいのに、複雑で分かりにくい…。

**Comment by ozo360** [comment]
とどのつまりinspections_summary.csvをどういう形に変更すればよいでしょうか？
スクレイピング自体は可能なのでデータ定義を提示していただけると大変助かります。

**Comment by amay077** [comment]
> inspections_summary.csvをどういう形に変更すればよいでしょうか？

以下のような感じで、増えた 抗原検査 の３列を付与するようにしておくと、今後のグラフ化などで活用できると思います。
（PCR検査の方の列名は現状との互換性のために変更しない方が良さそうです。）

## 現在

検査日 | 件数（件） | 陽性者数（人） | 率（％） | 備考 | 合算
-- | -- | -- | -- | -- | --
2020/07/06 | 130 | 1 | 0.8 | 7月6日（月曜日）

## 抗原検査対応

検査日 | 件数（件） | 陽性者数（人） | 率（％） |  抗原検査_件数（件） | 抗原検査_陽性者数（人） | 抗原検査_率（％） | 備考 | 合算
-- | -- | -- | -- | -- | -- | -- | -- | --
2020/07/06 | 130 | 1 | 0.8 | 6 | 1 | 16.7 | 7月6日（月曜日）

**Comment by amay077** [comment]
完了していると思われるので close します
