### ISSUE TITLE
「最新のお知らせ」の情報ソース追加及び自動更新

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#73]
## 改善詳細 / Details of Improvement
- #31 の続き
- 愛知県発表以外に（感染者情報がある）市区町村の情報も載せたい
- できれば自動的に情報を収集して更新したい

## 期待する見せ方・挙動 / Expected behavior

情報ソースとしては現在(3/12)のところ、以下が挙げられます（#31 では 愛知県のみ）。

- 愛知県 https://www.pref.aichi.jp/soshiki/list1-1.html
- 名古屋市 http://www.city.nagoya.jp/kenkofukushi/page/0000124556.html
- 半田市 https://www.city.handa.lg.jp/kinkyu/index.html
- 蒲郡市 https://www.city.gamagori.lg.jp/
- 岡崎市 https://www.city.okazaki.lg.jp/

[FYI]
tokyo 版では、お知らせページを作るissueも上がっているようです
tokyo-metropolitan-gov#1082

**Comment by fussy113** [comment]
お知らせの量かなり多いので、現在のコンポーネントだと、縦にめちゃくちゃ長くなりそうですね。
お知らせのコンポーネントをスクロールする形にするなど、デザインに関しても考慮する必要ありそうです！

**Comment by amay077** [comment]
そうですね、トップページに載せるのは現状ママで最新の２～３件、それ以外および過去のものは、 https://github.com/tokyo-metropolitan-gov/covid19/issues/1082 と同じく「お知らせページ」のような別ページを用意するのがよいかな、と思います。

**Comment by ctyo** [comment]
issueにかぶせで申し訳ありませんが、
現状のデータ更新の手間を、でできる範囲で楽にできないか、という観点の提案です。


現在、excelで作成->phpでjsonを吐き出し->masterマージという形で公開しています。
以下の形でアプリケーションに組み込めないでしょうか？

お試しでマクロでJSONを書き出すところまで作ってみました。課題等がなければどなたかアプリケーションへの反映部分を実装していただけないでしょうか？（火曜以降なら私もさわる時間つくれそう,...)

----

県発表のPDFを [GoogleShread Sheet](https://docs.google.com/spreadsheets/d/1oERqNAfnbFnXjKc0j82lechlrXWBHQuG1QU8JFtHnRU/edit?usp=sharing
)で追記
↓
[マクロでjsonを書き出し](https://script.google.com/macros/s/AKfycbw4_eC2o3BlL2HMUXZbsCfWu1pP4rzYb1b0S08DpW-YwtFP2fN7/exec)（自動）
↓
アプリケーション側で読み込んでいい感じで処理に組み込み
 - 処理はここのあたり : https://github.com/code4nagoya/covid19/blob/development/pages/index.vue#L105-L131

**Comment by ctyo** [comment]
↑を書いたあと確認したのですが、
マクロでJSON書き出しはログイン必須、回数制限がついているのですね。
JSONをコピペしてgithubに貼り付けてデプロイでも良いかもしれません。

**Comment by billhung** [comment]
@ctyo さん いいアイデアだと思います。
少し調べた。
手動でExcel更新>phpでJSON出力>/data/data.jsonを更新する  より
手動[Google Spreadsheet](https://docs.google.com/spreadsheets/d/1oERqNAfnbFnXjKc0j82lechlrXWBHQuG1QU8JFtHnRU/edit?usp=sharing)更新>マクロscriptでJSON出力>GitHubのdata/data.jsonにコピペの方が楽
ーーーーーーーーーーーーーーーーーーーー
上記の[MACRO](https://script.google.com/macros/s/AKfycbw4_eC2o3BlL2HMUXZbsCfWu1pP4rzYb1b0S08DpW-YwtFP2fN7/exec)、現在の出力したのは
```
  {
    "": "",
    "Sun Mar 15 2020 16:00:00 GMT+0900 (Japan Standard Time)": "名古屋市発表"
  },
```
data/data.jsonと比べて、こんなフォーマットが必要ですね。
```
            {
                "No": 3,
                "発表日": "2020-02-14T08:00:00.000Z",
                "年代・性別": "60代男性",
                "国籍": "日本",
                "住居地": "名古屋市",
                "接触状況": null,
                "": null,
                "備考": "名古屋市発表",
                "date": "2020-02-14",
                "w": 5,
                "short_date": "02\/14"
            },
```

今のマクロの処理を共有して一緒に修正しましょうか？
こちらも調べている最中です、[こんなように](http://blog.pamelafox.org/2013/06/exporting-google-spreadsheet-as-json.html)やってみます。同じく修正がまだ必要です。

**Comment by ctyo** [comment]
@billhung 確認ありがとうございます。
マクロの修正をお願いします。みんなが簡単に更新でいるようになることに価値を感じます。

以下は自由に修正していただいてOKですmm
 - 
https://docs.google.com/spreadsheets/d/1oERqNAfnbFnXjKc0j82lechlrXWBHQuG1QU8JFtHnRU/edit#gid=1588368354

**Comment by ctyo** [comment]
紹介していただいたScriptの追加はできました 🎉 
<img width="910" alt="スクリーンショット 2020-03-18 12 05 20" src="https://user-images.githubusercontent.com/1971086/76921224-d4df0400-6910-11ea-97b4-484046f74f3a.png">

**Comment by billhung** [comment]
まだマクロの問題を判明中ですが、こんな感じでデバッグできそうです。
![20200318 gogole app script debug](https://user-images.githubusercontent.com/2110915/76930182-432fc080-6929-11ea-8258-039eb756a808.jpg)

**Comment by billhung** [comment]
@ctyo 
GOOD NEWS!
行１４１を
　　var objects = getObjects_(dataRange.getValues(), normalizeHeaders_(headers));
から
　　var objects = getObjects_(dataRange.getValues(), headers);
に変更するだけで、完成なデータに少し近づいてきた。
![20200318 json export](https://user-images.githubusercontent.com/2110915/76953859-c1548d00-6952-11ea-9a30-31252ab528f0.JPG)

**Comment by billhung** [comment]
Googleのシート
https://docs.google.com/spreadsheets/d/12qStuXjsI8GE8qI1mLPLV--6TQcxAMPDu3-k9RCHN1k/edit#gid=0
修正したGoogle App Script
https://stopcovid19aichi.slack.com/files/U01006985GD/FVCCUMG57/exportjson.gs

使い方は
１．Google Spreadsheet>Tools>"Script Editor"、そしてこのscriptをコピペだけ
２．そのあと、Google Spreadsheetの一番右上の「Export JSON出力」すれば
３．最後はここにあるdata.jsonにコピペ
https://github.com/code4nagoya/covid19/tree/development/data
Hope this helps.
Bill


![image](https://user-images.githubusercontent.com/2110915/76959888-d387f880-695d-11ea-8397-11204b1b8884.png)

**Comment by hajime-miyauchi** [comment]
流れを読めてなくて申し訳ないのですが、データの自動更新について最終的には下記の完全自動化の動作がゴールかなと思ってます。

1. 愛知県のPDFデータが更新される
2. 定期的に愛知県のPDFデータをスクレイピングし、更新があれば自動でdata.jsonが更新される
3. サイトのグラフが自動で書き換わる

過渡期としては下記で、現状進んでいるのはこちらの準自動化だと認識してます。(間違ってたらごめんなさい)

1. 愛知県のPDFデータが更新される
2. 定期的に人間が目視で愛知県のPDFデータを確認
3. GoogleスプレッドシートにPDFデータを転記
4. data.jsonが書き換わる？
5. ちょっとこのへんわからないけど、たぶん手動でコミット、プッシュとかそんな感じ？

完全自動化の前に準自動化が必要ではあるかもしれないんですが、平行して完全自動化も考えたいと思います。
(もし、完全自動化が早期に実現できそうなら、完全自動化を優先したい)

@codeforalone さんのコードや、北海道の自動化が参考になるのではと思っています。

codeforaloneさんのコード
https://github.com/codeforalone/covid19-scrapy

COVID-19Hokkaidoデータ編③完全自動化（バリデーション・エラー検知）
https://qiita.com/Kanahiro/items/782cb6d5497d3c3704ec

兵庫県のデータ取得
https://qiita.com/y-chan/items/87919fd712d1560c5e95

**Comment by Miura55** [comment]
> 流れを読めてなくて申し訳ないのですが、データの自動更新について最終的には下記の完全自動化の動作がゴールかなと思ってます。
> 
> 1. 愛知県のPDFデータが更新される
> 2. 定期的に愛知県のPDFデータをスクレイピングし、更新があれば自動でdata.jsonが更新される
> 3. サイトのグラフが自動で書き換わる
> 
> 過渡期としては下記で、現状進んでいるのはこちらの準自動化だと認識してます。(間違ってたらごめんなさい)
> 
> 1. 愛知県のPDFデータが更新される
> 2. 定期的に人間が目視で愛知県のPDFデータを確認
> 3. GoogleスプレッドシートにPDFデータを転記
> 4. data.jsonが書き換わる？
> 5. ちょっとこのへんわからないけど、たぶん手動でコミット、プッシュとかそんな感じ？
> 
> 完全自動化の前に準自動化が必要ではあるかもしれないんですが、平行して完全自動化も考えたいと思います。
> (もし、完全自動化が早期に実現できそうなら、完全自動化を優先したい)
> 
> @codeforalone さんのコードや、北海道の自動化が参考になるのではと思っています。
> 
> codeforaloneさんのコード
> https://github.com/codeforalone/covid19-scrapy
> 
> COVID-19Hokkaidoデータ編③完全自動化（バリデーション・エラー検知）
> https://qiita.com/Kanahiro/items/782cb6d5497d3c3704ec
> 
> 兵庫県のデータ取得
> https://qiita.com/y-chan/items/87919fd712d1560c5e95

これですが、ひとまず自分の方で試します。まずは愛知県のサイトのPDFからスクレイピングする部分を実装します

**Comment by hajime-miyauchi** [comment]
ポンチ絵書いてみました。多分必要になるのはこんなところ(黄色部分)かと。
一つのプログラム内で完結することもできるし、さらに分割することもできると思いますが、このくらいの粒度で分割されていると変化に対応しやすそう。

![スクリーンショット 2020-03-21 22 26 50](https://user-images.githubusercontent.com/749758/77227359-2b736900-6bc3-11ea-832e-de208048ece8.png)

**Comment by hajime-miyauchi** [comment]
「東京都 新型コロナ対策サイト 地域展開 情報共有」にも各地域のスクレイピングの記事が紹介されてました。

https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view

**Comment by Miura55** [comment]
とりあえず県内の発生事例をCSVに変換しました。こんな感じでOKですか？

![コメント 2020-03-22 070102](https://user-images.githubusercontent.com/24681988/77237367-f559d780-6c0a-11ea-83f9-bbf84f3f0b77.png)

**Comment by hajime-miyauchi** [comment]
おおーー！素晴らしい！！そんな感じです。

**Comment by hajime-miyauchi** [comment]
@Miura55 CSVからJSONを生成するコードを作りました。もし可能であれば、出力するCSVの書式を合わせられると連携しやすくて良いかもです。

https://github.com/hajime-miyauchi/covid19-aichi-tools

**Comment by Miura55** [comment]
ありがとうございます。今から修正かけます

**Comment by Miura55** [comment]
@hajime-miyauchi ちょっと相談ですが、県内の発生事例はPDFからJSONに変換できましたけど、検査陽性者に関しては画像データしかなく、文字を取るのが難しいのでこれに関しては従来どおり手作業で抜き出して、JSONに追加する形でやろうと思いますが、いかがでしょうか？
![コメント 2020-03-25 224241](https://user-images.githubusercontent.com/24681988/77563716-fb9acd00-6f04-11ea-97f3-487343a56484.png)

**Comment by Miura55** [comment]
ちなみに今自動更新でできたJSONがこんな感じです！
https://github.com/Miura55/convid-19-scrape/blob/up-loadcsv/data.json

**Comment by hajime-miyauchi** [comment]
@Miura55 その画像については現状目視確認して、Googleスプレッドシートに反映するとあとはコマンド実行すればdata.jsonができあがるところまではできています。(下記参照)

https://docs.google.com/presentation/d/1zImnNFo_XebMO6fmuUiPPALPw2NZGg57TXWmKnkQ2Lg/edit#slide=id.g825c5544ea_0_5

可能であればPyOCRも試してみたいなとは思ってました。数字だけなので制度はそんなに悪くないと思うのですが、やってみないとなんともというところですね。

https://qiita.com/henjiganai/items/7a5e871f652b32b41a18

**Comment by Miura55** [comment]
実はPyORCを試したんですが、画像の問題で思ってたよりも認識率が悪いですね。僕のGithubにはORCのコードを挙げていますが、出来る限り文字が認識できるように画像を加工しても全然です。
https://github.com/Miura55/convid-19-scrape/blob/master/OCR.py

実際に上記のコードで認識した結果です。
https://github.com/Miura55/convid-19-scrape/blob/master/ocr-test-out.txt

**Comment by hajime-miyauchi** [comment]
@Miura55 試してたんですね！早い！

その精度だとちょっとしんどいですね。取り急ぎ私のコードでGoogle Spreadシートからの読み込みには対応できてるので、そのデータについては自動化は後回しですね。

**Comment by Miura55** [comment]
ひとまず、画像しかないところはスプレッドシートを読み込んで後はスクレイプでjsonを生成してみました。これでいいですよね？
https://github.com/Miura55/convid-19-scrape/blob/master/data/data.json

**Comment by hajime-miyauchi** [comment]
@Miura55 diffとってないのでパッと見ですが、patients_summaryの日付が歯抜けになってる気がします。

**Comment by Miura55** [comment]
そうですか？僕は宮内さんの作ってたjsonを参考にして作成しています

**Comment by Miura55** [comment]
あっ分かりました。日付は全てピックアップされてるはずですが、データの並びが日付順になってませんね。今出先なので帰ったら修正します

**Comment by hajime-miyauchi** [comment]
順番が不定になっているようなのでちゃんと確認できてないのですが。もしかしたら順番が不定なだけで歯抜けになってないかもしれません。あとで確認してみます。

![image](https://user-images.githubusercontent.com/749758/77630078-d8683000-6f8d-11ea-87ad-62c4d7c84709.png)

現在のdata.jsonは日付順になっているので、Pythonの実行環境にもよるかもしれませんね。

![image](https://user-images.githubusercontent.com/749758/77630212-fe8dd000-6f8d-11ea-8c45-9c476df44237.png)

**Comment by Miura55** [comment]
標準ライブラリでやればこういうことが無いと思いますが、僕のはデータ整形にpandas使っているので変換中に並びが崩れてしまったかもしれませんね

**Comment by hajime-miyauchi** [comment]
あ、あと、小計0の日も多分グラフ表示に必要なんです...

**Comment by hajime-miyauchi** [comment]
なので、patientsを単純に集計するだけだと0の日が抜けちゃう。

**Comment by Miura55** [comment]
そういえばそうですね、0は完全に無視してましたね。それもこみでコード直しますね

**Comment by Miura55** [comment]
直したら今日の分のデータがjsonで出来てるのでプルリク出せそうです

**Comment by hajime-miyauchi** [comment]
https://github.com/code4nagoya/covid19/pull/143

今日の分こちらのプルリクも上がってるのでご参照下さいー

**Comment by Miura55** [comment]
日付もソートさせてだいぶ見やすくなりました！
https://github.com/Miura55/convid-19-scrape/blob/master/data/data.json

![コメント 2020-03-26 235935](https://user-images.githubusercontent.com/24681988/77661363-e2a22280-6fbd-11ea-86e1-e40025167204.png)

**Comment by hajime-miyauchi** [comment]
@Miura55 可能であればDIFFでの確認をお願いしますー。

**Comment by Miura55** [comment]
左がツールを使って取り出したデータで、右がdevelopmentブランチからとってきたデータですー。これ、右側にはkeyもvalueも空文字列のデータがありますけどこれっていります？
あと、数字がint型になっているものは文字列に直したほうがいいですか？

![コメント 2020-03-27 020849](https://user-images.githubusercontent.com/24681988/77675185-f0f93a00-6fcf-11ea-9330-5f49c3f0ee7f.png)

**Comment by Miura55** [comment]
@hajime-miyauchi これでいかがですかー？
![コメント 2020-03-27 214234](https://user-images.githubusercontent.com/24681988/77757184-163f8400-7074-11ea-8241-55a8095132dd.png)

**Comment by hajime-miyauchi** [comment]
jsondiffというツールでもDIFF取ってみましたが、良さそうです！
http://www.jsondiff.com/

バックデートして接触状況が更新されている箇所が何箇所かわかりますね！
(左が @Miura55 さんのツールで出力したJSON、右が現在のJSON)

![スクリーンショット 2020-03-27 23 02 45](https://user-images.githubusercontent.com/749758/77763926-2c067680-707f-11ea-8886-977a3ddf2169.png)

@Miura55 さんのツールのほうに移行するか、ツールをマージするかどうするのが良いでしょう？

**Comment by hajime-miyauchi** [comment]
私のツールは自動化までのつなぎなのでまるっと捨てても大丈夫です！

**Comment by Miura55** [comment]
@hajime-miyauchi `僕のツールに移行していいかもです！ちなみに今は[このレポジトリ](https://github.com/Miura55/convid-19-scrape)の`up-loadcsv`ブランチに3時間おきにデータが更新されるので、このブランチをクローンさせてデータをcovid19のレポジトリにコピー→プルリクという流れで更新するイメージです。
具体的にはこんな感じです！
https://github.com/Miura55/convid-19-scrape/blob/master/README.md

**Comment by hajime-miyauchi** [comment]
それでいきましょう！一度プルリク出してみてください！

**Comment by hajime-miyauchi** [comment]
https://github.com/code4nagoya/covid19-scrape

codd4nagoyaにもリポジトリ用意しました。 @Miura55 さんにAdmin権限つけたので、もしよければこちらに移行してもらえると助かりますー。

**Comment by Miura55** [comment]
プルリク出してみたので、ご確認お願いしますー！

**Comment by Miura55** [comment]
> https://github.com/code4nagoya/covid19-scrape
> 
> codd4nagoyaにもリポジトリ用意しました。 @Miura55 さんにAdmin権限つけたので、もしよければこちらに移行してもらえると助かりますー。

こちらのコード移行したのでよろしくです！

**Comment by imabari** [comment]
PDFからCSV変換についてcamelot-pyを使うとdataframeに変換できます。
以下サンプルです。

愛知県の感染状況のPDFデータをCSVに変換
https://imabari.hateblo.jp/entry/2020/03/30/132758

**Comment by Miura55** [comment]
ありがとうございます。tabulaよりも良さそうですね。試してみます

**Comment by imabari** [comment]
兵庫県のですがjsonデータを作成しています

ご参考になれば
https://github.com/imabari/hyougo/blob/master/hyougo_json.ipynb

日付の0補完も.asfreq("D", fill_value=0)の１行でできます。
df_pts = (df_kanja["確認日"].value_counts().sort_index().asfreq("D", fill_value=0).reset_index()

**Comment by Miura55** [comment]
@imabari ありがとうございます。camelot-pyでCSV変換できました。途中でデータが結合される問題も解消しました。

**Comment by amay077** [comment]
こちらは、

> 愛知県発表以外に（感染者情報がある）市区町村の情報も載せたい
> できれば自動的に情報を収集して更新したい

という当初の目的は、情報収集の仕組みが難しいため却下となりました。
この issue の役割は終わったので close します。
