### ISSUE TITLE
愛知県HP「検査陽性者の状況」の項目[軽症・中等症]が[軽症・無症状]と[中等症]に分けられた事への対応

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#778]
## 改善詳細 / Details of Improvement
- 愛知県HP「検査陽性者の状況」の項目にて、[入院中]の内数として[軽症・中等症]と[重症]が有ったが、[軽症・中等症]が[軽症・無症状]と[中等症]に分けられた
- 7月中旬以降の第2波では、若年層中心に感染が広がっており、現時点では陽性者公表時の[中等症]と[重症]の比率は少ないが、陽性者公表時の比率が増えたり、その後に症状が[無症状]→[軽症]→[中等症]→[重症]と進行し[中等症][重症]が増えると、死亡者が増える可能性が高まり、医療機関の負荷も増えるので、[軽症・中等症]を[軽症・無症状]と[中等症]に分けて緻密に管理する事になったと考える
- 当サイトでも県の意図を汲み、追従対応する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/88456590-a0c8b080-ceb9-11ea-9536-967fd1509bdb.png)

## 期待する見せ方・挙動 / Expected behavior
**「main_summary」スプレッドシート**
- E列[軽症中等症]とF列[重症]の間に、F列[軽症無症状]、G列[中等症]と2列追加する
→『E列[軽症中等症]、F列[軽症無症状]、G列[中等症]、H列[重症]』となる

**「検査陽性者の状況」サマリ表**
- [入院中]の内数にて、[軽症・中等症]を削除して、[軽症・無症状]、[中等症]を追加する
→[入院中]の内数は、上から『[軽症・無症状]、[中等症]、[重症]』となる

**「検査陽性者状況の推移」積み上げ棒グラフ**
- 過去の[軽症中等症]はそのまま残し、本件対応後から[軽症無症状]と[中等症]に分割する
- 積み上げ順は、下から『[施設入所]、[軽症無症状]、[中等症]、[軽症中等症]、[転院]』とする

**Comment by hmatsu47** [comment]
「検査陽性者の状況」サマリ表の対応を行います。

**Comment by amay077** [comment]
ありがとうございます。サマリ表の対応は、

軽症・中等症 が空でない → これまで通り [軽症・中等症] のみを表示
軽症・中等症 が空 → [軽症・中等症]を削除して、[軽症・無症状]、[中等症]を追加

としておくと、汎用性があってよいと思います。

**Comment by hmatsu47** [comment]
いま、テストで、

 - 要素に対して required: false
 - 関連 li タグの表示・非表示を v-if で制御

という形で直してみました。

**Comment by amay077** [comment]
ひととおり対応完了したので close します。
