### ISSUE TITLE
「検査陽性者状況の推移」の「退院数」の数値がおかしい

### ISSUE THREAD

**Issue by hmatsu47** [code4nagoya/covid19#787]
## 起こっている問題 / The Problem
- 7/26 の数値で「511 人」のはずのところ、「2 人」（重症者数？）が表示されている
- おそらく #781 の対応によるもの（Pull request のスクリーンショットにも「2 人」が表示されている）
- 前日比も「0 人」になっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/35142774/88501534-bac3d980-d006-11ea-8b1d-67a90d3acc25.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しい退院数（および前日比）を表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトをそのまま表示する

## 動作環境・ブラウザ / Environment
- Windows / Android
- Chrome

※確認した環境

**Comment by hmatsu47** [comment]
- [MainSummaryChart.vue](https://github.com/amay077/covid19-1/blob/f5a9db0eebdfb7eba0d97f5bd4eaff5e049f664b/components/MainSummaryChart.vue)

の 90 行目、

`    const dataset = this.chartData.datasets[1]`

の `[1]` が「重症」のデータを指してしまっているのではないかと思います…。

**Comment by hmatsu47** [comment]
家に帰ってきたので確認して対応します。

**Comment by amay077** [comment]
お願いしますー。原因はご指摘の箇所で間違い無いと思います。
