### ISSUE TITLE
愛知県の指標変更に伴う対応

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#793]
## 改善詳細 / Details of Improvement
- 7月27日の第2回愛知県新型コロナウイルス感染症検証委員会にて、指標の変更が提示されたので対応する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/88555635-0310e500-d063-11ea-8f2d-b4d998de8c21.png)

## 期待する見せ方・挙動 / Expected behavior
**判断指標と達成状況(最新)パネル**
- 従来の「警戒領域」を「警戒」に、「危険領域」を「厳重警戒」に名称変更
- 「厳重警戒」の右に「危険」列を追加し、各指標の値を掲載
- 「○/○の状況」列は常に色付け
　警戒未満：緑
　警戒以上、厳重警戒未満：黄
　厳重警戒以上、危険未満：橙
　危険以上：赤
- 「感染率」を「重症者数」に変更
- 右上の全体判定を変更、「重症者数」を除く3指標で判定
　全て危険：危険
　１つでも厳重警戒以上：厳重警戒
　１つでも警戒以上：警戒
　上記以外：なし
- 注記に「重症者数」の記載を追加、「感染率」の記載を削除

**判断指標と達成状況(推移)グラフ**
- 従来の「警戒領域」を「警戒」に、「危険領域」を「厳重警戒」に名称変更
- 「危険」ラインを追加
- 傾きは途中で変化させ、ラインを統一
- 「重症者数」を追加、傾きは途中で2回変化、「感染率」は削除
- 注記に「重症者数」の記載を追加、「感染率」の記載を削除

**「重症者数」グラフ**
- 「入院患者数」グラフと同様に「過去7日間の平均」を追加
- 注記に「過去7日間の平均は、重症者数の後方7日移動平均値です」と追記

**グラフ順序変更**
- 指標の並びに合わせる為、「重症者数」グラフを「入院患者数」グラフの後ろへ移動

**Comment by hmatsu47** [comment]
「重症者数」グラフと表示順序について対応します。

**Comment by takainou** [comment]
7/27時点で「重症者数」を除く3指標全て「厳重警戒」以上だが、知事会見や知事ツイートにて現在「警戒領域」との事なので、全体判定から「厳重警戒」を除きます。

**判断指標と達成状況(最新)パネル**
- 右上の全体判定を変更、「重症者数」を除く3指標で判定
　全て危険：危険
　１つでも警戒以上：警戒
　上記以外：なし

![image](https://user-images.githubusercontent.com/63571899/88676886-96135300-d127-11ea-9ee6-bd1259d85407.png)
![image](https://user-images.githubusercontent.com/63571899/88676676-577d9880-d127-11ea-8c63-1c38280e173b.png)

**Comment by amay077** [comment]
判断指標と達成状況(最新)パネル について、着手します。

**Comment by amay077** [comment]
開発中の達成状況推移のグラフです。

![image](https://user-images.githubusercontent.com/401369/88828861-c2ea6780-d206-11ea-99dc-28b24e96de2b.png)

指標達成率は 警戒(25%)・厳重(50%)・危険(100%) で描いてますが、
指標値もほぼ倍々になっていて、log 2 な対数を導入できないかなあと考えています。
新規感染者数だけ 100％ を大幅に超えてしまい、他の達成状況が見づらくなってしまうのをなんとかしたいのもあります。

**Comment by hmatsu47** [comment]
新規感染者数以外に入院患者数もそのうち大幅に突き抜けそうですが、それぞれの項目の数値が取りうる範囲は危険ラインの3～5倍くらいまででしょうかね（そこまで達する前にまた指標が変わりそうですが）。
数値が危険ラインの2倍を超えるとグラフが読みにくくなるので、片対数グラフ化を考えてもいいのかもしれません（誤解を防ぐ目的で、縦軸に目盛がない点をどうするか考えたほうがいいですかね…注記するとか）。

**Comment by amay077** [comment]
こちらは

判断指標と達成状況(最新)パネル
判断指標と達成状況(推移)グラフ
「重症者数」グラフ
グラフ順序変更

の全て対応済みなので close します。
対数グラフはまた別の機会の議論にします。
