### ISSUE TITLE
検査陽性者の状況の注記内「入院等の内訳」の表示について

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19#830]
## 改善詳細 / Details of Improvement
- 7/28のデータから検査陽性者の状況グラフの注記に「入院等の内訳」が記載されるようになりました。
- 「入院等」の値は判断指標の「入院患者数」の値として利用されているため重要な値だと考えます。
- そのため「入院等の内訳」も重要な要素だと考えますがデフォルト非表示の注記内に記載されています。
- 「入院等の内訳」は注記と分けて検査陽性者の状況と併記（デフォルト表示）してはどうか。
- 発表形式が定まっていないため今後変更になる可能性は高いものの検討していただきたい。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/36749946/89491114-73e59900-d7e9-11ea-95c3-30418a1ba040.png)

## 期待する見せ方・挙動 / Expected behavior
- 具体的な表現方法の案は今のところ持っていません。
- 市町村別感染状況の凡例などのように注記とは別に記載されるとよいのではないか。
- より良い情報発信のためご意見やご提案をいただけると助かります。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hmatsu47** [comment]
凝ったものは必要ないと思いますので、既存コードを生かせるよう、

- データがある程度蓄積されるまでは「検査陽性者の状況」と同じ表形式のみで公開
  - 県サイトの「検査陽性者の状況」画像の形式がいきなり変わる可能性もあるので、少し様子を見る意味でも
- 2 週間程度蓄積されたら「検査陽性者状況の推移」と同じ積み上げグラフも作る
  - 「判断指標と達成状況」のように「最新」「推移」を切り替える形に

※「検査陽性者の状況」「検査陽性者状況の推移」も同じように「最新」「推移」を切り替える形にしても良いかも（注記含めて切り替わるように）

あたりでいかがでしょうか？

（Slack での議論にあったように）本当は「施設入所」だけ別になっているのも気持ちが悪いですが、県から公開されている情報の区分がこれまで通りなら、それに合わせておいたほうが良さそうな気がします。

**Comment by amay077** [comment]
賛同します。

「軽症・無症状者の内訳」であれば、軽症・無症状 項目を細分化することで解決できましたが、そうではなさそう（中等症で入院調整中の人も居るかも）なので扱いに困りますね。

ということで、入院等 にカッコ書きで記述するのはどうかなと思います。

![image](https://user-images.githubusercontent.com/401369/89529684-1ae92580-d828-11ea-88e7-cc66e5425b04.png)

処理的には、

1. 注記に 「入院等の内訳…」があったら、
2. その文末または「。」までの文字列を
3. 表内の「入院等」につづけて表示する

と流れを想定しています。

**Comment by hmatsu47** [comment]
わたしは「検査陽性者の状況」とは別の表を作るかな…とも思ったのですが、今のデータに内訳の列を追加して、その列からデータを取り出して amay077 さんが掲示されたように表示してもよさそうですね。

**Comment by amay077** [comment]
あっ、別表を作るのはよいですね。
その場合は、記入する Google Spreadsheet に「入院」「入院調整中」などの列を増やした方がやりやすそうです。

**Comment by hmatsu47** [comment]
恒久対応ではなくて暫定対応ですが、amay077 さんが最初に提示された形に合わせて作ってみましたので一旦プルリクを投げます。

**Comment by takainou** [comment]
今までの議論を元に、大阪サイトも参考にして、対応案をまとめてみました。特に「現在陽性者数」は単独の推移グラフにしても良いぐらい重要と考えています。知事会見でも現状を「入院等」の内訳説明で済ませようとした際「施設入所もですよね」と突っ込みが入る日もありました。県HPの情報を元に分かりやすく伝える事が当サイトの主目的ですので、「現在陽性者数」での対応が良いと考えます。

**[変更] 検査陽性者の状況(一覧) 表**
- 主に県全体の最新状況をまとめて把握する事を目的とする
- 「入院等の内訳」を組み込む(画面イメージ参照)
- 並びは上から症状の重い順とする
- 「現在陽性者数」「入院」を表示し、「入院等」は表示しない
　「現在陽性者数」＝「入院」+「調整中」+「自宅療養」+「施設入所」
- 「入院調整」「調整」はそのまま表示せず、合算し「調整中」として表示する
　「調整中」＝「入院調整」+「調整」
- 「軽症・無症状」は表示しない
- 追加4行「現在陽性者数」「入院」「調整中」「自宅療養」、削除2行「入院等」「軽症・無症状」で、計2行増加となる
- 「陽性患者数 (累積)」は県HPに合わせ「陽性者数 (累積)」に名称変更する

**[変更] 検査陽性者の状況(推移) 積み上げ棒グラフ**
- 主に退院の推移を把握する事、次に累計陽性者数の推移とその内訳を把握する事を目的とする
- 全積み上げグラフだったが、積み上げ数が増えすぎたので分割する
- 「検査陽性者の状況」2列目の積み上げ棒グラフとする
　下から「退院」「現在陽性」「転院」「死亡」と積み上げる
　「重症」「中等症」「軽症中等症」「軽症無症状」「施設入所」を削除し、「現在陽性」を追加する
- 「現在陽性」=「入院等」+「施設入所」で算出する
- パネル右上の数値は一番下の「退院」のままとする
- 「検査陽性者の状況」パネルと合体しボタン切替とする #835
- 「全体を100%とした構成比の推移グラフ」#242 にて「重症率」を掲載予定だったが、本来必要な「重症化率」はデータが無く算出できないので、「重症率」も掲載を断念する

**[新規] 現在陽性者の状況 積み上げ棒グラフ**
- 主に現在陽性者数の推移を把握する事、次に自宅療養の推移を把握する事を目的とする(愛知の自宅療養は日本一！)
- 「検査陽性者の状況」3列目の積み上げ棒グラフとする		
- 「入院等の内訳」が有る場合、下から「自宅療養」「施設入所」「調整中」「入院」を積み上げる
- 「入院等の内訳」が無い場合、下から「施設入所」「入院等」を積み上げる
- パネル右上の数値は積み上げを全て合算した「現在陽性」とする
- ツールチップには「現在陽性」も表示する
- グラフ配置は、現在の「検査陽性者の状況推移」積み上げ棒グラフの位置とする

**[変更] 入院患者数 積み上げ棒グラフ+折れ線グラフ**
- 主に入院患者数の推移を把握する事、次に中等症(+重症)の推移を把握する事を目的とする
- 「軽症以下」＝「入院」-「重症」-「中等症」を算出する
- 下から「重症」「中等症」「軽症以下」を積み上げる
- 凡例をクリックしても非表示化しないよう設定する
　→「軽症以下」のみの表示を避ける
- ツールチップには、「入院患者数」「中等症」「重症」を表示する
- データとしては「軽症以下」だが、表示・操作上は「入院患者数」として振る舞う事とする
- 「検査人数・陽性率」グラフにて同対応を実施済みである

入院患者数は積み上げとせず、「検査陽性者の状況」2-3列目の積み上げも検討しました、そこで見せたいのが中等症(+重症)ですが全体比が小さく分かりにくかったので、入院患者数積み上げとしました。

「現在陽性者の状況」は自宅療養を最下部としましたが、懸念事項が例えば調整中であればそれを最下部とするのも良いと考えます。

なお、画面イメージにおけるグラフの色は未調整です。
![image](https://user-images.githubusercontent.com/63571899/90018532-06090800-dce8-11ea-9e81-dc4198cf32cf.png) ![image](https://user-images.githubusercontent.com/63571899/90017717-e6251480-dce6-11ea-96e8-b7d9b988b957.png)
![image](https://user-images.githubusercontent.com/63571899/90017760-f806b780-dce6-11ea-80ec-1ab2b8a854f6.png)
![image](https://user-images.githubusercontent.com/63571899/90017781-005ef280-dce7-11ea-82e6-2376b7b147b9.png)
![image](https://user-images.githubusercontent.com/63571899/90017851-166cb300-dce7-11ea-82b9-743fb95ddb42.png)
![image](https://user-images.githubusercontent.com/63571899/90018117-68153d80-dce7-11ea-8596-42e911ab691c.png)

**Comment by takainou** [comment]
8/13(8/12 20時時点)より、内訳が枠内に組み込まれました。「入院等」は無くなり、「転院」も無くなってます。「軽症・無症状」の定義が変わっています。

スプレッドシートmain_summaryに県公表値のまま入れると、当サイトの「検査陽性者の状況」一覧表と、「検査陽性者の状況推移」積み上げ棒グラフの表示がおかしくなりますので、ひとまず前の定義で「軽症・無症状」「入院等」「転院」を入力しました。挙動確認未ですが、暫定対応としてはこれで良いと考えます。対応案を決定し、県HPに追随する必要が有ると考えます。

対応案を出したばかりですが、大きな論点は以下2点の認識です。

論点A. 「検査陽性者の状況」一覧表は、
1. 県HPまま
2. 現在陽性者数列を追加

論点B.「検査陽性者の状況推移」積み上げ棒グラフは、
1. 全部積み上げのまま
2. 現在陽性者数を分割し積み上げ棒グラフ１つ新設
3. 現在陽性者数を分割し積み上げ棒グラフ１つ新設し、さらに重症/中等症/軽症無症状は「入院患者数」棒グラフで分割

画面イメージはまだ修正出来ていないのですが、意見をお願いします。
![image](https://user-images.githubusercontent.com/63571899/90088525-1c4fac00-dd5a-11ea-8a08-77f7db88195a.png)

**Comment by ozo360** [comment]
「検査陽性者の状況」一覧表は、県HPままがよいのでないかと考えます。
「検査陽性者の状況推移」積み上げ棒グラフについては、ノープランです。

ちなみに、指標の入院患者数はどこの値を使うのか気になりました。
愛知県公式で現在の指標値を参照できるところはないんでしたっけ？

**Comment by takainou** [comment]
> ちなみに、指標の入院患者数はどこの値を使うのか気になりました。

おぉ、すみません、肝心な点が抜けてました。ありがとうございます。この枠からだと「入院」ぐらいしか無いですが、どうするのでしょうか。

> 愛知県公式で現在の指標値を参照できるところはないんでしたっけ？

はい、ありません。名古屋市の新型コロナ特設サイトにありますが、元ネタが不明です。

知事会見で、記者クラブには指標のペーパーが配布されており、数値を読み上げる日もあるので、今日夕方の会見にて確認出来るかもしれません。

**Comment by ozo360** [comment]
![image](https://user-images.githubusercontent.com/36749946/90097324-9ee36600-dd70-11ea-83a0-b1988034af08.png)
なるほどこちらの「愛知県のコロナ対策の指標」ですね。
愛知県からちゃんと公表して欲しいですね。
非公式サイトでだけ指標の数字が異なってしまうという状況は避けないといけないと思います。

**Comment by takainou** [comment]
> 非公式サイトでだけ指標の数字が異なってしまうという状況は避けないといけないと思います。

はい、その通りなのですが、公表いただけていない中、当サイトとしても指標を掲載したいという中の判断で、当サイトに指標を掲載した当初から数字は異なっています(陽性率、検査人数が公表されていない為ズレます)。

因みに、名古屋市の特設サイトが一時明らかに誤った数値を載せたり、一時掲載を見送っていたのは把握しており、名古屋市の特設サイトは元ネタが不明と認識しています。それよりも当サイトの方が精度高く、安定運用されていると認識しています。

そして、会見で口頭でチラっと話されるのを聞くぐらいしか、異なっている事をきちんと確認する術も無い状態です。

指標が設定されて３ヶ月以上経ちますが、残念ながら指標(や検査人数)が公表される気配が一切ないので期待する事は諦めており、当サイトで出来限り正確で価値が有り分かりやすい情報を提供する方が県民の為と考えて精一杯対応しているつもりです。

**Comment by takainou** [comment]
> 知事会見で、記者クラブには指標のペーパーが配布されており、数値を読み上げる日もあるので、今日夕方の会見にて確認出来るかもしれません。

会見動画を確認した所、新しい「検査陽性者の状況」の説明はありましたが、指標説明は陽性率と重症者数だけ読み上げて院患者数は読みあげられず…。

論点A. 「検査陽性者の状況」一覧表につき、既に案1に1票いただいておりますが、画面イメージ案です。
![image](https://user-images.githubusercontent.com/63571899/90100899-9858ec80-dd78-11ea-9d6c-20fa779c17d8.png)

案2を推す理由ですが、当サイトは東京都と異なり公式では無く、県HPとの併設です。県HPと役割分担し、県HPに足らない部分をより分かりやすく表現する事が、当サイトの役割の1つと認識しています。県HPままでは、県HPを見れば良いですし、「検査陽性者の状況」に限れば、県HPから情報量を落としています(クラスター、分類別、検疫患者、7月～)。情報量を落とす事も分かりやすく表現する方法の1つと考えますが、情報を足して分かりやすくしたいという考えもあり、厚労省(入院治療等を要する者の数)や大阪府も掲載している「現在陽性者数」を足せないかと提案させて頂きました。

ただ、開発負荷は増えますので、そこまでの価値は無いとの意見だったり、それじゃないとの意見もあるでしょうし、1列追加すると見にくいよという意見もあるでしょう。県HPままが良い理由を一言添えていただければと思います。

今回は、ひとまず県HPに追従する事を優先し、「現在陽性者数」は次の機会でも良いのかなとも、実際には考えております。導入と文末があべこべですみません。

論点B.「検査陽性者の状況推移」積み上げ棒グラフも画面イメージ作成しましたので、添付します。
案1.全部積み上げのまま[10積み上げ]
![image](https://user-images.githubusercontent.com/63571899/90146054-91070280-ddbb-11ea-80f1-9710f4d316b1.png)
案2.現在陽性者数を分割し[3積み上げ]
![image](https://user-images.githubusercontent.com/63571899/90146196-b85dcf80-ddbb-11ea-8153-c7de3a89049a.png)
積み上げ棒グラフ１つ新設[8積み上げ]
![image](https://user-images.githubusercontent.com/63571899/90146290-d4617100-ddbb-11ea-9096-afd9c42f7a54.png)
案3.現在陽性者数を分割し(案2と同じ)、積み上げ棒グラフ１つ新設し[5積み上げ]、
![image](https://user-images.githubusercontent.com/63571899/90146378-f0651280-ddbb-11ea-8673-c8ad81f62a61.png)
さらに重症/中等症/軽症無症状は「入院患者数」棒グラフで分割[3積み上げ]
![image](https://user-images.githubusercontent.com/63571899/90146480-0d99e100-ddbc-11ea-8fc1-ac067103dbb1.png)

**Comment by hajime-miyauchi** [comment]
あれ？すでに議論されているかもしれませんが、昨日20時発表の愛知県の「検査要請者の状況」も「入院等」ではなく「入院」に切り替わってますね。(これはこれで対応が必要そう)

愛知県でもこのIssueと同じような議論があったのかもしれませんね。

![](https://www.pref.aichi.jp/uploaded/image/242608.jpg)

**Comment by takainou** [comment]
はい、分かりにくいですが、このコメントhttps://github.com/code4nagoya/covid19/issues/830#issuecomment-673216000 からは、県HPの変更をふまえての議論になっております。

**Comment by ozo360** [comment]
@takainou 
検査陽性者の状況の画面イメージありがとうございます。
確かにこれであれば「現在陽性者数」があった方が判りやすいですね。
また、この程度なら効果的な見せ方の工夫の範囲内かと思いました。
こちらに意見を変更したいと思います。

@hajime-miyauchi 
指標の「入院患者数」を現在陽性者数（約1600）で表すか、入院（約300）で表すかという点で、
名古屋市では「入院患者数」、愛知県はそもそも公表されていないという状況です。
本来の意味であれば「入院」の数字で問題ないと私も考えるのですが
拠り所の無い判断で非公式サイトが公表するのは不味くないかと思います。

**Comment by takainou** [comment]
論点A.「検査陽性者の状況」は案2「現在陽性者数」有り1票で了解です。

指標「入院患者数」の取り扱い、大切ですが、まだ情報が足らない(県の変更有無、官公庁お盆シフトによる反映不足など)ので、一旦、保留して、もう少し情報が集まってから、議論再開としませんか。来週末ぐらいにはお盆シフト明けて業務も追いつくかと思いますので、その頃まで。もし、県が「入院」に変更したら、議論不要ですしね。

当サイトも「検査陽性者の状況」項目変更への追随(元の本Issueの論点)、陽性者一覧PDFの2ファイル対応  https://github.com/code4nagoya/covid19-aichi-tools/issues/58#issue-678267565 など、議論が必要な案件が有ります。

**Comment by ozo360** [comment]
それはそうなんですが、 #845 は既に反映されてしまっているので気にしています。
とはいえ週末全く顔を出せません。
申し訳ないです。

**Comment by takainou** [comment]
![image](https://user-images.githubusercontent.com/63571899/90100899-9858ec80-dd78-11ea-9d6c-20fa779c17d8.png)

『論点A.「検査陽性者の状況」一覧表 案2.現在陽性者数列を追加』の対応内容案です。案1の場合「現在陽性者数」関連の削除となります。スプレッドシートの列順変案も併せて提示します。

**[変更] 検査陽性者の状況(一覧) 表 案2.現在陽性者数列を追加**
- 主に県全体の最新状況をまとめて把握する事を目的とする
- 8/13(8/12 20時時点)以降の県HPでのフォーマット/並びに基本的に従う
- 「陽性患者数（累積）」の名称を「陽性者数（累積）」に表記を変更する
- 「軽症・無症状」はモバイルの幅を考慮し名称を「軽症無症状」に表記を変更する
- 「退院」の名称を「退院等」に表記を変更する
- 「入院等」を削除して「入院」を追加し、内訳は記載しない
- 「転院」を削除する
- 「入院調整」「自宅療養」「調整」を追加する
- 「軽症無症状」はスプレッドシートの値をそのまま使わず、以下で算出する
　「軽症無症状」＝「入院」－「中等症」－「重症」
　「検査陽性者の状況推移 積み上げ棒グラフ」が旧定義の「軽症・無症状」の為、県HPと異なる値をスプレッドシートに入力しており、本件を単独で対応可とする為
- 「現在陽性者数」のみ県HPに対して追加して表示、列も追加する
　「現在陽性者数」＝「入院」+「入院調整」+「施設入所」+「自宅療養」+「調整」
　「現在陽性者数」は他でも利用する可能性が有るのでdata.jsonに保持しても良い
- 追加5行「現在陽性者数」「入院」「入院調整」「自宅療養」「調整」、削除2行「入院等」「転院」で、計3行増加、「現在陽性者数」の1列増加となる

**[変更]スプレッドシートmain_summary列順変更案**
- スプレッドシートの列順が、県HPと大きく異なってしまっており、入力ミスを防ぐため、添付画面イメージの通り変更する(他のアプリに影響がなければ)。
- 「入院」「施設入所」を手前に、「入院中」「軽症中等症」「転院」を「備考」の前に移動
![image](https://user-images.githubusercontent.com/63571899/90242889-cddd0300-de68-11ea-8cec-34c7ba3b5ea9.png)

**Comment by amay077** [comment]
@takainou さん、

> [変更]スプレッドシートmain_summary列順変更案
> 
> スプレッドシートの列順が、県HPと大きく異なってしまっており、入力ミスを防ぐため、添付画面イメージの通り変更する(他のアプリに影響がなければ)。

は、他のアプリに影響はないので、即時おこなっていただいて OK です。

**Comment by amay077** [comment]
> 論点A.「検査陽性者の状況」は案2「現在陽性者数」有り1票で了解です。

は、私も 案2 に賛成です。現在陽性者数 はあったほうがわかりやすいと思います。

論点B については、

> [変更] 検査陽性者の状況(推移) 積み上げ棒グラフ
> 主に退院の推移を把握する事、次に累計陽性者数の推移とその内訳を把握する事を目的とする
>
> [新規] 現在陽性者の状況 積み上げ棒グラフ
> 主に現在陽性者数の推移を把握する事、次に自宅療養の推移を把握する事を目的とする(愛知の自宅療養は日本一！)

に概ね賛成を前提とした上で、もうすこし目的を汎化して、
以下のように考えてみました、案4 とします。

> 主に退院の推移を把握する事、次に累計陽性者数の推移とその内訳を把握する事を目的とする
→ 陽性者の「病状・容態」の推移はどうなっているか？（軽症無症状が全体のほとんどです、中等症が増えてきました、など）

> 主に現在陽性者数の推移を把握する事、次に自宅療養の推移を把握する事を目的とする(愛知の自宅療養は日本一！)
→ 現在陽性者の「居場所」の推移はどうなっているか？（重症病床と一般病床は逼迫していません、施設も空いています、自宅療養多いけどいいの？、など）

図にするとこんなイメージです。

![image](https://user-images.githubusercontent.com/401369/90317670-0282b480-df66-11ea-9b39-d5abc14f58f5.png)

それから、 https://github.com/code4nagoya/covid19/issues/835 を取り入れて、状況と推移 を一つのパネルで切り替えて表示するようにしたらどうかなとも考えています。案4 だと [状況 / 推移(病状) / 推移(居場所)] の切り替えになります。
パネルとしては、検査陽性者状況の推移 が 検査陽性者の状況 に吸収合併されて、ひとつ減ることになりますね。
また、 https://github.com/code4nagoya/covid19/issues/242 も現在は価値が高まっていると考えていて、これを実装した場合100%比率グラフもひとつのパネルに切り替え制で押し込めると、ちょっと機能過多かなあと、悩み中です。

ちょっと発散させてしまいましたが、現在の私見でした。

**Comment by amay077** [comment]
ひとまず「論点A.「検査陽性者の状況」」については、
”案2「現在陽性者数」有り” で概ね合意が得られたとして、
まずは、「検査陽性者の状況」パネルを修正する issue を別途立てて着手してよいと考えますがいかがでしょうか？

論点B の推移のグラフについての議論は引き続きこの issue で行えれば。

**Comment by takainou** [comment]
なるほど、それも分かりやすいかもです。私の案は「全体」→「現在陽性者」→「入院」とドリルダウンするのに対し、切り口(病状や療養場所)を変えるという事ですね。

案2から案3が出て来た背景になるのですが、推移(病状)で中等症をみようとしても、構成比的に少なくて推移が分からないのですよね。なので入院患者数の積み上げが良いかなと当初は考えました。推移(居場所)で重症病床をみようとしても同様ですが、こちらは、単独の推移グラフがあります。

まずは「何を見せて読み取ってもらいたいか」を摺り合わせましょうか。私は以下3点です。

1. 「現在陽性者」は単独でも推移を見せたい、積み上げでグラフ無くても良い
←県が把握管理する必要がある人数であり、県の現状を示すのに適しており、「現在陽性者数」が0人となって終息である。
←当初は、自宅療養・施設入所などがほぼ無く、入院患者数が同様の役割だった
←新規陽性者が出ていても、退院が上回れば、現在陽性者は減少し、県全体としては収束傾向と言えるので、新規陽性者よりこの増減幅の方が重要となる

1. 「中等症」は単独までは行かなくても、積み上げグラフで下段で見せたいが、精度向上次第か。
←重症化予備軍であり、重症化を防ぐ為の病状管理が肝要らしく、医者に制約がある
→まだ県の日々の状況更新が軌道に乗っていない様子で、8/11→8/12で急減している

1. 「自宅療養」は単独までは行かなくても、積み上げグラフで下段で見せたい
←「施設入所」「自宅療養」どちらもメリットデメリットが有り、病状と重症化リスク、陽性者の都合(同居者など)や希望で分けられるものだが、施設確保が遅れて「自宅療養」中心となった事は事実で、他都道府県と比べて愛知県はあまりにも「自宅療養」率が多いので推移を見守る必要がある

1.により「検査陽性者の状況」「検査陽性者の状況推移」パネルと「現在陽性者の状況推移」パネルは分けたいと考えています( #835 自体は賛同します)。2.3.は正直弱い要望です。全部積み上げだと積み上げすぎで分割された「積み上げグラフがあるなら、下段に置かせて欲しい」ぐらいですね。つまり「現在陽性者の推移」以外はもう少し醸成してからと考えています。
![image](https://user-images.githubusercontent.com/63571899/90336088-767b9600-e014-11ea-81ce-87d8b18b3a5b.png)

私も #242 は有用と考えています(重症者率が表現出来なくても)。「退院」「現在陽性者」「死亡」の構成比率推移でも十分と考えています【致死率は減ってます。8/3から「退院」の伸びの方が「現在陽性者」の伸びを上回ってます】。県全体の負荷という点では「現在陽性者」が減らないといけません【「現在陽性者」は8/10から減少】。100%積み上げ棒グラフではなく、100%積み上げ面グラフでも良いでしょう。
![image](https://user-images.githubusercontent.com/63571899/90336102-83988500-e014-11ea-9e7b-c620c7b6c4f6.png)

構成比率推移という点では、年代別は分かりやすいのですが、あくまで一時分析用で常設では無いかなと考えてます【先週後半から中高年、特に高齢者に拡がっている事が分かります】。
![image](https://user-images.githubusercontent.com/63571899/90336115-9dd26300-e014-11ea-8d19-4008c4008545.png)


もう少し醸成させたいのもあり、私も発散させてみました。

**Comment by takainou** [comment]
論点Bに対する私の最終見解です。
- 前述の「何を見せて読み取ってもらいたいか」の「2.中等症」「3.自宅療養」は、現時点で単独で見せるほど重要視する必要がないと考えている(どこかで推移が見られれば良いレベルか)
- 積み上げグラフの棲み分けも「何を見せて読み取ってもらいたいか」がまだはっきりして来ない
- 3つ以上の積み上げグラフにすると、見せたいものがぼやけてしまう

これをふまえ、まずは

1. 「現在陽性者数」単独の推移棒グラフを新設
2. 「検査陽性者の状況推移」積み上げ棒グラフは「主に退院を見せる全積み上げ棒グラフ」のコンセプトを維持する
　９つの全積み上げで、下から「退院 」「調整」「自宅療養」「施設入所」「入院調整」「軽症無症状」「中等症」「重症」「死亡」
4. 「検査陽性者の状況推移」積み上げ棒グラフは「「検査陽性者の状況」一覧表パネルと同居させる
1. 新設する「現在陽性者数」推移棒グラフを従来の「検査陽性者の状況推移」積み上げ棒グラフのパネル位置に配置する
 
で、どうでしょうか。「中等症」「自宅療養」は全積み上げ棒グラフで凡例操作で参照できますし、重要度が上がれば単独グラフ化を検討し、た、積み上げグラフの棲み分けがはっきりして来たら分割も検討します。

「現在陽性者数」単独の推移棒グラフイメージです。8月初ぐらいの値に減って来ました。
![image](https://user-images.githubusercontent.com/63571899/90526138-fcc9e080-e1aa-11ea-92b2-cb8d442ea6aa.png)

**Comment by takainou** [comment]
論点B.「検査陽性者の状況推移」積み上げ棒グラフの対応案は、以下となっており、案5が私の最終見解です。
1. 全部積み上げのまま
2. 現在陽性者数を分割し積み上げ棒グラフ１つ新設
3. 現在陽性者数を分割し積み上げ棒グラフ１つ新設し、さらに重症/中等症/軽症無症状は「入院患者数」棒グラフで分割
4. 現在陽性者数を分割し積み上げ棒グラフ１つ新設、病状別と居場所別に分ける
5. 全部積み上げのまま+「現在陽性者数」単独の推移棒グラフ１つ新設

検査陽性者の状況(推移)全積み上げグラフの画面イメージ(色は未調整)、及び、対応内容案です。

**[変更] 検査陽性者の状況(推移) 積み上げ棒グラフ**
- 主に退院の推移を把握する事、次に累計陽性者数の推移とその内訳を把握する事を目的とする
- 全積み上げグラフとし、凡例クリックによる表示/非表示で任意の項目の推移を確認できる
- 大きく２期間に分類して積み上げる
　1.入院等分割前(～7/27) 
　2.現時点(7/28～)
- 2.現時点(7/28～)は、９個の全積み上げで、症状の軽い順で下から
　「退院等」「施設入所」「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」「重症」「死亡」
　(「施設入所」は1.との連続性の為、症状は自宅療養よりも重いが下に配置する)
　「軽症無症状」＝「入院」－「重症」－「中等症」(7/28-8/11、8/12以降も計算式で同値となる)とする
　「退院等」＝「退院」＋「転院」(～8/11、8/12以降「転院」空欄につき同じ計算式で良い)とする
　ツールチップには９項目のみ表示し、「軽症中等症」は表示しない
- 1.入院等分割前(～7/27)は、５個の全積み上げで、症状の軽い順で下から
　「退院等」「施設入所」「軽症中等症」「重症」「死亡」
　「退院等」＝「退院」＋「転院」とする
　「軽症中等症」＝「軽症無症状」＋「中等症」(7/24-27、7/23以前は「中等症」空欄につき同じ計算式で良い)とする
　ツールチップには５項目のみ表示し、「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」は表示しない
- 1.の「軽症中等症」には2.の「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」が含まれており、 **1.→2.で「軽症中等症」が５分割される** 事になる
- 凡例は合計１０個となる(現時点の９個＋「軽症中等症」)
- 積み上げ数が増えて、凡例も増えており(モバイルだと3行)、グラフ表示縦幅が減って構成が分かりにくくなっているので、他グラフの標準縦幅より大きめとし、グラフ単体での縦幅を確保する。ツールチップが全項目表示出来るように調整する。
- パネル右上の数値は一番下の「退院等」とする(表記は退院のままで良い)
- 「検査陽性者の状況」パネルと合体しボタン切替とする #835
- 「全体を100%とした構成比の推移グラフ」#242 にて「重症率」も掲載する
- スプレッドシートmain_summaryの「軽症無症状」の値は、本改修と同時に、現在の暫定対応(「入院」－「重症」－「中等症」＋「自宅療養」＋「調整」＋「入院調整」)から、県HP画像の値(意味的には「入院」－「重症」－「中等症」)に、戻す(8/12～最新)。これにより、暫定対応は無くなり、スプレッドシートmain_summaryには県HPの画像の値のみの入力となる。
![image](https://user-images.githubusercontent.com/63571899/90778430-932b0d00-e337-11ea-9a20-d496aa9dcb42.png)

「現在陽性者数」単独の推移棒グラフイメージです。7月末ぐらいの値に減って来ました。
![image](https://user-images.githubusercontent.com/63571899/90778588-c8375f80-e337-11ea-990a-2ee48bac1f1e.png)

**Comment by amay077** [comment]
では、後は各 issue で対応するとして、本 issue は close します。
