### ISSUE TITLE
3月12分のデータの追加

### ISSUE THREAD

**Issue by takayashibagaki** [code4nagoya/covid19#84]
## 起こっている問題 / The Problem
- コロナウイルスの3/12分のデータを追加

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by takayashibagaki** [comment]
データのリンクはこちらです。

https://docs.google.com/spreadsheets/d/1BqCcrMTkkufqrv9AO9wS88utbotRUcG6/edit#gid=1588368354

**Comment by billhung** [comment]
3月16日朝、本番サイトで3月12日分のデータを反映されました。
https://stopcovid19.code4.nagoya/
COMMITリンク
https://github.com/code4nagoya/covid19/runs/507618201?check_suite_focus=true

**Comment by takayashibagaki** [comment]
ありがとうございます！！
