### ISSUE TITLE
愛知県HPの「愛知県内の検査件数」で月ごとの集計値が登場したことによる対応

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19#840]
## 改善詳細 / Details of Improvement
- [愛知県内の感染者・検査件数 - 愛知県](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html) の「3．愛知県内の検査件数」の表に「２月」「３月」など、月ごとに集計された行が登場しました（添付画像参照）
- 8/8現在は、これらの行はデータ加工でエラーとなるため [応急処置として読み飛ばし](https://github.com/code4nagoya/covid19-aichi-tools/pull/56) ています
- 月ごとに集計された行を適切に読んで data.json に加工し、サイト側で表示する方法を提案します。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/401369/89706280-21e67400-d99f-11ea-8419-7584fa79f57f.png)

#### data.json の inspections_summary の仕様

**現在**

```
  "inspections_summary": {
      "date": "2020/08/01 12:57",
      "data": [
          {
              "日付": "2020-03-01",
              "小計": 639,
              "合算": "○"
          },
```

**対応後**

data.json に「集計」項目を追加し、 m:月合算 / w:週合算 / なし:日単独 を設定し、データの集計範囲を示すものとします。
※「合算」は、データ表示側の対応が終わるまでの互換性維持のために残し、データ表示側が済めば削除。

```
  "inspections_summary": {
      "date": "2020/08/01 12:57",
      "data": [
          {
              "日付": "2020-03-01",
              "小計": 639,
              "合算": "○",
              "集計": "m"  ← m or w or 空
          },
```

具体的には、表の「検査日」が、

- ○月 の場合 → data.jsonの 集計 に "m" を設定
- ○月○日～○月○日の場合
    - 開始日が月曜日かつ終了日までの日数が７日以内の場合 → 集計 に "w" を設定
    - 上記以外の場合 → 集計 に "m" を設定
- ○月○日の場合 → 集計 は空
- いずれにも該当しない場合 → 行は処理対象外

### データ表示側「検査実施件数パネル」の対応

**現在**

- 合算が「空でない」場合は、週合算値とみなし、週別のグラフデータとして使用
- 合算が「空」の場合は、日単独値とみなし、日別のグラフデータとして使用。且つ、７日間で集計し週別のグラフデータとしても使用

**対応後**

- グラフの種類 [週別/日別/累計] に、「月別」を加えて [月別/週別/日別/累計] とする
- 集計が「m」の場合は、月合算値とみなし、月別のグラフデータとして使用
- 集計が「w」の場合は、週合算値とみなし、週別のグラフデータとして使用、且つ、月ごとに集計し月別のグラフデータとしても使用
- 集計が「空」の場合は、日単独値とみなし、日別のグラフデータとして使用。且つ、７日間で集計し週別のグラフデータとしても使用、さらに月ごとに集計し月別のグラフデータとしても使用
- 月別のグラフは下図の通りとする
- 月別を選択したときのタイトルは「検査実施件数(月別)」とする

![image](https://user-images.githubusercontent.com/401369/89708443-1ea8b380-d9b2-11ea-9b29-dfef5803af64.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amay077** [comment]
愛知県HPの表では「7月1日（水曜日）～7月14日（火曜日）」と集計されているので、週単位の集計データ（集計:"w"）は、作成されない可能性が高いです。

**Comment by takainou** [comment]
8月18日 17時現在の検査件数の更新から、日単位の範囲が減り、週単位のデータが発生しています。7/1始まりの水～火です。この形の表にまとめるの手間なはずですが、手間かけてるのに推移が分かりにくいです…。

来週には7月が月単位にまとめられるのかもしれませんし、第2波として7月以降が週単位と日単位なのかもしれませんが、現時点では分かりませんので、まずは取り込み処理等が動いて、日別のグラフが掲載される、つまり現状維持されれば良いと考えます。
![image](https://user-images.githubusercontent.com/63571899/90513439-a0f75b80-e19a-11ea-80c3-fe7ec14438bf.png)

**Comment by takainou** [comment]
8月19日 17時現在の検査件数の更新から、7月が月単位にまとめられ、週単位は無くなりました…。2週間強の日単位だけで推移は分かりません。毎日フォーマット変更して何しているんでしょう。そんな変更よりも日々の検査人数を公表して欲しいものです。
![image](https://user-images.githubusercontent.com/63571899/90627316-c77acc80-e256-11ea-9bab-0b35ca8527de.png)

**Comment by amay077** [comment]
７月の集計行が登場すると、やっつけ処理で対応しきれず定時処理が落ちるので、「ちゃんと」対応しました。
https://github.com/code4nagoya/covid19-aichi-tools/pull/64

**Comment by takainou** [comment]
8月31日 17時現在の検査件数の更新から、8月前半(1～14)がまとめられました。本Issue起票当初(8月7日 17時現在)と同じ形式につき、問題無いかと思いますが共有します。
![image](https://user-images.githubusercontent.com/63571899/91719432-49acae80-ebd0-11ea-80ad-b9a0e5837456.png)

**Comment by amay077** [comment]
完了していると思われるので close します
