### ISSUE TITLE
山梨・愛媛県版を追加

### ISSUE THREAD

**Issue by yukou-isshiki** [code4nagoya/covid19#85]
## 起こっている問題 / The Problem
- 本家に山梨県版のリンクが追加されてたので対応する。あと、愛媛県版も追加する。

**Comment by fussy113** [comment]
#88 

いつも対応ありがとうございます!
こちらで今後追加対応減らせると思うのですがどうでしょう!?

**Comment by yukou-isshiki** [comment]
まとめサイトの構想が出ているので、変えるならそっちの方が良いと思います。

https://github.com/homata/stopcovid19-dashboard

**Comment by hajime-miyauchi** [comment]
まとめサイトは、まだ構想段階のようですので現時点においては一旦本家サイトにしておいて、まとめサイトが立ち上がった段階でリンク差しかえするというのはどうでしょう。

**Comment by hajime-miyauchi** [comment]
まとめサイトを構想している小俣さんのほうでも現時点ではforkedSites.mdへの掲載を呼びかけているので、そちらに掲載されてるのが今この時点で「完成しているサイトの情報」としては最新版かと。
(アクセスできる状態になっているサイトは他にもたくさんあるが、完成してリンクを貼っていい状態なのか、まだ開発中だからリンクを貼ってほしくないのかが判断しづらい)

https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view

**Comment by yukou-isshiki** [comment]
ちょっと、Slackで聞いたのですが`forkedSites.md`についてはあくまで、開発者向けで一般向けのご案内という想定にはなっていないようです。

ページが長くなってきており、いずれは水先案内ページにリンクを切り替える必要は当然出てくると思います。

ただ、個人的にはそのページが開発者向けとなっている`forkedSites.md`というのは疑問に思います。(あくまで、一般利用者向けのリンク・サイトであるべきだと思うので)

**Comment by hajime-miyauchi** [comment]
> forkedSites.mdについてはあくまで、開発者向けで一般向けのご案内という想定にはなっていないようです。

これについては同意です。上記サイトへのリンクが最善策とは考えていません。

ただ、現時点で結構他の地域サイトが追いきれないくらい立ち上がってきているので、愛知として、このまま更新を続けていくのか、そうしないのかの判断期かなと思った次第です。

考えられる方向性としては下記3つが思いつきますが、今回わたしが提案したのは3です。

1. 各地域版へリンクをそもそもやめてしまう(北海道はすでに段階でそうしている)
2. 愛知版としてやれるところまで(まとめサイトが立ち上がるまで？)地域サイトを掲載し続ける
3. 利用者向けのサイトではないが、ひとまず現時点で最新、且つ正確な情報が掲載されているforkedSites.mdへのリンクを貼る

> 本家に山梨県版のリンクが追加されてたので対応する。あと、愛媛県版も追加する。

本家にリンクが追加されていたということであれば、そのページにリンクしちゃうのもありかもと思いましたが見つけられませんでした。

**Comment by ctyo** [comment]
いったん、こちらの議論の関連です。

他の自治体は東京へ一覧リンクを貼る対応をマージしました。
自治体以外のいい感じのサイトへリンクが貼りたいニーズなどが高まりましたら、別途対応をしましょう。
https://github.com/code4nagoya/covid19/issues/88

**Comment by amay077** [comment]
こちらは close しますが、東京への一覧リンク先がリンク切れになったようなので

#104 

を作りました。
