### ISSUE TITLE
「検査陽性者の状況」一覧表の県HP変更への追随、および「現在陽性者数」の追加

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#868]
## 改善詳細 / Details of Improvement
- 7/28から、県HPの「検査陽性者の状況」の枠下注記に「入院等の内訳」が記載され始めた
- 8/13から、内訳は枠内に組み込まれ、掲載内容も変化した(「入院等」「転院」の削除など)
- 当サイトの「検査陽性者の状況」一覧表も、県HPに追随する必要がある
- #830 にて議論して来たが、概ね合意が得られたので、本Issueを起票する
- 県HPには表現されていないが「現在陽性者数」は、県が把握管理する必要がある人数であり、県の現状を示すのに適しており、「現在陽性者数」が0人となって終息なので、列を追加して表現する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/90324971-78ac0900-dfb0-11ea-9b02-156d88b7b148.png)

## 期待する見せ方・挙動 / Expected behavior
**[変更] 検査陽性者の状況 一覧表**
- 主に県全体の最新状況をまとめて把握する事を目的とする
- 8/13(8/12 20時時点)以降の県HPでのフォーマット/並びに基本的に従う
- 「陽性患者数（累積）」の名称を「陽性者数（累積）」に表記を変更する
- 「退院」の名称を「退院等」に表記を変更する
- 「軽症・無症状」はモバイルの幅を考慮し名称を「軽症無症状」に表記を変更する
- 「入院等」を削除して「入院」を追加し、内訳は記載しない
- 「転院」を削除する
- 「入院調整」「自宅療養」「調整」を追加する
- 「軽症無症状」はスプレッドシートmain_summaryの値をそのまま使わず、以下で算出して表示する
　「軽症無症状」＝「入院」－「中等症」－「重症」
　←「検査陽性者の状況推移 積み上げ棒グラフ」が旧定義の「軽症・無症状」の為、
　　県HPと異なる値をスプレッドシートmain_summaryに入力しており、本件を単独で対応可とする為
- 「現在陽性者数」のみ県HPに対して追加して表示、列も追加する
　「現在陽性者数」＝「入院」+「入院調整」+「施設入所」+「自宅療養」+「調整」
　「現在陽性者数」は他でも利用する可能性が有るのでdata.jsonに保持しても良い
　(「入院」が空の場合、「現在陽性者数」＝「入院中」+「施設入所」で保持する)
- 追加5行「現在陽性者数」「入院」「入院調整」「自宅療養」「調整」、削除2行「入院等」「転院」で、計3行増加、「現在陽性者数」の1列増加となる
- パネル右上の更新日に時刻を表示してないので、省力化の為、スプレッドシートmain_summary「更新日時」の時刻入力を止め、「更新日」のみの入力とする(もしくは、パネル右上に時刻も表示する)

**Comment by amay077** [comment]
> パネル右上の更新日に時刻を表示してないので、省力化の為、スプレッドシートmain_summary「更新日時」の時刻入力を止め、「更新日」のみの入力とする(もしくは、パネル右上に時刻も表示する)

については、 https://github.com/code4nagoya/covid19-aichi-tools/issues/44 の目処が立ちそうなので、現状ママの時刻ありで、「パネル右上に時刻も表示する」としたく思います。

**Comment by takainou** [comment]
> については、 code4nagoya/covid19-aichi-tools#44 の目処が立ちそうなので、現状ママの時刻ありで、「パネル右上に時刻も表示する」としたく思います。

了解です。同認識かと思いますが、時刻表示するのは本パネル「検査陽性者の状況」一覧表のみで、他パネルは現状通り日のみ表示の認識です。

それよりも、OCRの目処が立ちそうな事に、喜びを隠せません。ありがとうございます。ありがとうございます。

となると、OCR導入までには「軽症無症状」は、県HPそのままの値を入れるようにした方が良いですね(「検査陽性者状況の推移」積み上げ棒グラフの修正が必要)。

また、折角ですので、inspection_persons_summaryも算出ロジック《累計検査実施人数の日毎差分で前日反映と、土日未更新→月更新時の日別検査実施件数による按分で金土日反映》もまとめておきます。これはOCRが無くても、累計検査実施人数と日別検査実施件数(PCR+抗原)があれば導入出来ると考えてます。更新の流れはOCRを参考にします(スプレッドシート残して手動更新可とするなど)。

**Comment by amay077** [comment]
> となると、OCR導入までには「軽症無症状」は、県HPそのままの値を入れるようにした方が良いですね(「検査陽性者状況の推移」積み上げ棒グラフの修正が必要)。

そうなんです。OCR から読んだ列群は、その順番を維持したまま代入したいですね。
ということで、以下のようにしてはどうでしょうか？

1. 現在のスプレッドシートの E列：軽症無症状 は、列名は変更せずに、位置を後端（Q列の次？）へ移動（居場所に関係なく 軽症無症状の人数合計）
2. E列には、列名「入院_軽症無症状」として、入院中の 軽症無症状者数 （画像の 軽症・無症状）を入力

これで現在の表示プログラムに影響は与えず、本issueの内訳表示には、「入院_軽症無症状」項目を使えばよいことになります。

**Comment by takainou** [comment]
はい「入院_軽症無症状」の追加に賛同します。使わない項目が増えますが、意味が変わっているのでやむないですね。

移動するなら「入院中」と「軽症中等症」の間でしょうか。

スプレッドシート上では「入院中」同様計算式としますが、これらはOCR導入後はどのデータ(OCRorスプレッドシート)を用いても自動算出されると考えておけば良いでしょうかね(OCR導入後スプレッドシート側では計算式入力不要になる？)。

また、「検査陽性者状況の推移」積み上げ棒グラフの修正は、最終案提示させていただきました。

**Comment by amay077** [comment]
> 移動するなら「入院中」と「軽症中等症」の間でしょうか。

はい、そこで問題ないです。
今は我々が仕様変更過渡期なので、互換性維持優先で。
改修が落ち着いたら不要な列は削除していきましょう。

> スプレッドシート上では「入院中」同様計算式としますが、これらはOCR導入後はどのデータ(OCRorスプレッドシート)を用いても自動算出されると考えておけば良いでしょうかね(OCR導入後スプレッドシート側では計算式入力不要になる？)。

いえ、OCR導入後もスプレッドシート側の計算式入力は必要なままです。
OCR代替の最終手段としてのスプレッドシートは、現状の運用を維持するようにしました。

**Comment by takainou** [comment]
すみません、まだ分かってないのかもしれません。

OCR導入しても、スプレッドシートに「軽症無症状」の計算式を入れる必要がある
→
「軽症無症状」を参照しているアプリが無くなるまで、スプレッドシート入力を続ける必要がある
→
「入院_軽症無症状」の追加目的が良くわからないです。追加目的は「OCR移行を早くして、スプレッドシートの入力を止める為」だと理解してました。

追加目的「OCR から読んだ列群は、その順番を維持したまま代入したい」のは、「アプリにてそのまま表示したい」という意味でしょうか。

最初に提案した算出式
「軽症無症状」＝「入院」－「中等症」－「重症」
は、OCRの読み込み「入院」チェック機能と同義なので、そのまま表示と同義ですし、読み込みチェックが不整合なら、OCRの値が採用されないので、そのまま表示されないですよね。それなら、算出式で良いと考えます。

なお、追加目的「他の方が参照するケースを考慮し、意味が変わっているなら、別項目とする」なら理解出来ます。それですと他の項目も配慮必要なのかもしれません(「退院等」とか)。ちょっと考えてみます。

**Comment by amay077** [comment]
> OCR導入しても、スプレッドシートに「軽症無症状」の計算式を入れる必要がある

念のため再確認ですが、↑は、「OCR認識が失敗したと気づいた時」に、Google スプレッドシートに、

- 失敗した日の行を追加し
- 軽症無症状 と 入院中 の列には、計算式を設定する（現状の運用のまま）

です。OCR が成功した日はこれらは必要ありません。

> 「入院_軽症無症状」の追加目的が良くわからないです。追加目的は「OCR移行を早くして、スプレッドシートの入力を止める為」だと理解してました。
>
> 追加目的「OCR から読んだ列群は、その順番を維持したまま代入したい」のは、「アプリにてそのまま表示したい」という意味でしょうか。

追加目的は、本issue のためですが、
『「軽症無症状」＝「入院」－「中等症」－「重症」』で導き出すよりも、
画像に描かれている値を採用するほうが忠実と考えるためです（画像にない情報を計算式で導き出すべき）。

また、OCR では画像に描かれている項目の順番をそのまま CSV に書き出したいです（処理の簡略化のため）。
そして、OCR で出力した CSV（https://github.com/code4nagoya/covid19-aichi-tools/issues/44#issuecomment-675539849 の B）と、A と D である Google スプレッドシートはマージ処理の簡略化のため、列の順序を同じにしておきたいです。

Google スプレッドシートで設定している計算式を、取り込み時に再現することは不可能ではないですが、
現状、Google スプレッドシート(D) は、A とのマージのために読んでいるだけで、各行各列の値の加工は行いたくないです。

まとめると、

- 「入院_軽症無症状」列を E に追加するのは、画像に記載されている情報を可能な限りそのまま採用するのが元データに忠実でわかりやすい
- シートの計算式をマージ処理で再現しないのは、マージ処理はデータを読み出して結合することに専念して各行各列の値を加工しないことが望ましい

と考えるためです。

**Comment by takainou** [comment]
すみません、言い出したのは私ですが、撤回させて下さい。

本件など、OCR導入(スプレッドシート入力停止)前に検討した案件は、OCR導入(スプレッドシート入力停止)に伴う修正を考慮せずに検討してます。

申し訳ありませんが、私はまだ、OCR導入(スプレッドシート入力停止)に伴う影響をきちんと把握出来てません。

OCR導入(スプレッドシート入力停止)と、各案件の導入予定順序を先に決めて頂き、それぞれの影響を把握しながら、段階的に進めませんか。

本件は、OCR導入(スプレッドシート入力停止)前に導入するとして、進めさせて頂ければと考えています。

**Comment by amay077** [comment]
了解です。
まずは本 issue を実装しましょうか。

**Comment by amay077** [comment]
https://github.com/code4nagoya/covid19/issues/868#issuecomment-675001362 の右上の日付表示について、
すいません、私も撤回させてください。他のパネルも 時刻まで表示 と勘違いしてました。

なので、 

「パネル右上の更新日に時刻を表示してないので、省力化の為、スプレッドシートmain_summary「更新日時」の時刻入力を止め、「更新日」のみの入力とする」

で問題ありません。

**Comment by takainou** [comment]
実装ありがとうございます。

OCR導入(スプレッドシート入力停止)前に、最新の県HP画像に存在しない項目を参照している「検査陽性者の状況」一覧表(本Issue)および「検査陽性者の状況推移」積み上げ棒グラフは何らかの対応が必要と認識しています。他に、OCR導入(スプレッドシート入力停止)前に実装するだろうと考えられている案件があれば、共有して下さい。

main_summaryの更新時刻入力停止、ありがとうございます。早速明日朝より停止します。

**Comment by takainou** [comment]
> なお、追加目的「他の方が参照するケースを考慮し、意味が変わっているなら、別項目とする」なら理解出来ます。それですと他の項目も配慮必要なのかもしれません(「退院等」とか)。ちょっと考えてみます。

県HPの変更履歴は、以下の認識です

「入院中(旧)」＝「入院」＋「入院調整」＋「施設入所」＋「自宅療養」＋「調整」
「軽症中等症(旧)」＝「軽症無症状(新)」＋「中等症」＋「入院調整」＋「施設入所」＋「自宅療養」＋「調整」

4/9～
○「施設入所」追加
●「入院中(新)」＝「入院」＋「入院調整」＋「自宅療養」＋「調整」に意味変更
●「軽症中等症(新)」＝「軽症無症状(新)」＋「中等症」＋「入院調整」＋「自宅療養」＋「調整」に意味変更

7/24～
○「軽症中等症(新)」廃止、「軽症無症状(旧)」「中等症」に分割
○「軽症無症状(旧)」＝「軽症無症状(新)」＋「入院調整」＋「自宅療養」＋「調整」

7/30～(7/28,29は知事twitter)
○「入院」「入院調整」「自宅療養」「調整」を枠下に追加
○「入院中(新)」を「入院等」に表記変更
○「入院等」＝「入院」＋「入院調整」＋「自宅療養」＋「調整」のまま
○「軽症無症状(旧)」＝「軽症無症状(新)」＋「入院調整」＋「自宅療養」＋「調整」のまま

8/12～
○「入院等」(＝「入院中(新)」)廃止、「入院」「入院調整」「自宅療養」「調整」に分割
●「軽症無症状(新)」＝「軽症無症状(新)」のみに意味変更
●「退院」「転院」廃止、「退院等」追加、「退院等」＝「退院」＋「転院」

対応方針を、仮に
・県HPの値だけをmain_summary_historyとして残す
・意味が変わった場合は、項目名と列を変える
・過去だけの列も残す
とすると、●項目は未対応となり、スプレッドシートの列と項目名を変更する事になります
・「入院中」「軽症中等症」の4/9前後
・「退院」「軽症無症状」の8/12前後

でも、こんな分断されたデータ、他の方が参照して利用できるのでしょうか…。他の方が使えるようにしようと考えましたが、利用出来ないなら列と項目名を変更する価値が無い気がします。「軽症無症状」だけ対応するのもイマイチですよね。

**Comment by amay077** [comment]
> OCR導入(スプレッドシート入力停止)前に、最新の県HP画像に存在しない項目を参照している「検査陽性者の状況」一覧表(本Issue)および「検査陽性者の状況推移」積み上げ棒グラフは何らかの対応が必要と認識しています。

OCR結果の CSV は、現状と互換性を維持するようにします（具体的には、現在の [main_summary_history.csv](https://github.com/code4nagoya/covid19/blob/development/data/main_summary_history.csv) と同じ列群を同じ順序で出力します ）ので、アプリ側とは独立して OCR導入 は可能です。

**Comment by amay077** [comment]
> 追加目的「他の方が参照するケースを考慮し、意味が変わっているなら、別項目とする」なら理解出来ます。

すいません、Google スプレッドシートを実際にどう変更しようかではなく、私の好みとしては、この目的はアリです。
それから、この蓄積されたデータは、（本当は愛知県から提供されるべきだがそれがされないので）唯一無二の貴重な情報であるので、価値は高いと思っています。

ただ「意味が変わるなら別項目」は、データ原理主義的で、実際にはアプリ改修コストを下げるなどの別の理由もあったので、
「他の方が参照するケースを考慮し、意味が変わっているなら、別項目とする」は **目的としない** という意見にします。

ということで、本 issue 冒頭の以下対応はこの通りで実装されており、

>「軽症無症状」はスプレッドシートmain_summaryの値をそのまま使わず、以下で算出して表示する
>　「軽症無症状」＝「入院」－「中等症」－「重症」
>　←「検査陽性者の状況推移 積み上げ棒グラフ」が旧定義の「軽症・無症状」の為、
>　　県HPと異なる値をスプレッドシートmain_summaryに入力しており、本件を単独で対応可とする為

また OCR も現状と互換性を維持した出力になっておりアプリへの影響はなく、
現時点では、
「Google スプレッドシートの仕様は変更しない」
というのが結論でしょうか。

よろしければ本 issue は、PR https://github.com/code4nagoya/covid19/pull/879 のマージと共に close し、必要があれば別途 issue（検査陽性者の状況推移 積み上げ棒グラフの改修）で続けましょうか。

**Comment by takainou** [comment]
了解です。「検査陽性者の状況推移」積み上げグラフ修正時にはスプレッドシートへの入力を県HP通りに戻すので、そのIssueで継続議論とし、本IssueはCloseして下さい。

なお、「入院等の内訳にある入院のオープンデータが見つからない」という声はTwitter上で見た事も有り、需要がある事は認知しており、ただ、データ定義書が無いととても使えないぞとも考えました。

また、「軽症無症状」を数式で算出するのは、リーズナブルだと考えています。ここ数日、世間では
「大阪府は東京都よりも重症者が多い」
「人口呼吸器に早う繋いどるからや」
「んなこたぁない、手引き通りやっとるわ」
「東京都は重症者の定義が大阪府(=国)と違っていて一部含まれないぞ」
「最初(4/27)からだよ」
「対策サイトの注記を7月に黙って変えただろ」
「注記が最初から間違ってただけだ」
「少なく見せて黙って変えて隠蔽だろ」
「国の定義にしても38人で大阪府(65人)の方が多い」
という情けない議論がありますね。

症状は、重症の方の人数だけを数えて公表し国に報告している都道府県が多く、中等症を公表している都道府県は少ないです。全現在陽性者の症状を把握している訳ではなく、重症や中等症の方を数えているだけです(愛知県はまだ中等症の数え方が軌道に乗ってません。重症者は国の定義です)。そして症状別に考えれば自宅療養や施設入所も軽症無症状です。なので大阪府サイトのように入院の内訳として重症しか掲載しない見せ方もあります。愛知県は内訳を全て掲載しているので「入院」「重症」「中等症」を数えて、「軽症無症状」を単に数式で算出していると考えられ、その方法と同じという事になります。ただ県HPが計算を間違えた場合、当サイトが県HPのまま間違えておくべきかどうかは要議論なので、議論は継続しましょう。

**Comment by takainou** [comment]
本日の入力(8/19時点)より、
「更新日のみの入力(表示形式も変更)」
「備考の"入院等の内訳"記載停止」
としました。
なお、別件ですが、「入院」セル左上のExcelエラーは本日の画像にも表示されています。
