### ISSUE TITLE
他自治体の対策サイトへのリンク先を、本家サイトのまとめにする

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#88]
## 改善詳細 / Details of Improvement
- 現在愛知として[他自治体のサイトへのリンク集](https://stopcovid19.code4.nagoya/government)を用意しているが、今後増えていくことが予想されるため更新が追いつかない可能性がある。
- 本家サイトでも[同様のリンク集](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/forkedSites.md)が作られているため、愛知としてはそのページにリンクを貼って、他自治体のサイトを見つけたときは本体側を更新するほうが更新作業が一元化できて良いのではないか。

## スクリーンショット / Screenshot

![スクリーンショット 2020-03-15 18 41 23](https://user-images.githubusercontent.com/749758/76699042-9c5ee080-66ec-11ea-9a97-e89145322f08.png)
![スクリーンショット 2020-03-15 18 41 09](https://user-images.githubusercontent.com/749758/76699043-a385ee80-66ec-11ea-8a17-ca6a3f2fe44a.png)

## 期待する見せ方・挙動 / Expected behavior
- サイドバーのリンク先を[本家のforkSites.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/forkedSites.md)に変更する。
- 愛知のgovernmentは削除。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fussy113** [comment]
これ今から進めてきます〜
