### ISSUE TITLE
「検査陽性者の状況」推移全積み上げ棒グラフの県HP変更への追随

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19#894]
## 改善詳細 / Details of Improvement
- 7/28から、県HPの「検査陽性者の状況」の枠下注記に「入院等の内訳」が記載され始めました
- 8/13から、内訳は枠内に組み込まれ、掲載内容も変化しました(「入院等」「転院」の削除など)
- 当サイトの「検査陽性者の状況」推移も、県HPに追随する必要があります
- #830 にて議論して来たが、概ね合意が得られたので、本Issueを起票します

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/63571899/90993804-3eb2b680-e5f1-11ea-9dda-d883c07d82e5.png)

## 期待する見せ方・挙動 / Expected behavior
**[変更] 検査陽性者の状況(推移) 積み上げ棒グラフ**
- 主に退院の推移を把握する事、次に累計陽性者数の推移とその内訳を把握する事を目的とする
- 全積み上げグラフとし、凡例クリックによる表示/非表示で任意の項目の推移を確認できる
- 大きく２期間に分類して積み上げる
　1.入院等分割前(～7/27) 
　2.現時点(7/28～)
- 2.現時点(7/28～)は、９個の全積み上げで、症状の軽い順で下から
　「退院等」「施設入所」「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」「重症」「死亡」
　(「施設入所」は1.との連続性の為、症状は自宅療養よりも重いが下に配置する)
　「軽症無症状」＝「入院」－「重症」－「中等症」(7/28-8/11、8/12以降も計算式で同値となる)とする
　「退院等」＝「退院」＋「転院」(～8/11、8/12以降「転院」空欄につき同じ計算式で良い)とする
　ツールチップには９項目のみ表示し、「軽症中等症」は表示しない
- 1.入院等分割前(～7/27)は、５個の全積み上げで、症状の軽い順で下から
　「退院等」「施設入所」「軽症中等症」「重症」「死亡」
　「退院等」＝「退院」＋「転院」とする
　「軽症中等症」＝「軽症無症状」＋「中等症」(7/24-27、7/23以前は「中等症」空欄につき同じ計算式で良い)とする
　ツールチップには５項目のみ表示し、「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」は表示しない
- 1.の「軽症中等症」には2.の「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」が含まれており、 **1.→2.で「軽症中等症」が５分割される** 事になる
- 色の案は「自宅療養」= #0468F4 (「施設入所」と同じ緑系)、「入院調整」= #7F7F7F (「転院」の色、グレー系)、「調整」= #BFBFBF (「入院調整」と同じグレー系)
- 凡例は合計１０個となる(現時点の９個＋「軽症中等症」)
- パネル右上の数値は一番下の「退院等」とする(表記は退院のままで良い)
- 以下注記を修正する
　※7月24日より、[軽症中等症]が[軽症無症状]と[中等症]に分割されました
→※7/27以前の[軽症中等症]には、「自宅療養」「調整」「入院調整」「軽症無症状」「中等症」が含まれています
- スプレッドシートmain_summaryとOCR読み取り結果main_summary_recognized.csvの「軽症無症状」の値は、本改修と同時に、現在の暫定対応(「入院」－「重症」－「中等症」＋「自宅療養」＋「調整」＋「入院調整」)から、県HP画像の値(意味的には「入院」－「重症」－「中等症」)に、戻す(スプレッドシートmain_summaryは過去の値も戻す。8/12～最新。開発時も戻した値で行う)。これにより、暫定対応は無くなり、スプレッドシートmain_summaryやとOCR読み取り結果main_summary_recognized.csvには県HPの画像の値のみの入力/接続となる。

**Comment by amay077** [comment]
@takainou さん、

https://deploy-preview-906--dev-covid19-aichi.netlify.app/

で試せますが、

> スプレッドシートmain_summaryとOCR読み取り結果main_summary_recognized.csvの「軽症無症状」の値は、本改修と同時に、現在の暫定対応(「入院」－「重症」－「中等症」＋「自宅療養」＋「調整」＋「入院調整」)から、県HP画像の値(意味的には「入院」－「重症」－「中等症」)に、戻す(スプレッドシートmain_summaryは過去の値も戻す。8/12～最新。開発時も戻した値で行う)。これにより、暫定対応は無くなり、スプレッドシートmain_summaryやとOCR読み取り結果main_summary_recognized.csvには県HPの画像の値のみの入力/接続となる。

は考慮していません。
「開発時も戻した値で行う」のところが気になっています。
できたら、「値を戻した版のスプレッドシート」を、コピーして用意していだけないでしょうか？

**Comment by takainou** [comment]
開発ありがとうございます。やはり映えますね。パネル合体して初期表示しなくなるのはもったいない気がしてます。

> できたら、「値を戻した版のスプレッドシート」を、コピーして用意していだけないでしょうか？

データ＞古いファイル＞main_summary_test
に用意しました。元ファイルから以下の更新を行っています。
・8/20-21のデータを挿入
・8/12以降の「軽症無症状」を県HP画像の値(「入院」－「重症」－「中等症」)に、戻す

> は考慮していません。

現時点のアプリでは以下の個所が8/12以降も計算式となっているという事ですね。
>「軽症無症状」＝「入院」－「重症」－「中等症」(7/28-8/11、8/12以降も計算式で同値となる)とする

本アプリ、スプレッドシート入力、OCR読み込みの移行をどう行うかですが、せーので一斉移行する案を記載しています。やりやすい方法にて移行していただければと思います(スプレッドシート列追加案を以前提示頂いたのですが、その際は理解が追い付かずですみません)。

以下注記は削除頂いて良いと考えます(追加していただいた注記に含んでおり、7/24-27の「軽症無症状」「中等症」は煩雑になるので掲載していません)

> ※7月24日より、[軽症中等症]が[軽症無症状]と[中等症]に分割されました

数値確認は今夜に実施させてください。

**Comment by takainou** [comment]
> 数値確認は今夜に実施させてください。

数値確認完了いたしました。問題ありませんでした。ありがとうございます。

**Comment by amay077** [comment]
確認ありがとうございます。

「※7月24日より～」の注記は削除しました。

> 本アプリ、スプレッドシート入力、OCR読み込みの移行をどう行うかですが、せーので一斉移行する案を記載しています。やりやすい方法にて移行していただければと思います

スプレッドシートの「軽症無症状」の列はアプリでは使用しなくなりましたので、これでリリースしますね。

そのため、スプレッドシートの「軽症無症状を県HP画像の値に戻す」は、いつ行っていただいても大丈夫です。
（OCR から main_summary_reconized.csv を生成する処理の軽症無症状への設定値は修正する必要がありますが、現状の画像精度では認識失敗の可能性が高いので精度向上と合わせて実施します。）

**Comment by takainou** [comment]
注記修正ありがとうございます。リリース作業よろしくお願いします。

スプレッドシートmain_summaryは、今夜中に修正しておきます。

また、9:30時点の県HP画像が低解像度の場合、10時までに、スプレッドシートmain_summaryにデータ投入するようにします。

**Comment by amay077** [comment]
完了していると思われるので close します
