### ISSUE TITLE
さくらインターネットのロゴを追加！

### ISSUE THREAD

**Issue by takayashibagaki** [code4nagoya/covid19#94]
## 改善詳細 / Details of Improvement
- さくらインターネット様が、愛知県版のコロナサイトのためにクラウドを無償提供してして頂けることになりました！！！！　感謝の意を込めて、サイト内にさくらインターネットのロゴを掲載しましょう！

北海道のJUST道ITは、画面下部にロゴを埋め込んでいます。ご参考になりましたら幸いです。
<img width="265" alt="桜" src="https://user-images.githubusercontent.com/24749743/76763404-639b3600-67d6-11ea-8e24-652088a0b5d0.png">

**Comment by MURAMASA2470** [comment]
対応させていただきます
