### ISSUE TITLE
Support by Code for Nagoyaの表記を削除

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#96]
## 改善詳細 / Details of Improvement
- 現状で「Code for Nagoya」以外の団体もサポートしてくれているし、他の団体も参画しやすいよう表記を削除

## スクリーンショット / Screenshot
![68747470733a2f2f73636f6e74656e742d6c6178332d312e78782e666263646e2e6e65742f762f74312e302d392f38393338343431315f333839343234343231333932303931305f363038303639333633353433333632373634385f6f2e6a70673f5f6e635f6361743d313031265f6e635f7369643d636](https://user-images.githubusercontent.com/749758/76765665-1b7e1280-67da-11ea-9805-5bbd5b73da86.jpeg)

## 期待する見せ方・挙動 / Expected behavior
- 画像等から「Support by Code for Nagoya」の表記を削除

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by asukaokochi** [comment]
やります〜

**Comment by asukaokochi** [comment]
![ogp](https://user-images.githubusercontent.com/29916133/77245967-3d5a1800-6c66-11ea-8ca8-2193fc741e58.png)
ごめんなさい…
権限がなくcommitできないため、こちらもしよかったらどなたか代わりにpushしてもらえると嬉しいです…
