### ISSUE TITLE
SNSへのリンクを変更

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19#99]
## 起こっている問題 / The Problem
- Twitterアカウントを開設(https://twitter.com/stopcovid19ai )したのでTwitterのリンク先を差し替え。
- 愛知県公式のTwitter/LINE/Facebookアカウントの取り扱いについては、「愛知県公式SNS」と項目をわけるべき？(このサイトが愛知県のものであるような誤解を与えてしまうため)
- 「本サイトのSNS」という項目にTwitterとGitHubを掲載するほうが、公式とそうでない部分の棲み分けができて良いのでは。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/749758/76812490-629af080-6838-11ea-901f-567d56cdbd76.png)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by asukaokochi** [comment]
こちら、明日のお昼頃から着手しても良いでしょうか？？

**Comment by hajime-miyauchi** [comment]
北海道みたいなのが良さそう。

- 「愛知県公式Twitter」等はテキストの外部リンク表記
- このプロジェクトのGitHubと公式ツイッターはアイコン表記

<img width="237" alt="スクリーンショット 2020-03-20 17 25 23" src="https://user-images.githubusercontent.com/749758/77147107-e6223f00-6acf-11ea-8635-47f83b86e5f0.png">

**Comment by mikkame** [comment]
やります！
